### ISSUE TITLE
m0cp write need to create .img file first?

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#10]
followed https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md#16-perform-the-io

do we need to create .img file first?

> [root@ssc-vm-1091 cortx-hare]# hctl status
> Profile: 0x7000000000000001:0x22
> Data pools:
>     0x6f00000000000001:0x23
> Services:
>     localhost  (RC)
>     [started]  hax        0x7200000000000001:0x6   10.230.247.138@tcp:12345:1:1
>     [started]  confd      0x7200000000000001:0x9   10.230.247.138@tcp:12345:2:1
>     [started]  ioservice  0x7200000000000001:0xc   10.230.247.138@tcp:12345:2:2
>     [unknown]  m0_client  0x7200000000000001:0x1c  10.230.247.138@tcp:12345:4:1
>     [unknown]  m0_client  0x7200000000000001:0x1f  10.230.247.138@tcp:12345:4:2

> 
> [root@ssc-vm-1091 cortx-hare]# cortx/cortx-motr/motr/st/utils/m0cp -l 10.230.247.138@tcp:12345:4:1 -H 10.230.2                                   47.138@tcp:12345:1:1 \
> >      -p 0x7000000000000001:0x22 -P 0x7200000000000001:0x1c -o 12:10 \
> >      -s 1m -c 128 /var/misc/random.img -L 9
> -bash: cortx/cortx-motr/motr/st/utils/m0cp: No such file or directory
> [root@ssc-vm-1091 cortx-hare]# /var/cortx/cortx-motr/motr/st/utils/m0cp -l 10.230.247.138@tcp:12345:4:1 -H 10.                                   230.247.138@tcp:12345:1:1      -p 0x7000000000000001:0x22 -P 0x7200000000000001:0x1c -o 12:10      -s 1m -c 12                                   8 /var/misc/random.img -L 9
> m0_write failed! Object id 12:10rc = -1
> [root@ssc-vm-1091 cortx-hare]# /var/cortx/cortx-motr/motr/st/utils/m0cp -l 10.230.247.138@tcp:12345:4:1 -H 10.                                   230.247.138@tcp:12345:1:1      -p 0x7000000000000001:0x22 -P 0x7200000000000001:0x1c -o 14:10      -s 1m -c 12                                   8 /var/misc/random.img -L 9
> m0_write failed! Object id 14:10rc = -1

**Comment by huanghua78** [comment]
This issue is not seen any more.
