### ISSUE TITLE
Repeating cas_fom_tick rc=-2 errors from mero-server

### ISSUE THREAD

**Issue by rajkumarpatel2602** [Seagate/cortx-motr#100]
**_JIRA :_** 
https://jts.seagate.com/browse/EOS-8035

**_Affected Version(s) :_**
Cortx-1.0.0-rc1, Cortx-1.0.0-rc2

**_Steps to reproduce :_**
1. Deploy cluster
2. Configure and run S3 I/O: manual one using aws tool or using cosbench tool.
3. Check journalctl logs
4. [**_To generate this issue_**] Request to non-existing index 

**_Error log:_**
> May 06 17:44:43 sm29-r20.pun.seagate.com mero-server[232226]: mero[232226]:  bb20  ERROR  [cas/service.c:1147:cas_fom_tick]  <! rc=-2

**_Effect:_**
S3 I/O works, however such errors are generated multiple times.
Pacemaker resource doesn't not go to failed state - this is expected behavior.

**Comment by rajkumarpatel2602** [comment]
Issue is created so that our ever growing cortx community stay aware and one can avoid duplicated effort of issue creation in future.

**Comment by huanghua78** [comment]
This issue is closed: https://jts.seagate.com/browse/EOS-8035
