### ISSUE TITLE
motr unit test cas-client error

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#1012]
[root@ssc-vm-g3-rhev4-0505 cortx-motr]# scripts/m0 run-ut -t cas-client
----- run_ut -t cas-client -----
START Iteration: 1 out of 1
cas-client [Leonid]
  idx-create [Leonid] motr[23151]:  5860  FATAL  [lib/assert.c:50:m0_panic]  panic: Unit-test assertion failed: rc == 0 at cas_client_init() (cas/ut/client_ut.c:183)  [git: 2.0.0-307-32-g25afb2d] /var/motr/m0ut/m0trace.23151
Motr panic: Unit-test assertion failed: rc == 0 at cas_client_init() cas/ut/client_ut.c:183 (errno: 4) (last failed: none) [git: 2.0.0-307-32-g25afb2d] pid: 23151  /var/motr/m0ut/m0trace.23151
/var/cortx/cortx-motr/motr/.libs/libmotr.so.2(m0_arch_backtrace+0x20)[0x7f941a2f5bc0]
/var/cortx/cortx-motr/motr/.libs/libmotr.so.2(m0_arch_panic+0xe6)[0x7f941a2f5d76]
/var/cortx/cortx-motr/motr/.libs/libmotr.so.2(+0x379f44)[0x7f941a2e3f44]
/var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x285c12)[0x7f941ba0cc12]
/var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x14c604)[0x7f941b8d3604]
/var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x14dbca)[0x7f941b8d4bca]
/var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(m0_ut_run+0x263)[0x7f941ba0c533]
/var/cortx/cortx-motr/ut/.libs/lt-m0ut(main+0x11c9)[0x404709]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f94183bc555]
/var/cortx/cortx-motr/ut/.libs/lt-m0ut[0x404881]
/var/cortx/cortx-motr/utils/m0run: line 416: 23151 Aborted                 (core dumped) $(srcdir_path_of $binary) "$@"

**Comment by hessio** [comment]
Hi @huanghua78 do you know what the cause of this is?

**Comment by yanqingfu** [comment]
tested on the main branch. reboot VM still has the error. tested on two VMs still has the error
CentOS Linux release 7.9.2009 (Core), 3.10.0-1160.el7.x86_64

**Comment by huanghua78** [comment]
This is known issue.
Jira Ticket is created.

**Comment by yanqingfu** [comment]
noted

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

This issues is being addressed through  EOS-24883

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Fixed through [EOS-24883] ./scripts/m0 run-ut -t cas-client FAILED without -ETIMEOUT - JIRA NSS (seagate.com)

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Fixed through [EOS-24883] ./scripts/m0 run-ut -t cas-client FAILED without -ETIMEOUT - JIRA NSS (seagate.com)

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Verified.
