### ISSUE TITLE
pip install python-ipaddress failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#1057]
followed https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst
https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst#troubleshooting

If pip fails to install a package while installing build dependencies, try installing packages using pip installer. run the following commands if package is ipaddress:

sudo pip install python-ipaddress
sudo scripts/install-build-deps

[root@ssc-vm-g3-rhev4-1169 cortx-motr]# pip install python-ipaddress
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting python-ipaddress
  Could not find a version that satisfies the requirement python-ipaddress (from versions: )
No matching distribution found for python-ipaddress

**Comment by hessio** [comment]
I tried to reproduce this error, when I run `sudo scripts/install-build-deps` this completes without error, can you retry this on a fresh setup?

**Comment by yanqingfu** [comment]
the error I want to indicate is related to command **pip install python-ipaddress**
not with **scripts/install-build-deps**

**Comment by yanqingfu** [comment]
[root@ssc-vm-g3-rhev4-1169 ~]# pip --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
You have new mail in /var/spool/mail/root

**Comment by yanqingfu** [comment]
scripts/install-build-deps is running ok for me

I just want to test the mentioned debug process

**Comment by imvenkip** [comment]
> [root@ssc-vm-g3-rhev4-1169 ~]# pip --version
> pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
> You have new mail in /var/spool/mail/root

It's looking, your trying to execute command with root login.  

[root@ssc-vm-g3-rhev4-1169 744290]# rpm -qa | grep ipaddress
python-ipaddress-1.0.16-2.el7.noarch

**Comment by yanqingfu** [comment]
which means we need to put **yum install python-ipaddress**  or **pip install ipaddress** in the instruction?

[root@ssc-vm-g3-rhev4-1169 cortx-motr]# yum install python-ipaddress            Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-
              : manager
Loading mirror speeds from cached hostfile
 * epel: pubmirror1.math.uh.edu
EOS_CentOS-7_CentOS-7-Extras                             | 2.1 kB     00:00
EOS_CentOS-7_CentOS-7-OS                                 | 2.1 kB     00:00
EOS_CentOS-7_CentOS-7-Updates                            | 2.1 kB     00:00
EOS_EPEL-7_EPEL-7                                        | 2.1 kB     00:00
EOS_Puppet6_puppet6-el7                                  | 2.1 kB     00:00
Package python-ipaddress-1.0.16-2.el7.noarch already installed and latest version
Nothing to do
[root@ssc-vm-g3-rhev4-1169 cortx-motr]# pip install ipaddress
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting ipaddress
  Downloading https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
Installing collected packages: ipaddress
Successfully installed ipaddress-1.0.23

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
