### ISSUE TITLE
Problem to test the fdmi app in the fdmi-sample-app branch

### ISSUE THREAD

**Issue by lia54** [Seagate/cortx-motr#1062]
Hi, I am trying to test the fdmi app from this link:
https://github.com/Seagate/cortx-motr/tree/fdmi-sample-app/fdmi/plugins 
and I am having problems to find the fdmi filter id from the cluster settings.

I went over the code to see how they parse the /etc/motr/confd.xc to get this value and there is not line on that file starting with 0x6c value. 
Does this means the cluster is not running with this capability?
If that is not the case, where I can find the fdmi filter id value then?

**Comment by hessio** [comment]
I am not sure, @andriytk do you know?

**Comment by andriytk** [comment]
Maybe @max-seagate knows.

**Comment by max-seagate** [comment]
@lia54: https://github.com/Seagate/cortx-hare/pull/1631 is required for Hare to add FDMI filters to Motr configuration.

**Comment by johnbent** [comment]
@lia54 , yeah, please watch that PR and when it lands, then let's try again.

**Comment by lia54** [comment]
Thanks everyone! @johnbent @andriytk @max-seagate @hessio  
I asked @huanghua78 about it and he said I should work under the fdmi-int branch with a script he setup on the fdmi/plugins directory. I will follow up with him for the next set of problems.

**Comment by huanghua78** [comment]
Basically, these branches (e.g. fdmi-sample-app) are for internal use.
Actually, these branches should be deleted when PRs are merged.
Actually, these branches should not be created.

"Does this means the cluster is not running with this capability?"
Yes. The cluster is not running.

Please see the demo from @rajkumarpatel2602 and @huanghua78 , you will see how to run this.
I am closing this issue.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
