### ISSUE TITLE
Problem to run cortx cluster-motr --Cluster Bootstrap stuck in the Starting Motr phase

### ISSUE THREAD

**Issue by lia54** [Seagate/cortx-motr#1068]
I was trying to setup a cortx-motr cluster up and running using the following command:
`sudo hctl bootstrap --mkfs singlenode.yaml` and it got stuck into the `Starting Motr (phase1 , mkfs)` step. 
This has happened to me in the past and in some cases I was able to solve it by restarting the VM.
Does anyone know which one could be the cause of this issue?
Is it possible that some motr services are failed to restart after running `hctl shutdown` ?

**Comment by nkommuri** [comment]
While (phase1, mkfs) is stuck, can you please check if hax is running or crashed? In case it crashed, journalctl must have some info regarding the crash.

**Comment by lia54** [comment]
I checked the services and hare-hax service is failed I restarted it and I also have the network service marked as failed, but I could not restart it successfully.

**Comment by nkommuri** [comment]
Hi, did you find any useful info in journal log regarding hax crash? Which motr process is still running even after "hctl shutdown"? You can find it in "ps" output.

**Comment by mehjoshi** [comment]
Also, check using lsmod if the m0tr module is still left loaded. If so, unload it using rmmod.

**Comment by yanqingfu** [comment]
could you check the following:

**cat /etc/modprobe.d/lnet.conf**

**ip a**

and **data_iface** in singlenode.yaml file

**Comment by lia54** [comment]
I checked the cat /etc/modprobe.d/lnet.conf, ip a and data_iface in singlenode.yaml file and the three of them are ok using the same interface. 
I checked the m0tr modules after running hctl shutdown and there are two modules still loaded m0ctl and m0tr plus the galois module that it is used by m0tr. I was not able to remove the m0tr module since it says that is in used.

**Comment by lia54** [comment]
@nkommuri I was not getting any event regarding the hare-hax crashed in the journalctl. 
Is it possible that I am not being able to see the entire system log? 
When I tried sudo journalctl it does not show any output

**Comment by lia54** [comment]
@nkommuri I was able to check what is the output by running
`sudo journalctl --since <time_for_hare_crash>` with @andriytk help! 

This is the output of the log and as we can see in the bold section it seems that the Motr version was not compatible with the Hare one since I rebuild Motr using a different branch to be able to run some additional tests. 

`Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: 2021-09-27 09:54:02,036 [INFO] {MainThread} Welcome to HaX
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: 2021-09-27 09:54:02,036 [INFO] {MainThread} Setting up ha_link interface with the options as follows: hax fid = 0x7200000000000001:0x6, hax endpoint = 10.230.244.130@tcp:12345:1:1, HA fid = 0x7300000000000001:0x7
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: 2021-09-27 09:54:02,036 [DEBUG] {MainThread} Loading library from path: /opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/motr/../../libhax.cpython-36m-x86_64-linux-gnu.so
**Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: motr[00000]:  a100  ERROR  [ha/halon/interface.c:216:halon_interface_is_compatible]  The loaded motr library (571cbc7bb2a4ecf61ca4c4ee5f42cc2296b0ce54) is not the expected one (d35074f6098e762754d37030a01935a8602fa2ee)**
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: motr[00000]:  a100  ERROR  [ha/halon/interface.c:598:m0_halon_interface_init]  <! rc=-22
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: 2021-09-27 09:54:02,046 [ERROR] {MainThread} Cannot initialize Motr API. m0_halon_interface_init returned 0
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: Traceback (most recent call last):
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: File "/opt/seagate/cortx/hare/bin/hax", line 11, in <module>
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: sys.exit(main())
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/hax.py", line 130, in main
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: motr = Motr(planner=planner, ffi=ffi, herald=herald, consul_util=util)
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/motr/__init__.py", line 69, in __init__
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: raise RuntimeError('Cannot initialize Motr API')
Sep 27 09:54:02 smc3-m03.colo.seagate.com hare-hax[70837]: RuntimeError: Cannot initialize Motr API
Sep 27 09:54:02 smc3-m03.colo.seagate.com systemd[1]: hare-hax.service: main process exited, code=exited, status=1/FAILURE
Sep 27 09:54:02 smc3-m03.colo.seagate.com systemd[1]: Unit hare-hax.service entered failed state.
Sep 27 09:54:02 smc3-m03.colo.seagate.com systemd[1]: hare-hax.service failed.
Sep 27 09:54:02 smc3-m03.colo.seagate.com systemd[1]: hare-hax.service holdoff time over, scheduling restart.

**Comment by mengwanguc** [comment]
I also had this problem. 

The hctl bootstrap works fine after I installed motr and hare.

However, once I reboot the machine, hctl bootstrap doesn't work any more and is stuck at `Starting Motr (phase1 , mkfs)` just same as Liana...

I feel something is wrong when shutting down motr.

Therefore, when I use hare, I have to avoid shutting down hctl or rebooting the machine. Otherwise I may have to re-install everything.

Hope this problem can be resolved soon...

**Comment by nkommuri** [comment]
@lia54 Can you please try rebuilding the Hare. Thanks

**Comment by huanghua78** [comment]
As @lia54 mentioned in logs, the mismatch of Motr and Hare version may cause issues.

The Hare (Hare-Hax) is using Motr library. So, if a new version of Motr is installed, the Hare also need to be rebuilt and re-installed.
Before new version is updated and reinstalled, the Motr cluster should be shut down with "hctl shutdown".

Please note, the Motr and Hare are tightly coupled. The latest main branches from both components are suggested.

**Comment by lia54** [comment]
After checking out the main branch for cortx-motr and cortx-hare and rebuild afterwards, I was able to successfully bootstrap the cluster using the command: 
`hctl bootstrap --mkfs singlenode.yaml`

Thanks everyone for the help and feedback! @andriytk @nkommuri @huanghua78 @mehjoshi @yanqingfu @mengwanguc

**Comment by johnbent** [comment]
Awesome @lia54 ! Please go ahead and close this issue then.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github Issue closed

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github issue closed

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
