### ISSUE TITLE
Arm64 port to be added

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1128]
Arm64 port was implemented in context of Sage2 EU R&D project, and it is to be merged to main.

**Comment by cortx-admin** [comment]
> Andriy Tkachuk commented in Jira Server:

Please note: the change requires for all Motr clients to add -include config.h parameter to CFLAGS from now on to be able to compile. (In config.h file, the CONFIG_X86_64 and CONFIG_AARCH64 macros are defined.)
