### ISSUE TITLE
REGRESSION: Motr API compatibility is broken after DI introduction

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1166]
The DI (Data Integrity) feature introduced at commit 3a429ad broke Motr API compatibility: attr[] parameter to m0_obj_op() has to be NULL now if user did not put blocks' checksums into it (which indicates that the DI feature is off). This API change imposes the requirement to update all Motr client apps now, even if they don't need to use the DI feature.

@madhavemuri suggests restoring the compatibility by re-implementing the needed API change like this:
1) Introduce a new ENF_ flag to the attributes.
2) Check the flag and read the checksums from the attr[] only when the flag is set.
3) If the flag is not set - work as before without DI.

Such an approach would preserve Motr API compatibility, and would allow Motr client apps to work with the new Motr without any code modifications. For example, https://github.com/Seagate/cortx-motr/pull/1045 won't be needed.

**Comment by cortx-admin** [comment]
> Rajat Patil commented in Jira Server:

For this issue PR is created and the same is under review.

M0_ENF_DI flag is added to enable DI, If this flag is not set will work as before without DI.

**Comment by andriytk** [comment]
This must be fixed by now.

**Comment by cortx-admin** [comment]
> Yeshpal Jain commented in Jira Server:

[EOS-26312: enable di flag s3 api motr side changes by rajatpatil98 · Pull Request #1345 · Seagate/cortx-motr (github.com)|https://github.com/Seagate/cortx-motr/pull/1345]

**Comment by cortx-admin** [comment]
> Yeshpal Jain commented in Jira Server:

Flag is introduced to check for usage of attr variable, if M0_ENF_DI is enabled, than only attr variable will be used for data integrity.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comments
