### ISSUE TITLE
Libfabric runs in userspace only. Kernel UTs are disabled!

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1173]
Hi, 

I am build motr follow the quick start guide without using libfabric ( default should be lnet)

However, when I running kernel test, it show 

```
[root@ssc-vm-g3-rhev4-2033 cortx-motr]# sudo scripts/m0 run-kut
----- run_kut -----
Libfabric runs in userspace only. Kernel UTs are disabled!
m0kut: test status: SUCCESS
```

Any idea ?

**Comment by upendrapatwardhan** [comment]
@kiwionly2 
Can you please check if libfabric is uninstalled on your setup if you are using lnet.
If not, please follow the steps mentioned [here](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/711230113/Libfabric+setup+and+using+libfabric+with+motr#Uninstalling-libfabric-package)

**Comment by kiwionly2** [comment]
@upendrapatwardhan 

Yes, I had uninstall libfabric, then rebuild motr with latest code and run the test again.

However seem like same issue occurs.

![image](https://user-images.githubusercontent.com/77140436/141270150-c08e98fd-11fb-42b8-af62-1199dfe65140.png)

**Comment by upendrapatwardhan** [comment]
@kiwionly2 
based on `Libfabric runs in userspace only. Kernel UTs are disabled!` , I think there is some libfabric binary still present on your setup. Could you try the following
1. Search for fi_info using 'updatedb` and `locate fi_info`  and remove all fi_info instances.
2. Rebuild motr code `./scripts/m0 rebuild` 
3. Run the kut

**Comment by cortx-admin** [comment]
> Trupti Patil commented in Jira Server:

[~536285], Would you pls take this forward?
CC: [~715719], [~711131]

**Comment by cortx-admin** [comment]
> Anagha Deshmukh commented in Jira Server:

Hi, can you please check if libfabric rpm is uninstalled on your setup?

**Comment by kiwionly2** [comment]
@upendrapatwardhan 

I had manually remove all libfabric, now the test able to run.

Thanks !

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Fixed.
Addresses [#1173|https://github.com/Seagate/cortx-motr/issues/1173]

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Resolved

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Verified.
https://github.com/Seagate/cortx-motr/issues/1173#issuecomment-968531002
