### ISSUE TITLE
libfabric-devel is needed by cortx-motr-2.0.0-1_giteef39d9_3.10.0_1127.19.1.el7.x86_64

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-motr#1188]
When I follow Motr Quick Start Guide and run "make rpms", I got this error:

`libfabric-devel is needed by cortx-motr-2.0.0-1_giteef39d9_3.10.0_1127.19.1.el7.x86_64
`

This can be resolved by simply running `sudo yum install libfabric-devel`

Probably we need to add it to "install-build-deps"?

**Comment by r-wambui** [comment]
Ping folks via email for assistance.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26104. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by yanqingfu** [comment]
if you install libfabric, it will give this error: https://github.com/Seagate/cortx-motr/issues/1173

**Comment by cortx-admin** [comment]
> Kanchan Manohar Chaudhari commented in Jira Server:

PR Raised: https://github.com/Seagate/cortx-motr/pull/1254

**Comment by cortx-admin** [comment]
> Kanchan Manohar Chaudhari commented in Jira Server:

PR #1256 merged to main branch.

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Kanchan Chaudhari
* Component Build  :  371 
* Release Build    :  2123  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/centos-7.8.2003/2123 
{panel}

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Kanchan Chaudhari
* Component Build  :  158 
* Release Build    :  647  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/centos-7.9.2009/647 
{panel}

**Comment by cortx-admin** [comment]
> Zoheb Khan commented in Jira Server:

Validated with latest changes, error reported here is not observed. Hence, closing this as Done.
