### ISSUE TITLE
cortx-motr 08spiel-sns-repair-quiesce m0t1fs read failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#12]
> SNS Repair done.
> verifying ...
> m0t1fs read failed
> Failed: SNS repair failed..
> /var/motr/root/sandbox.st-08spiel-sns-repair-quiesce
> unmounting and cleaning..
> === pids of services: 2973 2966 2960 2956 2864 2772 2128 ===
> Shutting down services one by one. mdservice is the last.
> ----- 2973 stopping--------lt-m0d: got signal 1
> motr[02973]:  87e0  ERROR  [conf/rconfc.c:1181:rconfc_fail]  rconfc: 0x7fffb79def38, state M0_RCS_IDLE failed with -22
> motr[02973]:  c920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02973]:  c920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02973]:  c920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02973]:  c920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> ----- 2973 stopped --------
> ----- 2966 stopping--------lt-m0d: got signal 1
> motr[02966]:   f20  ERROR  [conf/rconfc.c:1181:rconfc_fail]  rconfc: 0x7ffc70317678, state M0_RCS_IDLE failed with -22
> motr[02966]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02966]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02966]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02966]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> ----- 2966 stopped --------
> ----- 2960 stopping--------lt-m0d: got signal 1
> motr[02960]:  4f00  ERROR  [conf/rconfc.c:1181:rconfc_fail]  rconfc: 0x7ffcee29b658, state M0_RCS_IDLE failed with -22
> motr[02960]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02960]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02960]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02960]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> ----- 2960 stopped --------
> ----- 2956 stopping--------lt-m0d: got signal 1
> motr[02956]:   e00  ERROR  [conf/rconfc.c:1181:rconfc_fail]  rconfc: 0x7fff83e07558, state M0_RCS_IDLE failed with -22
> motr[02956]:  9920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02956]:  9920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02956]:  9920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> motr[02956]:  9920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:1003
> ----- 2956 stopped --------
> ----- 2864 stopping--------lt-m0d: got signal 1
> ----- 2864 stopped --------
> ----- 2772 stopping--------lt-m0d: got signal 1
> motr[02772]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:800
> motr[02772]:  d920   WARN  [ha/link.c:1511:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.76@tcp:12345:33:900
> ----- 2772 stopped --------
> ----- 2128 stopping--------lt-m0d: got signal 1
> ----- 2128 stopped --------
> m0tr                13920594  0
> galois                 22944  1 m0tr
> lnet                  586401  3 m0tr,ksocklnd
> Motr services stopped.
> Test log available at /var/motr/root/sandbox.st-08spiel-sns-repair-quiesce/motr_2020-08-21_00:28:54.log.
> spiel-sns-repair-quiesce: FAILURE 1
> 183.60user 105.39system 4:43.16elapsed 102%CPU (0avgtext+0avgdata 830480maxresident)k
> 5852256inputs+10666112outputs (100major+2593141minor)pagefaults 0swaps

/var/motr/root/sandbox.st-08spiel-sns-repair-quiesce/motr_2020-08-21_00:28:54.log:

> 500+0 records in
> 500+0 records out
> 2048000 bytes (2.0 MB) copied, 5.10242 s, 401 kB/s
> 700+0 records in
> 700+0 records out
> 5734400 bytes (5.7 MB) copied, 0.00718364 s, 798 MB/s
> 700+0 records in
> 700+0 records out
> 5734400 bytes (5.7 MB) copied, 8.00079 s, 717 kB/s
> 300+0 records in
> 300+0 records out
> 4915200 bytes (4.9 MB) copied, 0.00545938 s, 900 MB/s
> **dd: error reading ‘/tmp/test_m0t1fs_21-08-2020_00:28:54/0:10002’: Input/output error**
> 138+0 records in
> 138+0 records out
> 2260992 bytes (2.3 MB) copied, 1.36536 s, 1.7 MB/s
> Unmounting file system ...
> mount | grep m0t1fs
> Cleaning up mount test directory...
> Unmounting file system ...
> mount | grep m0t1fs
> Cleaning up mount test directory...

**Comment by huanghua78** [comment]
currently 'm0t1fs' is not supported.
