### ISSUE TITLE
Create artificial aging tool

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#121]
It is very important to be able to test a system that is aged and that is fragmented and that is almost capacity full.  There's been a ton of excellent academic research about this. For example,
https://research.cs.wisc.edu/adsl/Publications/impressions-fast09.pdf
https://www.usenix.org/system/files/hotstorage19-paper-conway.pdf

However, what I believe most people do when they want to study an aged file system is they write some data generation tool that basically just writes and deletes and writes and deletes real objects for a really long time until the system is aged and full.  But with mass-capacity storage, this can take days or even weeks to age and fill a system.  It works (at the end of the process you have an aged and full system that has appropriate metadata structures describing all of the data that has been put into the system and not deleted) but it is very slow to actually put all that data.  

However, you maybe don't really need to actually put all that data; all you really need are the metadata structures describing that data.  For example, using file system terms: at the end of the aging process you'll have a ton of inodes and a ton of data blocks but all you really need to study the full and aged system are the inodes whereas the data blocks themselves are not as important(*).

Instead of this very slow process, would it be possible to merely write a set of metadata structures that describe a system as it would look after being aged and fragmented?  This could be done much much more quickly presumably.

(*) if you're studying compression or dedup or some other aspect of the system related to the data _content_, then yeah, the data blocks would be important.  But for many aging/filling studies, they probably aren't.

**Comment by r-wambui** [comment]
@nikitadanilov Any updates on this?  @truptiatseagate You have been assigned this issue on Jira could you please let's know if this is in the pipeline or a is this  planned for future sprints?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Comment from [~517711] on chat,

We still need this, but not as a high priority

**Comment by shashank-parulekar** [comment]
With effort, and time, we might be able to write a utility to populate metadata but for DI enabled builds this will not work as new data needs to be written (or existing data read) to calculate the CRC and embed it in the metadata.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this JIRA closed and the same will be tracked via CORTX-34060 which will be picked up in future PI based on available bandwidth
