### ISSUE TITLE
motr BE segment size should be configurable 

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-motr#122]
motr BE segment size should be configurable via provisioner. This is required for Cortx to run on 4U100 where the metadata disks are around ~300GB. Such can be a case in open source community where users may have different disks sizes.

Currently for physical setups are using 5T which is default in motr.conf 
`/opt/seagate/cortx/motr/conf/motr.conf:MOTR_M0D_BESEG_SIZE=5497558138880`
`/etc/sysconfig/motr `

Provisioner should have mechanism to update these values for uses via say cluster.sls

cc @johnbent @ipoddubnyy @ypise

**Comment by nkommuri** [comment]
@vidyadhar-pinglikar  Is this something being considered as part of Partition STOB implementation?

**Comment by nkommuri** [comment]
Response from Vidyadhar...

[12/13/2021 1:00 PM] Vidyadhar Pinglikar
seg size is provided on cmdline which is typically i guess from sysconfig; partition stob will use that size if provided on cmdline and if not will compute by itself

so to be specific i guess partition stob wont address it; and is out of scope of it.., it just use the size received from cmdline as i/p

in future when hare config will be used may be this will be implemented

**Comment by chandradharraval** [comment]
Added hare component as well

**Comment by chandradharraval** [comment]
Hi @madhavemuri , @vidyadhar-pinglikar ,
Do we still need this if partition stob will not be implemented?

**Comment by cortx-admin** [comment]
> Madhav Vemuri commented in Jira Server:

This is already covered through the size of meta-data device passed in solution.yaml.

[~520479] [~530903]: This ticket can be closed.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed based on above comments
