### ISSUE TITLE
LNet reporting drops.

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-motr#13]
Hello-

While operating under S3 load, a VM instance is logging these errors to the system log:

_[  435.699805] LNetError: 4944:0:(lib-ptl.c:190:lnet_try_match_md()) Matching packet from 12345-192.168.10                                       .13@tcp, match 9007199254740992 length 69632 too big: 1048576 left, 65536 allowed
[  435.699862] LNetError: 4944:0:(lib-ptl.c:190:lnet_try_match_md()) Skipped 45 previous similar messages
[  494.313371] LNet: 4943:0:(lib-move.c:3961:lnet_parse_put()) Dropping PUT from 12345-192.168.10.13@tcp portal 2 match 9007199254740992 offset 0 length 69632: 4
[  494.313376] LNet: 4943:0:(lib-move.c:3961:lnet_parse_put()) Skipped 79 previous similar messages
[  499.821820] LNetError: 4943:0:(lib-ptl.c:190:lnet_try_match_md()) Matching packet from 12345-192.168.10.13@tcp, match 9007199254740992 length 69632 too big: 1046376 left, 65536 allowed
[  499.821873] LNetError: 4943:0:(lib-ptl.c:190:lnet_try_match_md()) Skipped 75 previous similar messages_

Is anybody familiar with this error? Could it be related to TCP frame size?

Thanks,
-Tim

**Comment by andriytk** [comment]
@justinzw , @johnbent any idea who can check the above configuration parameters in our [VA](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst) and possibly fix?

**Comment by andriytk** [comment]
@mukul-seagate11 , @VenkyOS , @ipoddubnyy any idea who can fix it in our VA?

**Comment by mukul-seagate11** [comment]
@andriytk, did you try validating with new OVA image, https://github.com/Seagate/cortx/releases/download/VA/cortx-va-1.0.2.zip where multiple fixes as gone

**Comment by andriytk** [comment]
@mukul-seagate11 no. (I'm still waiting for the Fusion 11 license.) But can you check if the parameters I mentioned above are the same in Motr and s3server? (They are different in cortx-va-1.0.1.zip) If they are different, please set S3_MOTR_MAX_RPC_MSG_SIZE to the same value as MOTR_M0D_MAX_RPC_MSG_SIZE.

**Comment by mukul-seagate11** [comment]
@nileshgovande @madhavemuri, please verify the parameters in latest ova image

**Comment by nileshgovande** [comment]
Adding @sachitanands generally for OVA and @knrajnambiar76 for S3_MOTR_MAX_RPC_MSG_SIZE

**Comment by nkommuri** [comment]
Hi, 
As per @andriytk comment above, https://github.com/Seagate/cortx-motr/issues/13#issuecomment-696672912,   this is expected. Closing the ticket. Please reopen if you still see the issue even after Andriy's suggestion.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github issue closed

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
