### ISSUE TITLE
Dependencies question

### ISSUE THREAD

**Issue by gregnsk** [Seagate/cortx-motr#1385]
I'm building Motr following  https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst

I see that `sudo scripts/install-build-deps` installs Lustre. It also uses python 2.7

Why does it install Lustre if I'm not planning to use Lnet?

Also, do we have any dependency on Python 2?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27540. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Gregory Touretsky commented in Jira Server:

I also see the following statement in https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/711230113/Libfabric+setup+and+using+libfabric+with+motr:
"The default transport in the motr branch would be Lnet."

Is it still the case? 
Libfabric should be the default

[~520423]

**Comment by cortx-admin** [comment]
> Gregory Touretsky commented in Jira Server:

see also https://jts.seagate.com/browse/EOS-27542 and https://jts.seagate.com/browse/EOS-27543

**Comment by chandradharraval** [comment]
@gregnsk - Python dependencies mentioned under this ticket can be tracked under EOS-27542
@madhavemuri, @sg-shankar  - Can you confirm on Lustre/Lnet. I remember we decided to have Lnet support till we stabilize with Libfab

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~530002], [~520423],

Any update on above comment?

**Comment by cortx-admin** [comment]
> Shankar Tukaram More commented in Jira Server:

When we install dependency (./scripts/install-build-deps) both Libfbaric and LNet (Lusture) rpms gets installed, but the default transport will be Libfbaric. This can be checked by running following cmd after install deps.
 _
 bash-4.2$ fi_info --version 2
 fi_info: 1.11.2_

 To use LNet, user must uninstall the libfabric package and rebuild the motr code.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Question about Lustre is answered in above comments from [~530002]

[~530002] - ANy plan of removing lustre?

Python migration is going to be done via EOS-6081. Once that is merged we can resolve this issue
