### ISSUE TITLE
motr system test 44motr-rm-lock-cc-io Binary files /var/motr/src_file and /var/motr/dest_file2 differ Files differ, object got corrupted

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#14]
[root@ssc-vm-1061 cortx-motr]# ./scripts/m0 run-st 44motr-rm-lock-cc-io
----- run_st 44motr-rm-lock-cc-io -----
<< 44motr-rm-lock-cc-io >>
Motr RM lock CC_IO Test ...
n k p:2 1 4
vm.max_map_count = 30000000
motr_service_start: (N,K,P)=(3,2,20) nr_ios=4 multiple_pools=0
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00171417 s, 612 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00102611 s, 1.0 GB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00197831 s, 530 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00176288 s, 595 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00205684 s, 510 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00176585 s, 594 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00105214 s, 997 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00143888 s, 729 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00125449 s, 836 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00162947 s, 644 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00153473 s, 683 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00136677 s, 767 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00104768 s, 1.0 GB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00122198 s, 858 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00161536 s, 649 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00138145 s, 759 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00170309 s, 616 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00128074 s, 819 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00133179 s, 787 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00128733 s, 815 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00149068 s, 703 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.0016347 s, 641 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00149312 s, 702 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00142643 s, 735 MB/s

[152:
  {0x74| ((^t|1:0), 1, (11, 22), ^o|2:9, ^v|1:20, 1,
          [1: "20 3 2"],
          [1: ^n|1:2],
          [1: ^S|1:6],
          [3: ^o|1:9, ^o|20:1, ^o|2:9],
          [1: ^p|1:0], [0])},
  {0x70| ((^p|1:0), [3: ^o|1:9, ^o|20:1, ^o|2:9])},
  {0x6e| ((^n|1:2), 16000, 2, 3, 2, [8: ^r|1:100, ^r|1:0, ^r|1:1, ^r|1:2, ^r|1:3, ^r|1:4, ^r|1:5, ^r|1:6])},

  {0x72| ((^r|1:100), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:1", [1: ^s|1:101])},
  {0x72| ((^r|1:0), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:900", [8: ^s|1:0, ^s|11:0, ^s|6:0, ^s|7:0,                     ^s|3:0, ^s|13:0, ^s|15:0, ^s|16:0])},
  {0x72| ((^r|1:1), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:901", [8: ^s|1:1, ^s|11:1, ^s|6:1, ^s|7:1,                     ^s|3:1, ^s|13:1, ^s|15:1, ^s|16:1])},
  {0x72| ((^r|1:2), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:902", [8: ^s|1:2, ^s|11:2, ^s|6:2, ^s|7:2,                     ^s|3:2, ^s|13:2, ^s|15:2, ^s|16:2])},
  {0x72| ((^r|1:3), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:903", [8: ^s|1:3, ^s|11:3, ^s|6:3, ^s|7:3,                     ^s|3:3, ^s|13:3, ^s|15:3, ^s|16:3])},
 {0x72| ((^r|1:4), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:800", [3: ^s|2:0, ^s|12:0, ^s|3:4])},
 {0x72| ((^r|1:5), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:34:1",
                          [3: ^s|1:6, ^s|1:7, ^s|3:6])},
 {0x72| ((^r|1:6), [1:3], 0, 0, 0, 0, "192.168.47.113@tcp:12345:33:100",
                          [2: ^s|8:0, ^s|3:7])},
  {0x73| ((^s|8:0), @M0_CST_CONFD, [1: "192.168.47.113@tcp:12345:33:100"], [0], [0])},
  {0x73| ((^s|1:6), @M0_CST_HA, [1: "192.168.47.113@tcp:12345:34:1"], [0], [0])},
  {0x73| ((^s|1:7), @M0_CST_FIS, [1: "192.168.47.113@tcp:12345:34:1"], [0], [0])},
  {0x73| ((^s|1:101), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:1"], [0], [0])},

 {0x73| ((^s|2:0), @M0_CST_MDS, [1: "192.168.47.113@tcp:12345:33:800"], [0], [0])},
  {0x73| ((^s|12:0), @M0_CST_ADDB2, [1: "192.168.47.113@tcp:12345:33:800"], [0], [0])},
  {0x73| ((^s|3:4), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:800"], [0], [0])},

  {0x73| ((^s|1:0), @M0_CST_IOS, [1: "192.168.47.113@tcp:12345:33:900"], [0], [5: ^d|1:1, ^d|1:2, ^d|1:3, ^d|1:4, ^d|1:5])},
  {0x73| ((^s|11:0), @M0_CST_ADDB2, [1: "192.168.47.113@tcp:12345:33:900"], [0], [0])},
 {0x73| ((^s|6:0), @M0_CST_SNS_REP, [1: "192.168.47.113@tcp:12345:33:900"], [0], [0])},
  {0x73| ((^s|7:0), @M0_CST_SNS_REB, [1: "192.168.47.113@tcp:12345:33:900"], [0], [0])},
 {0x73| ((^s|3:0), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:900"], [0], [0])},
 {0x73| ((^s|13:0), @M0_CST_CAS, [1: "192.168.47.113@tcp:12345:33:900"], [0], [1: ^d|20:0])},
  {0x73| ((^s|15:0), @M0_CST_DIX_REP, [1: "192.168.47.113@tcp:12345:33:900"], [0], [0])},
  {0x73| ((^s|16:0), @M0_CST_DIX_REB, [1: "192.168.47.113@tcp:12345:33:900"], [0], [0])},
  {0x73| ((^s|1:1), @M0_CST_IOS, [1: "192.168.47.113@tcp:12345:33:901"], [0], [5: ^d|1:6, ^d|1:7, ^d|1:8, ^d|1:9, ^d|1:10])},
  {0x73| ((^s|11:1), @M0_CST_ADDB2, [1: "192.168.47.113@tcp:12345:33:901"], [0], [0])},
 {0x73| ((^s|6:1), @M0_CST_SNS_REP, [1: "192.168.47.113@tcp:12345:33:901"], [0], [0])},
  {0x73| ((^s|7:1), @M0_CST_SNS_REB, [1: "192.168.47.113@tcp:12345:33:901"], [0], [0])},
 {0x73| ((^s|3:1), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:901"], [0], [0])},
 {0x73| ((^s|13:1), @M0_CST_CAS, [1: "192.168.47.113@tcp:12345:33:901"], [0], [1: ^d|20:1])},
  {0x73| ((^s|15:1), @M0_CST_DIX_REP, [1: "192.168.47.113@tcp:12345:33:901"], [0], [0])},
  {0x73| ((^s|16:1), @M0_CST_DIX_REB, [1: "192.168.47.113@tcp:12345:33:901"], [0], [0])},
  {0x73| ((^s|1:2), @M0_CST_IOS, [1: "192.168.47.113@tcp:12345:33:902"], [0], [5: ^d|1:11, ^d|1:12, ^d|1:13, ^d|1:14, ^d|1:15])},
  {0x73| ((^s|11:2), @M0_CST_ADDB2, [1: "192.168.47.113@tcp:12345:33:902"], [0], [0])},
 {0x73| ((^s|6:2), @M0_CST_SNS_REP, [1: "192.168.47.113@tcp:12345:33:902"], [0], [0])},
  {0x73| ((^s|7:2), @M0_CST_SNS_REB, [1: "192.168.47.113@tcp:12345:33:902"], [0], [0])},
 {0x73| ((^s|3:2), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:902"], [0], [0])},
 {0x73| ((^s|13:2), @M0_CST_CAS, [1: "192.168.47.113@tcp:12345:33:902"], [0], [1: ^d|20:2])},
  {0x73| ((^s|15:2), @M0_CST_DIX_REP, [1: "192.168.47.113@tcp:12345:33:902"], [0], [0])},
  {0x73| ((^s|16:2), @M0_CST_DIX_REB, [1: "192.168.47.113@tcp:12345:33:902"], [0], [0])},
  {0x73| ((^s|1:3), @M0_CST_IOS, [1: "192.168.47.113@tcp:12345:33:903"], [0], [5: ^d|1:16, ^d|1:17, ^d|1:18, ^d|1:19, ^d|1:20])},
  {0x73| ((^s|11:3), @M0_CST_ADDB2, [1: "192.168.47.113@tcp:12345:33:903"], [0], [0])},
 {0x73| ((^s|6:3), @M0_CST_SNS_REP, [1: "192.168.47.113@tcp:12345:33:903"], [0], [0])},
  {0x73| ((^s|7:3), @M0_CST_SNS_REB, [1: "192.168.47.113@tcp:12345:33:903"], [0], [0])},
 {0x73| ((^s|3:3), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:903"], [0], [0])},
 {0x73| ((^s|13:3), @M0_CST_CAS, [1: "192.168.47.113@tcp:12345:33:903"], [0], [1: ^d|20:3])},
  {0x73| ((^s|15:3), @M0_CST_DIX_REP, [1: "192.168.47.113@tcp:12345:33:903"], [0], [0])},
  {0x73| ((^s|16:3), @M0_CST_DIX_REB, [1: "192.168.47.113@tcp:12345:33:903"], [0], [0])},

 {0x73| ((^s|3:6), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:34:1"], [0], [0])},
 {0x73| ((^s|3:7), @M0_CST_RMS, [1: "192.168.47.113@tcp:12345:33:100"], [0], [0])},
  {0x64| ((^d|1:1), 0, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop1")},
 {0x6b| ((^k|1:1), ^d|1:1, [1: ^v|1:10])},
 {0x6a| ((^j|1:1), ^k|1:1, [0])},
 {0x64| ((^d|1:2), 1, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop2")},
 {0x6b| ((^k|1:2), ^d|1:2, [1: ^v|1:10])},
 {0x6a| ((^j|1:2), ^k|1:2, [0])},
 {0x64| ((^d|1:3), 2, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop3")},
 {0x6b| ((^k|1:3), ^d|1:3, [1: ^v|1:10])},
 {0x6a| ((^j|1:3), ^k|1:3, [0])},
 {0x64| ((^d|1:4), 3, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop4")},
 {0x6b| ((^k|1:4), ^d|1:4, [1: ^v|1:10])},
 {0x6a| ((^j|1:4), ^k|1:4, [0])},
 {0x64| ((^d|1:5), 4, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop5")},
 {0x6b| ((^k|1:5), ^d|1:5, [1: ^v|1:10])},
 {0x6a| ((^j|1:5), ^k|1:5, [0])},
 {0x64| ((^d|1:6), 5, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop6")},
 {0x6b| ((^k|1:6), ^d|1:6, [1: ^v|1:10])},
 {0x6a| ((^j|1:6), ^k|1:6, [0])},
 {0x64| ((^d|1:7), 6, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop7")},
 {0x6b| ((^k|1:7), ^d|1:7, [1: ^v|1:10])},
 {0x6a| ((^j|1:7), ^k|1:7, [0])},
 {0x64| ((^d|1:8), 7, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop8")},
 {0x6b| ((^k|1:8), ^d|1:8, [1: ^v|1:10])},
 {0x6a| ((^j|1:8), ^k|1:8, [0])},
 {0x64| ((^d|1:9), 8, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop9")},
 {0x6b| ((^k|1:9), ^d|1:9, [1: ^v|1:10])},
 {0x6a| ((^j|1:9), ^k|1:9, [0])},
 {0x64| ((^d|1:10), 9, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop10")},
 {0x6b| ((^k|1:10), ^d|1:10, [1: ^v|1:10])},
 {0x6a| ((^j|1:10), ^k|1:10, [0])},
 {0x64| ((^d|1:11), 10, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop11")},
 {0x6b| ((^k|1:11), ^d|1:11, [1: ^v|1:10])},
 {0x6a| ((^j|1:11), ^k|1:11, [0])},
 {0x64| ((^d|1:12), 11, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop12")},
 {0x6b| ((^k|1:12), ^d|1:12, [1: ^v|1:10])},
 {0x6a| ((^j|1:12), ^k|1:12, [0])},
 {0x64| ((^d|1:13), 12, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop13")},
 {0x6b| ((^k|1:13), ^d|1:13, [1: ^v|1:10])},
 {0x6a| ((^j|1:13), ^k|1:13, [0])},
 {0x64| ((^d|1:14), 13, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop14")},
 {0x6b| ((^k|1:14), ^d|1:14, [1: ^v|1:10])},
 {0x6a| ((^j|1:14), ^k|1:14, [0])},
 {0x64| ((^d|1:15), 14, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop15")},
 {0x6b| ((^k|1:15), ^d|1:15, [1: ^v|1:10])},
 {0x6a| ((^j|1:15), ^k|1:15, [0])},
 {0x64| ((^d|1:16), 15, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop16")},
 {0x6b| ((^k|1:16), ^d|1:16, [1: ^v|1:10])},
 {0x6a| ((^j|1:16), ^k|1:16, [0])},
 {0x64| ((^d|1:17), 16, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop17")},
 {0x6b| ((^k|1:17), ^d|1:17, [1: ^v|1:10])},
 {0x6a| ((^j|1:17), ^k|1:17, [0])},
 {0x64| ((^d|1:18), 17, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop18")},
 {0x6b| ((^k|1:18), ^d|1:18, [1: ^v|1:10])},
 {0x6a| ((^j|1:18), ^k|1:18, [0])},
 {0x64| ((^d|1:19), 18, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop19")},
 {0x6b| ((^k|1:19), ^d|1:19, [1: ^v|1:10])},
 {0x6a| ((^j|1:19), ^k|1:19, [0])},
 {0x64| ((^d|1:20), 19, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop20")},
 {0x6b| ((^k|1:20), ^d|1:20, [1: ^v|1:10])},
 {0x6a| ((^j|1:20), ^k|1:20, [0])},
  {0x53| ((^S|1:6), [1: ^a|1:6], [3: ^v|1:10, ^v|1:20, ^v|2:10])},
  {0x61| ((^a|1:6), [1: ^e|1:7], [3: ^v|1:10, ^v|1:20, ^v|2:10])},
  {0x65| ((^e|1:7), [1: ^c|1:8], [3: ^v|1:10, ^v|1:20, ^v|2:10])},
  {0x63| ((^c|1:8), ^n|1:2, [24: ^k|1:1, ^k|1:2, ^k|1:3, ^k|1:4, ^k|1:5, ^k|1:6, ^k|1:7, ^k|1:8, ^k|1:9, ^k|1:10, ^k|1:11, ^k|1:12, ^k|1:13, ^k|1:14, ^k|1:15, ^k|1:16, ^k|1:17, ^k|1:18, ^k|1:19, ^k|1:20, ^k|20:0, ^k|20:1, ^k|20:2, ^k|20:3],
                            [3: ^v|1:10, ^v|1:20, ^v|2:10])},
  {0x6f| ((^o|1:9), 0, [3: ^v|1:10, ^v|0x40000000000001:11, ^v|0x40000000000001:12])},
  {0x76| ((^v|1:10), {0| (3, 2,
                                            20,
                                            [5: 0, 0, 0, 0, 2],
                                            [1: ^j|1:21])})},
  {0x76| ((^v|0x40000000000001:11), {1| (0, ^v|1:10, [5: 0, 0, 0, 0, 1])})},
  {0x76| ((^v|0x40000000000001:12), {1| (1, ^v|1:10, [5: 0, 0, 0, 0, 2])})},
  {0x6a| ((^j|1:21), ^S|1:6, [1: ^j|1:22])},
  {0x6a| ((^j|1:22), ^a|1:6, [1: ^j|1:23])},
  {0x6a| ((^j|1:23), ^e|1:7, [1: ^j|1:24])},
  {0x6a| ((^j|1:24), ^c|1:8, [20: ^j|1:1, ^j|1:2, ^j|1:3, ^j|1:4, ^j|1:5, ^j|1:6, ^j|1:7, ^j|1:8, ^j|1:9, ^j|1:10, ^j|1:11, ^j|1:12, ^j|1:13, ^j|1:14, ^j|1:15, ^j|1:16, ^j|1:17, ^j|1:18, ^j|1:19, ^j|1:20])} ,
{0x6f| ((^o|2:9), 0, [1: ^v|2:10])},
{0x76| ((^v|2:10), {0| (4, 0, 4, [5: 0, 0, 0, 0, 1], [1: ^j|2:21])})},
{0x6a| ((^j|2:21), ^S|1:6, [1: ^j|2:22])},
{0x6a| ((^j|2:22), ^a|1:6, [1: ^j|2:23])},
{0x6a| ((^j|2:23), ^e|1:7, [1: ^j|2:24])},
{0x6a| ((^j|2:24), ^c|1:8, [4: ^j|2:1, ^j|2:6, ^j|2:11, ^j|2:16])},
{0x6a| ((^j|2:1), ^k|1:1, [0])},
 {0x6a| ((^j|2:6), ^k|1:6, [0])},
 {0x6a| ((^j|2:11), ^k|1:11, [0])},
 {0x6a| ((^j|2:16), ^k|1:16, [0])}  ,
{0x64| ((^d|20:0), 20, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop25")},
{0x6b| ((^k|20:0), ^d|20:0, [1: ^v|1:20])},
{0x6a| ((^j|20:100), ^k|20:0, [0])},
{0x64| ((^d|20:1), 21, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop26")},
{0x6b| ((^k|20:1), ^d|20:1, [1: ^v|1:20])},
{0x6a| ((^j|20:101), ^k|20:1, [0])},
{0x64| ((^d|20:2), 22, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop27")},
{0x6b| ((^k|20:2), ^d|20:2, [1: ^v|1:20])},
{0x6a| ((^j|20:102), ^k|20:2, [0])},
{0x64| ((^d|20:3), 23, 4, 1, 4096, 596000000000, 3, 4, "/dev/loop28")},
{0x6b| ((^k|20:3), ^d|20:3, [1: ^v|1:20])},
{0x6a| ((^j|20:103), ^k|20:3, [0])},
{0x6f| ((^o|20:1), 0, [1: ^v|1:20])},
{0x76| ((^v|1:20), {0| (1, 1, 4,
                                                    [5: 0, 0, 0, 0, 1],
                                                    [1: ^j|20:1])})},
{0x6a| ((^j|20:1), ^S|1:6, [1: ^j|20:2])},
{0x6a| ((^j|20:2), ^a|1:6, [1: ^j|20:3])},
{0x6a| ((^j|20:3), ^e|1:7, [1: ^j|20:4])},
{0x6a| ((^j|20:4), ^c|1:8, [4:  ^j|20:100, ^j|20:101, ^j|20:102, ^j|20:103])}]
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -T linux -e lnet:192.168.47.113@tcp:12345:35:1 -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd && exec /var/cortx/cortx-motr/motr/m0d -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -f '<0x7200000000000001:6>' -T linux -e lnet:192.168.47.113@tcp:12345:33:100 -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0d.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ha && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -T ad -e lnet:192.168.47.113@tcp:12345:35:1 -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
lt-m0d: systemd notifications not allowed

Started
Press CTRL+C to quit.
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/mds1 && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -T ad -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:35:800 -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios1 && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:35:900 -f '<0x7200000000000001:0>' -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios2 && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:35:901 -f '<0x7200000000000001:1>' -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios3 && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:35:902 -f '<0x7200000000000001:2>' -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios4 && exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:35:903 -f '<0x7200000000000001:3>' -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0mkfs.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ha && exec /var/cortx/cortx-motr/motr/m0d -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -T ad -e lnet:192.168.47.113@tcp:12345:34:1 -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc -f '<0x7200000000000001:5>' -H 192.168.47.113@tcp:12345:34:1 |& tee -a m0d.log
lt-m0d: systemd notifications not allowed

Started
Press CTRL+C to quit.
Motr HA agent started.
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/mds1 && exec /var/cortx/cortx-motr/motr/m0d -T ad -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:33:800 -f '<0x7200000000000001:4>' -H 192.168.47.113@tcp:12345:34:1 -c /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/confd/conf.xc |& tee -a m0d.log
lt-m0d: systemd notifications not allowed

Started
Press CTRL+C to quit.
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios1 && exec /var/cortx/cortx-motr/motr/m0d -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:33:900 -f '<0x7200000000000001:0>' -H 192.168.47.113@tcp:12345:34:1 |& tee -a m0d.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios2 && exec /var/cortx/cortx-motr/motr/m0d -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:33:901 -f '<0x7200000000000001:1>' -H 192.168.47.113@tcp:12345:34:1 |& tee -a m0d.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios3 && exec /var/cortx/cortx-motr/motr/m0d -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:33:902 -f '<0x7200000000000001:2>' -H 192.168.47.113@tcp:12345:34:1 |& tee -a m0d.log
cd /var/motr/root/sandbox.st-44motr-rm-lock-cc-io/ios4 && exec /var/cortx/cortx-motr/motr/m0d -T ad -d disks.conf -D db -S stobs -A linuxstob:addb-stobs -w 20 -m 65536 -q 16 -N 100663296 -C 262144 -K 100663296 -k 262144 -e lnet:192.168.47.113@tcp:12345:33:903 -f '<0x7200000000000001:3>' -H 192.168.47.113@tcp:12345:34:1 |& tee -a m0d.log
Motr confd started.
Motr mdservices started.
lt-m0d: systemd notifications not allowed

lt-m0d: systemd notifications not allowed

lt-m0d: systemd notifications not allowed

lt-m0d: systemd notifications not allowed

Started
Press CTRL+C to quit.
Started
Press CTRL+C to quit.
Started
Press CTRL+C to quit.
Started
Press CTRL+C to quit.
Motr ioservices started.
motr service started
*** m0dixinit is omitted. Mkfs creates meta indices now.
Read obj while write/update is in process.
Delete obj while write/update is in process.
Delete obj while read is in process.
Test exclusivity among Readers and Writers
**Binary files /var/motr/src_file and /var/motr/dest_file2 differ
Files differ, object got corrupted**
=== pids of services: 3976 3966 3959 3955 3860 3768 3119 ===
Shutting down services one by one. mdservice is the last.
----- 3976 stopping--------lt-m0d: got signal 1
motr[03976]:  cf80  ERROR  [conf/rconfc.c:1182:rconfc_fail]  rconfc: 0x7ffe676836e0, state M0_RCS_IDLE failed with -22
----- 3976 stopped --------
----- 3966 stopping--------lt-m0d: got signal 1
motr[03966]:  fc80  ERROR  [conf/rconfc.c:1182:rconfc_fail]  rconfc: 0x7ffca15f63e0, state M0_RCS_IDLE failed with -22
----- 3966 stopped --------
----- 3959 stopping--------lt-m0d: got signal 1
motr[03959]:  2160  ERROR  [conf/rconfc.c:1182:rconfc_fail]  rconfc: 0x7ffd03e388c0, state M0_RCS_IDLE failed with -22
----- 3959 stopped --------
----- 3955 stopping--------lt-m0d: got signal 1
motr[03955]:  5990  ERROR  [conf/rconfc.c:1182:rconfc_fail]  rconfc: 0x7ffdc620c0f0, state M0_RCS_IDLE failed with -22
----- 3955 stopped --------
----- 3860 stopping--------lt-m0d: got signal 1
----- 3860 stopped --------
----- 3768 stopping--------lt-m0d: got signal 1
motr[03768]:  c920   WARN  [ha/link.c:1513:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.113@tcp:12345:33:800
motr[03768]:  c920   WARN  [ha/link.c:1513:ha_link_outgoing_fom_tick]  rlk_rc=-110 endpoint=192.168.47.113@tcp:12345:33:900
----- 3768 stopped --------
----- 3119 stopping--------lt-m0d: got signal 1
----- 3119 stopped --------
m0tr                13922622  0
galois                 22944  1 m0tr
lnet                  586401  3 m0tr,ksocklnd
Motr services stopped.

Test log file available at /var/motr/motr_2020-09-10_21:59:39.log
Motr trace files are available at: /var/motr/motr
145.77user 19.98system 3:34.03elapsed 77%CPU (0avgtext+0avgdata 738268maxresident)k
237944inputs+4119232outputs (87major+1979821minor)pagefaults 0swaps

after reboot, the error still exists

**Comment by huanghua78** [comment]
This is fixed.

**Comment by yanqingfu** [comment]
double-checked. it passed
