### ISSUE TITLE
Document for how motr work in high level detail 

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1401]
Hi, 

I am trying to run some sample for motr client from  `motr/examples` and `bindings/go` sample, it is working accordingly. 

Smple below show how I am running go client binding for mkv.

> ./mkv -prof 0x7000000000000001:0 -hax 192.168.54.176@tcp:12345:34:1 -proc 0x7200000000000001:64 -ep 192.168.54.176@tcp:12345:33:1000 -c 0x7800000000000123:0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 

Some how I still could not understand how the underlying system work, ( even for some parameter, I am trial and error and hopefully it just work )

Is that any documentation that could describe how motr work on high level ? e.g. how the client server interact, how the cluster connect ( tcp ? ) also the format of profile id, process id, the object type of file ( for copy ) or the correct type of key value.

I do read some document in `/doc` folder and it is actually quite low level for me, which still a bit trouble to understand how motr work.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27661. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Hi @kiwionly2 I think you are right it is difficult to find a lot of the answers to these things, we are working on improving this however. Have you had a look at `/doc/pdf` there are a lot of pdfs that begin with HDL(

**Comment by hessio** [comment]
Hi @kiwionly2 I think you are right it is difficult to find a lot of the answers to these things, we are working on improving this however. Have you had a look at `/doc/pdf` there are a lot of pdfs that are prefixed with "HDL" (High-Level Description) and I found them to be pretty useful myself. Here are some I think might be helpful to your questions:  
[https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/Motr_architectural_2-pager.pdf](https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/Motr_architectural_2-pager.pdf)  
[https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/Motr_Data_Organization.pdf](https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/Motr_Data_Organization.pdf)  
[https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/mero_technical_whitepaper.pdf](https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/mero_technical_whitepaper.pdf)  
https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/Motr_FAQ.pdf  
  
**Note:** Motr used to be called "Mero" and I think "Colibri" so don't let the naming confuse you.  
  
This reading list may help you in the right direction too: https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/Motr_reading_list.pdf  
  
I will cc @andriytk as he may know this better than I.

**Comment by chandradharraval** [comment]
@kiwionly2 - Are you getting required information from documents shared by @hessio ? If yes then can we close this ticket?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking the Jira Closed as corresponding Github issue is closed now based on documentation links shared above
