### ISSUE TITLE
Outdated link in Reading list

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1403]
While browse thought the documentation : [reading list](https://github.com/Seagate/cortx-motr/blob/main/doc/reading-list.md), I found that link in [Network](https://github.com/Seagate/cortx-motr/blob/main/doc/reading-list.md#network) session : [LNET: Lustre Networking](https://wiki.lustre.org/Lid/ulfi/ulfi_lnet.html) no longer have correct information.

![image](https://user-images.githubusercontent.com/77140436/150100140-f429cf40-db88-452e-a2e6-fb0e834be82c.png)

**Comment by r-wambui** [comment]
@kiwionly2 should this be the correct reference link? -> https://wiki.lustre.org/Lustre_Networking_(LNET)_Overview

**Comment by kiwionly2** [comment]
@r-wambui 

This seem like correct, maybe some one could help to confirm ?

**Comment by r-wambui** [comment]
@johnbent you're one of the contributors of the reading-list.md, could you please confirm the link above so we can update accordingly.

**Comment by johnbent** [comment]
Yes, this is the correct link. Thanks @r-wambui and @kiwionly2 !

**Comment by chandradharraval** [comment]
@kiwionly2 - Can you close this issue as per confirmation from @johnbent ?

**Comment by kiwionly2** [comment]
Issue fixed.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comments
