### ISSUE TITLE
Improvements in Reading List

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#143]
https://github.com/Seagate/cortx-motr/blob/main/doc/motr-design-doc-list.rst

@VenkyOS , please do the following:

1. Add a Column for Title
2. Replace the titles in the actual links with 'PDF', 'RST', 'GDOC', 'DOCX' or 'PPTX' or whatever.  This will make the table much skinnier and more readable.
3. Change the Column Headers to the following:
'Sr. No', 'Source File', 'Source Line', 'Title', 'PDF', 'GitHub', 'Google', 'SharePoint'.

Also, there are some issues with the numbering I saw.

**Comment by VenkyOS** [comment]
@johnbent - I will work on the same,

**Comment by VenkyOS** [comment]
@johnbent - I have made the changes accordingly.

**Comment by nkommuri** [comment]
Hi @VenkyOS , if the requested changes are done, please close the ticket. thanks

**Comment by johnbent** [comment]
@nkommuri , @VenkyOS is no longer at Seagate. These tickets can be reassigned to @swatid-seagate. FYI @novium258

**Comment by r-wambui** [comment]
@swatid-seagate Any update on this?

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Started working on it.

**Comment by chandradharraval** [comment]
@swatid-seagate - Any further progress on this task?

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

I had a word with @RachelNovak about improving the above document. It seems an old format  needs conversion. Also, there are suggested improvements. I will be starting afresh creating new document for this.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

This job remains unsolved due to inadequate time.

**Comment by chandradharraval** [comment]
Hi @novium258,
Has Swati given any handover to anyone in team for work already completed for this issue?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
