### ISSUE TITLE
Kernel module compilation fails with --enable-debug

### ISSUE THREAD

**Issue by sergey-shilov** [Seagate/cortx-motr#1435]
On the Centos 8 and Rocky Linux 8.4 I'm getting the compiler error when I the motr is configured with --enable-debug. The user space code is compiled without errors, so it's related to kernel modules only.

Centos 8 versions:
{noformat}
bash-4.4$ cat /etc/redhat-release
CentOS Stream release 8
bash-4.4$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-6)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
{noformat}

Rocky Linux 8.4 versions:
{noformat}
bash-4.4$ cat /etc/redhat-release
Rocky Linux release 8.4 (Green Obsidian)
bash-4.4$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
{noformat}

The compiler error:
{noformat}
  CC [M]  /devel/cortx-motr/m0t1fs/linux_kernel/file.o
In file included from ././include/linux/compiler_types.h:58,
                 from <command-line>:
./arch/x86/include/asm/jump_label.h: In function ‘page_is_devmap_managed’:
./include/linux/compiler-gcc.h:305:38: error: asm operand 0 probably doesn’t match constraints [-Werror]
 #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                      ^~~
./arch/x86/include/asm/jump_label.h:38:2: note: in expansion of macro ‘asm_volatile_goto’
  asm_volatile_goto("1:"
  ^~~~~~~~~~~~~~~~~
./include/linux/compiler-gcc.h:305:38: error: asm operand 1 probably doesn’t match constraints [-Werror]
 #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                      ^~~
./arch/x86/include/asm/jump_label.h:38:2: note: in expansion of macro ‘asm_volatile_goto’
  asm_volatile_goto("1:"
  ^~~~~~~~~~~~~~~~~
./include/linux/compiler-gcc.h:305:38: error: impossible constraint in ‘asm’
 #define asm_volatile_goto(x...) do { asm goto(x); asm (""); } while (0)
                                      ^~~
./arch/x86/include/asm/jump_label.h:38:2: note: in expansion of macro ‘asm_volatile_goto’
  asm_volatile_goto("1:"
  ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:316: /devel/cortx-motr/m0t1fs/linux_kernel/file.o] Error 1
make[2]: *** [Makefile:1571: _module_/devel/cortx-motr] Error 2
make[1]: *** [Makefile:20536: build-kernel-modules] Error 2
make: *** [Makefile:4497: all] Error 2
{noformat}

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28457. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Sergey Shilov commented in Jira Server:

Both Centos 8 and Rocky Linux 8.4 were taken from G4 infra.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

[~520479] can someone help here on priority? this may block progress on https://jts.seagate.com/browse/EOS-27594 .  [~535284] is facing this while compiling motr code in debug mode.

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

I was able to fix the compilation issue with the below patch
{code:java}
# git diff
diff --git a/configure.ac b/configure.ac
index 58bad1d1..57b32fa7 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1057,7 +1057,7 @@ AS_IF([test x$enable_debug = xyes],
        M0_CPPFLAGS="-DDEBUG $M0_CPPFLAGS"
        M0_KCPPFLAGS="-DDEBUG $M0_KCPPFLAGS"
        M0_CFLAGS="-g -O0 $M0_CFLAGS"
-       M0_KCFLAGS="-g -O0 $M0_KCFLAGS"
+       M0_KCFLAGS="-g -O2 $M0_KCFLAGS"
        AC_DEFINE([ENABLE_DEBUG])
       ],[
        M0_CFLAGS="-g -O2 $M0_CFLAGS"
{code}

Based on the comment [here|https://gcc.gnu.org/bugzilla//show_bug.cgi?id=84187#c3], the config '-O0' seems to be invalid config for the inline-asm during kernel module compilation.

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

[PR-1438|https://github.com/Seagate/cortx-motr/pull/1438] started.

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Upendra Patwardhan
* Component Build  :  340 
* Release Build    :  868  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/centos-7.9.2009/868 
{panel}

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Fixed.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Assigning to [~535284] for further closure
