### ISSUE TITLE
libFabric issue build on Ubuntu/Debian 

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1459]
I had follow the quick start guide to build **motr** on **Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-96-generic x86_64)**

Due to default ubuntu no **libFabric** install, I need to install one ( **version 1.6.2** ).

According to doc, we should use **libFabric** with is Seagate customize build, however this is only available in **rpm**, **deb** is not available.

I try to build using **alien**, however, it is not working.

![image](https://user-images.githubusercontent.com/77140436/152729296-c49c794a-5448-48ad-8214-a46b22c80a37.png)

Should we create a **deb** version for support Ubuntu/Debain ?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28513. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by r-wambui** [comment]
@nkommuri Any updated on supporting libFabric for debian/ubuntu OS

**Comment by andriytk** [comment]
I believe Motr should work with the distribution-provided libfabric package by now. The panic issue fix was landed already at #1382.

There still might be some issues with the performance, though. For this, you can download the deb package sources, apply the changes described at https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/711230113/Libfabric+setup+and+using+libfabric+with+motr and build+install the updated deb package yourself.

cc @madhavemuri

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Resolved based on above comment assigning the same to [~930816] for further closure

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed.
