### ISSUE TITLE
system test 03console failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#1506]
----- run_st 03console -----
<< 03console >>
Running m0mkfs... OK
Service started
Console test fop, xcode input: connecting from 0@lo:12345:34:* to 0@lo:12345:34:1
connected
Console Address = 0@lo:12345:34:*
Server Address = 0@lo:12345:34:1
Sending FOP: 09 Console Test

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 22
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcd
Server replied with FOP: 08 Console Reply

        m0_cons_fop_reply
                cons_return(u32) = 0
                cons_notify_type(u32) = 9
OK
Console test fop, YAML input: connecting from 0@lo:12345:34:* to 0@lo:12345:34:1
connected
Console Address = 0@lo:12345:34:*
Server Address = 0@lo:12345:34:1

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 495
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Sending FOP: 09 Console Test

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 495
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Server replied with FOP: 08 Console Reply

        m0_cons_fop_reply
                cons_return(u32) = 0
                cons_notify_type(u32) = 9
OK
**/var/cortx/cortx-motr/console/st/console-st.sh: line 136: 23031 Killed                  $SERVER -v &>$SANDBOX_DIR/server.log**
console: test status: SUCCESS
0.39user 0.58system 0:04.97elapsed 19%CPU (0avgtext+0avgdata 306192maxresident)k
80inputs+397192outputs (10major+116289minor)pagefaults 0swaps

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29039. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mehjoshi** [comment]
Hi @yanqingfu,

Can you post some more details about your setup? Specifically, the following will be helpful:
1) Git hash of Motr code
2) OS version
3) output from df -h to verify that the system has sufficient space in all directories.
4) A log of the steps along with their output to understand it there were any failures observed at any of the steps during the setup.
5) Look into the output of journalctl for any system errors.
6) Motr UTs and STs capture traces from their execution in the test directory. You should find them under /var/motr/m0st/m0trace*. You can re-run just the single failing testcase and attach traces from it. You can run a single ST using a command like this:
${MOTR_SRC_DIR}/scripts/m0 run-st -t 03console

----- run_st -t 03console -----
<< 03console >>
Running m0mkfs... OK
Service started
Console test fop, xcode input: connecting from 0@lo:12345:34:* to 0@lo:12345:34:1
connected
Console Address = 0@lo:12345:34:*
Server Address = 0@lo:12345:34:1
Sending FOP: 09 Console Test

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 22
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Server replied with FOP: 08 Console Reply

        m0_cons_fop_reply
                cons_return(u32) = 0
                cons_notify_type(u32) = 9
OK
Console test fop, YAML input: connecting from 0@lo:12345:34:* to 0@lo:12345:34:1
connected
Console Address = 0@lo:12345:34:*
Server Address = 0@lo:12345:34:1

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 495
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Sending FOP: 09 Console Test

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 495
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Server replied with FOP: 08 Console Reply

        m0_cons_fop_reply
                cons_return(u32) = 0
                cons_notify_type(u32) = 9
OK
/root/cortx/cortx-motr/console/st/console-st.sh: line 136: 82188 Killed                  $SERVER -v &>$SANDBOX_DIR/server.log
console: test status: SUCCESS
4.18user 1.03system 0:07.64elapsed 68%CPU (0avgtext+0avgdata 342768maxresident)k
136inputs+534552outputs (11major+173282minor)pagefaults 0swaps
#

Thanks for posting!

**Comment by mehjoshi** [comment]
@yanqingfu, Looking closely at the output you pasted it looks like the same test is passing even for you.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Based on above comments, marking this issue Resolved with resolution "No Work"

**Comment by yanqingfu** [comment]
this line /root/cortx/cortx-motr/console/st/console-st.sh: line 136: 82188 Killed $SERVER -v &>$SANDBOX_DIR/server.log
if you run scripts/m0 run-st it will not proceed and will exit after 03console

**Comment by yanqingfu** [comment]
1. 7d2217c4812719ce8b8dd2216ae39ee6eea7ea7d
2. CentOS 7.9.2009 x86_64
3.  cortx-motr in var
Filesystem                                   Size  Used Avail Use% Mounted on
devtmpfs                                     3.9G     0  3.9G   0% /dev
tmpfs                                        3.9G     0  3.9G   0% /dev/shm
tmpfs                                        3.9G  876K  3.9G   1% /run
tmpfs                                        3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mapper/vg_sysvol-lv_root                 20G  3.1G   16G  17% /
/dev/sda1                                    976M  120M  790M  14% /boot
/dev/mapper/vg_sysvol-lv_tmp                 9.8G   38M  9.2G   1% /tmp
/dev/mapper/vg_sysvol-lv_var                 217G   15G  193G   8% /var
/dev/mapper/vg_sysvol-lv_log                 7.8G   87M  7.3G   2% /var/log
/dev/mapper/vg_sysvol-lv_audit               240M  3.9M  220M   2% /var/log/audit
tmpfs                                        782M     0  782M   0% /run/user/670951
ssc-nfs-home1.colo.seagate.com:/home/670951  2.5T  744G  1.8T  30% /home/670951
4. I didn't see any failure during the setup while following the guide

**Comment by cortx-admin** [comment]
> Mehul Manharlal Joshi commented in Jira Server:

run-st exits after it encounters the first skipped test.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Adding in Sprint65 for fixing the same

**Comment by cortx-admin** [comment]
> Mehul Manharlal Joshi commented in Jira Server:

Following is the link to the PR:
https://github.com/Seagate/cortx-motr/pull/1543

**Comment by cortx-admin** [comment]
> Mehul Manharlal Joshi commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Mehul Manharlal Joshi commented in Jira Server:

.
