### ISSUE TITLE
system test 07m0d-fatal failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#1507]
----- run_st -t 07m0d-fatal -----
<< 07m0d-fatal >>
Test environment start
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00150394 s, 697 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00174161 s, 602 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00149111 s, 703 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00171744 s, 611 MB/s
Main m0d start
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -D /var/motr/root/sandbox.st-07m0d-fatal/confd/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/confd/addb-stobs -e libfab:192.168.59.161@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-07m0d-fatal/confd/conf.txt -w 3 -f <0x7200000000000001:0> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -j
/var/cortx/cortx-motr/motr/m0d -F -D /var/motr/root/sandbox.st-07m0d-fatal/confd/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/confd/addb-stobs -e libfab:192.168.59.161@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-07m0d-fatal/confd/conf.txt -w 3 -f <0x7200000000000001:0> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -j
main pid=23460
Sample m0d start
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -D /var/motr/root/sandbox.st-07m0d-fatal/systest-23313/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/systest-23313/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/systest-23313/addb-stobs -e libfab:192.168.59.161@tcp:12345:34:1002 -m 163840 -q 2 -w 3 -f <0x7200000000000001:1> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -H 192.168.59.161@tcp:12345:34:1001
/var/cortx/cortx-motr/motr/m0d -D /var/motr/root/sandbox.st-07m0d-fatal/systest-23313/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/systest-23313/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/systest-23313/addb-stobs -e libfab:192.168.59.161@tcp:12345:34:1002 -m 163840 -q 2 -w 3 -f <0x7200000000000001:1> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -H 192.168.59.161@tcp:12345:34:1001
sample pid=23614
m0d running: 23460 23614
Command to inject a single-time fault on main m0d side
connecting from 192.168.59.161@tcp:12345:34:2001 to 192.168.59.161@tcp:12345:34:1001
connected
Console Address = 192.168.59.161@tcp:12345:34:2001
Server Address = 192.168.59.161@tcp:12345:34:1001
Sending FOP: 260 Fault Injection Command

        m0_fi_command_req
                m0_buf
                        b_nob(u64) = 30
                        b_addr(u8) = motr_ha_entrypoint_rep_rm_fill
                m0_buf
                        b_nob(u64) = 10
                        b_addr(u8) = no_rms_fid⚌⚌
                fcr_disp(u8) =
                fcr_num1(u32) = 0
                fcr_num2(u32) = 0
Server replied with FOP: 261 Fault Injection Command reply

        m0_fi_command_rep
                fcp_rc(u32) = 0
Obtain write lock on the cluster
s 192.168.59.161@tcp:12345:34:1001, c 192.168.59.161@tcp:12345:34:2001, d 5
Got write lock
Released write lock
m0d running: 23460 23614
(23460) pids list is expected
Stop (1)
m0d-fatal test FAILED: 1
1.14user 1.06system 0:42.76elapsed 5%CPU (0avgtext+0avgdata 300392maxresident)k
160inputs+754328outputs (16major+192527minor)pagefaults 0swaps

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29040. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mehjoshi** [comment]
Hi @yanqingfu,

I tried the same test on CentOS 7.9 with latest Motr code checked out afresh.
I do not see any failures. Here is the output:

# ./scripts/m0 run-st -t 07m0d-fatal
----- run_st -t 07m0d-fatal -----
<< 07m0d-fatal >>
Test environment start
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00254948 s, 411 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00198086 s, 529 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00212732 s, 493 MB/s
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00147702 s, 710 MB/s
Main m0d start
/root/cortx/cortx-motr/utils/mkfs/m0mkfs -F -D /var/motr/root/sandbox.st-07m0d-fatal/confd/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/confd/addb-stobs -e libfab:192.168.51.42@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-07m0d-fatal/confd/conf.txt -w 3 -f <0x7200000000000001:0> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -j
/root/cortx/cortx-motr/motr/m0d -F -D /var/motr/root/sandbox.st-07m0d-fatal/confd/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/confd/addb-stobs -e libfab:192.168.51.42@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-07m0d-fatal/confd/conf.txt -w 3 -f <0x7200000000000001:0> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -j
main pid=82824
Sample m0d start
/root/cortx/cortx-motr/utils/mkfs/m0mkfs -D /var/motr/root/sandbox.st-07m0d-fatal/systest-82643/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/systest-82643/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/systest-82643/addb-stobs -e libfab:192.168.51.42@tcp:12345:34:1002 -m 163840 -q 2 -w 3 -f <0x7200000000000001:1> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -H 192.168.51.42@tcp:12345:34:1001
/root/cortx/cortx-motr/motr/m0d -D /var/motr/root/sandbox.st-07m0d-fatal/systest-82643/db -T AD -S /var/motr/root/sandbox.st-07m0d-fatal/systest-82643/stobs -A linuxstob:/var/motr/root/sandbox.st-07m0d-fatal/systest-82643/addb-stobs -e libfab:192.168.51.42@tcp:12345:34:1002 -m 163840 -q 2 -w 3 -f <0x7200000000000001:1> -d /var/motr/root/sandbox.st-07m0d-fatal/confd/disks.conf -H 192.168.51.42@tcp:12345:34:1001
sample pid=83002
m0d running: 82824 83002
Command to inject a single-time fault on main m0d side
connecting from 192.168.51.42@tcp:12345:34:2001 to 192.168.51.42@tcp:12345:34:1001
connected
Console Address = 192.168.51.42@tcp:12345:34:2001
Server Address = 192.168.51.42@tcp:12345:34:1001
Sending FOP: 260 Fault Injection Command

        m0_fi_command_req
                m0_buf
                        b_nob(u64) = 30
                        b_addr(u8) = motr_ha_entrypoint_rep_rm_fill__________!
                m0_buf
                        b_nob(u64) = 10
                        b_addr(u8) = no_rms_fid
                fcr_disp(u8) =
                fcr_num1(u32) = 0
                fcr_num2(u32) = 0
Server replied with FOP: 261 Fault Injection Command reply

        m0_fi_command_rep
                fcp_rc(u32) = 0
Obtain write lock on the cluster
s 192.168.51.42@tcp:12345:34:1001, c 192.168.51.42@tcp:12345:34:2001, d 5
Got write lock
Released write lock
m0d running: 82824
Stop (0)
m0d-fatal: test status: SUCCESS
15.79user 2.52system 0:54.34elapsed 33%CPU (0avgtext+0avgdata 376104maxresident)k
264inputs+956160outputs (17major+428873minor)pagefaults 0swaps

Thanks!

**Comment by yanqingfu** [comment]
1. 7d2217c4812719ce8b8dd2216ae39ee6eea7ea7d
2. CentOS 7.9.2009 x86_64
3.  cortx-motr in var
Filesystem                                   Size  Used Avail Use% Mounted on
devtmpfs                                     3.9G     0  3.9G   0% /dev
tmpfs                                        3.9G     0  3.9G   0% /dev/shm
tmpfs                                        3.9G  876K  3.9G   1% /run
tmpfs                                        3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mapper/vg_sysvol-lv_root                 20G  3.1G   16G  17% /
/dev/sda1                                    976M  120M  790M  14% /boot
/dev/mapper/vg_sysvol-lv_tmp                 9.8G   38M  9.2G   1% /tmp
/dev/mapper/vg_sysvol-lv_var                 217G   15G  193G   8% /var
/dev/mapper/vg_sysvol-lv_log                 7.8G   87M  7.3G   2% /var/log
/dev/mapper/vg_sysvol-lv_audit               240M  3.9M  220M   2% /var/log/audit
tmpfs                                        782M     0  782M   0% /run/user/670951
ssc-nfs-home1.colo.seagate.com:/home/670951  2.5T  744G  1.8T  30% /home/670951
4. I didn't see any failure during the setup while following the guide

**Comment by yanqingfu** [comment]
restarted machine and run again, still has the error

**Comment by yanqingfu** [comment]
after comparing your log, my m0d running has two ids
Got write lock
Released write lock
**m0d running: 23460 23614**
yours has one
Got write lock
Released write lock
**m0d running: 82824**

**Comment by nkommuri** [comment]
@yanqingfu , can you please check if any m0d is running before starting the ST. Thanks.

**Comment by yanqingfu** [comment]
how to check?

**Comment by chandradharraval** [comment]
Hi @yanqingfu ,
Simple "ps -aux" command should help here

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue closed based on above comments
