### ISSUE TITLE
Script for stop standalone motr in "motr/examples"

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1513]
When a connection lost after start motr standalone server from `motr/examples/setup_a_running_motr_system.sh`, that is not way to stop the server unless kill the process via `kill -9 pid1 pid2 ..`

The issue is that is too many pid to manually copy and paste, and seem like directory `/var/motr` is not clean up ( until we get out of disk space error when motr no longer could start, perhaps we could put this information in documentation also )

Could we have a script to stop motr and clean up `/var/motr` directotry if the connection accidentally terminate and no longer could  `EXIT` motr server?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29132. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by r-wambui** [comment]
@kiwionly2 I have requested @rkothiya to look into this and assist.

**Comment by kiwionly2** [comment]
@huanghua78 yes, I ssh to a remote server and client for testing ( since I only have a remote server that running linux), so I get this issue when connection lost.

I will try `screen `command and see how the thing run.

**Comment by chandradharraval** [comment]
Hi @kiwionly2 ,
Were you able to confirm the same based on your above comments? If yes can we close this ticket?

**Comment by kiwionly2** [comment]
Since I have a solution for this, yup, I think we could close it now.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue closed based on above comments
