### ISSUE TITLE
High level go client for motr

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1523]
Hi all, 

I had created a high level go client for motr. ( which is a wrapper based on existing go binding)

With this Client , you could easily create a motr client in go code :
```
client, err = NewClient(&Options{
		HAAddr:     "192.168.63.52@tcp:12345:34:1",
		LocalAddr:  "192.168.63.52@tcp:12345:33:1000",
		Profile:    "0x7000000000000001:0",
		ProcessFId: "0x7200000000000001:64",
		TraceOn:    false,
	})

ctx := context.Background()
err := client.Create(ctx, indexId)
err = client.put(ctx, indexId, "k1", "v1", "k2", "v2", "k3", "v3", "k4", "v4")
```

You could checkout this [branch](https://github.com/kiwionly2/cortx-motr/tree/high_level_go_client) to give it a try.

See [README.md](https://github.com/kiwionly2/cortx-motr/tree/go_motr/bindings/go/client) for instruction of how to run the tests.

*Note that that is something to aware of :
1. You can't create a new client under same process PID and same client Id (LocalAddr), you need to use a new LocalAddr e.g. `192.168.63.52@tcp:12345:33:1001` as a new client id, and run the new client under new OS process. e.g. run another instance.
2. Due to `struct m0_container` not work well with `cgo`, `struct m0_container` is not encapsulate in `type Client struct` but use global variable ` struct m0_container` instead, currently it still work because of note 1 above.
3. All Operations first parameter is `context.Context`, but currently it is not use, it might be use in future. 

Any feedback is welcome :)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29198. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by kiwionly2** [comment]
@andriytk

**Comment by johnbent** [comment]
@kiwionly2 , very cool! This seems like you should make a pull request. But, before you do, is your README.md linked from another existing page in cortx-motr?

**Comment by kiwionly2** [comment]
@johnbent , the readme is from my branch ( since i not sure is this will go for PR )  maybe the title is a bit confusing, I will change that later.

**Comment by johnbent** [comment]
@andriytk , have you had a chance to look at this yet? Where should this go?

**Comment by andriytk** [comment]
Is there a PR for this? Maybe we can use it as another example of go/mio KV API usage at `bindings/go/`?

**Comment by kiwionly2** [comment]
@andriytk I had create a PR #1536 for this.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Closing this issue and corresponding Github is closed
