### ISSUE TITLE
We may need to find a place holder to collect all this details in one location.

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1570]
We may need to find a place holder to collect all this details in one location.

_Originally posted by @yeshpal-jain-seagate in https://github.com/Seagate/cortx-rgw/pull/144#discussion_r837088887_

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~934754],
Where can we document this?

**Comment by cortx-admin** [comment]
> Swapnil Chaudhary commented in Jira Server:

Below details are available in motr/client.h file wrt to M0_ENF_META flag.
{noformat}
 enum m0_entity_flags {
	/**
	 * If motr client application has the capability to store object
	 * metadata by itself (such as pool version and layout, which can
	 * be stored by the application at motr distributed index, for example),
	 * it can use this flag to avoid sending additional metadata fops on
	 * such object operations as CREATE, OPEN, DELETE, GETATTR and, thus,
	 * improve its performance.
	 *
	 * Before calling m0_entity_create() or m0_entity_open(), application
	 * is expected to set obj->ob_entity->en_flags |= M0_ENF_META. When
	 * m0_entity_create() returns, the pool version and layout id will be
	 * available for the application at obj->ob_attr.oa_pver and
	 * obj->ob_attr.oa_lid respectively.
	 *
	 * For example, create workflow can look like this:
	 *
	 *   obj->ob_entity.en_flags |= M0_ENF_META;
	 *   m0_entity_create(NULL, &obj->ob_entity, &ops[0]);
	 *   // Save the returned pool version and lid into app_meta_data
	 *   app_meta_data.pver = obj->ob_attr.oa_pver;
	 *   app_meta_data.lid  = obj->ob_attr.oa_lid;
	 *
	 * And read workflow:
	 *
	 *   obj->ob_entity.en_flags |= M0_ENF_META;
	 *   // Set the pool version and lid from app_meta_data
	 *   obj->ob_attr.oa_pver = app_meta_data.pver;
	 *   obj->ob_attr.oa_lid  = app_meta_data.lid;
	 *   m0_entity_open(NULL, &obj->ob_entity, &ops[0]);
	 */
	M0_ENF_META = 1 << 0,
	/**
	 * If this flags is set during entity_create() that means application
	 * do not support update operation.
	 * XXX: This flag is not in use and will be deleted soon, so please
	 *      remove it from your code. If you need to avoid RMW when writing
	 *      the non-full last parity group, use M0_OOF_LAST flag instead.
	 */
{noformat}

Do we need to add any additional information ?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
