### ISSUE TITLE
Failure to Build Motr (continuation of past issue)

### ISSUE THREAD

**Issue by rajrana22** [Seagate/cortx-motr#1581]
Hi all, sorry for not replying earlier. For some reason, Github wasn't sending me notifications of this issue thread.
I tried building again using CentOS 8.3 on Chameleon, but when trying to run `./configure`, I'm getting the following issue:
```
configure: INTEL ISA-L Headers Available
checking rdma/fabric.h usability... no
checking rdma/fabric.h presence... no
checking for rdma/fabric.h... no
checking for motr/config.h... configure: motr/config.h not found! Creating the symlink.
ln: failed to create symbolic link 'config.h': File exists
checking for LNet header dir... configure: error: lnet/include not found in '', please provide a         correct path to Lustre headers using --with-lustre option
```
For context, I'm trying to use LNET.

Not sure if this is related, but when I run `sudo ./scripts/install-build-deps`, I get the following message:
```
ERROR! couldn't resolve module/action 'authorized_key'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/cc/cortx-motr/scripts/provisioning/roles/ssh-jumphost/tasks/main.yml': line 37, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# on the same host
- name: enable SSH self-login with the public key
  ^ here
```

_Originally posted by @rajrana22 in https://github.com/Seagate/cortx-motr/issues/1384#issuecomment-1059903316_

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29960. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Jugal Patil commented in Jira Server:

install-build-deps is failing with following error
{code:java}
ERROR! couldn't resolve module/action 'authorized_key'. This often indicates a misspelling, missing collection, or incorrect module path.The error appears to be in '/home/cc/cortx-motr/scripts/provisioning/roles/ssh-jumphost/tasks/main.yml': line 37, column 3, but may
be elsewhere in the file depending on the exact syntax problem.{code}

cortx-motr supports ansible 2.9 but the setup from which issue is reported is using ansible 2.10
reverting to ansible 2.9 will solve this build issue. 

reference :- [ansible 2.10 fails to parse existing playbook · Issue #104295 · NixOS/nixpkgs (github.com)|https://github.com/NixOS/nixpkgs/issues/104295]

**Comment by nkommuri** [comment]
Closing issue as per above comment. Please revert ansible version and check. Please reopen if the issue persist even after that. Thanks.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed based on above comments

**Comment by mermellla** [comment]
still seeing this issue with 2.9
