### ISSUE TITLE
https://github.com/Seagate/cortx/blob/main/doc/be/CORTX_CORE_ARCHITECTURE.rst

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#16]
@nikitadanilov should this file (https://github.com/Seagate/cortx/blob/main/doc/be/CORTX_CORE_ARCHITECTURE.rst) be moved from the 'cortx' parent repo to the 'cortx-motr' repo?  What do you think?

**Comment by nikitadanilov** [comment]
Wow, this did fall between the cracks, sorry. Yes, let's move this to cortx-motr.

**Comment by huanghua78** [comment]
I will take care of this.

**Comment by huanghua78** [comment]
This is fixed in 0f2a9ab1
