### ISSUE TITLE
REGRESSION: used data is freed at dix_cas_rops_send() causing memory corruption

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1601]
https://github.com/Seagate/cortx-motr/blob/2d8a769326a8c07f4827ffee97615946895f6ad7/dix/req.c#L1802

This frees used data: m0_cas_get()->m0_cas__get()->cas_req_prep()->cas_records_op_prepare() copies cas_id:

op->cg_id = *index;

This means that extent op->cg_id.ci.layout.dl_desc.ld_imask.im_range is shared between op->cg_id and cctg_id. m0_cas_id_fini() frees the extent, so garbage is written in fop and sent to the server.

Please revert.

_Originally posted by @nikitadanilov in https://github.com/Seagate/cortx-motr/pull/1568#discussion_r846403240_

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30728. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by andriytk** [comment]
@nikitadanilov, but where should it be freed then - `ld_imask.im_range`?

**Comment by nikitadanilov** [comment]
> @nikitadanilov, but where should it be freed then - `ld_imask.im_range`?

I don't know, sorry.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Assigning to [~520414] for further actions

**Comment by cortx-admin** [comment]
> Trupti Patil commented in Jira Server:

Have requested help from [~535284] on this issue, he being the index path expert.

**Comment by andriytk** [comment]
Will be fixed by https://github.com/Seagate/cortx-motr/pull/1628.

**Comment by cortx-admin** [comment]
> Sergey Shilov commented in Jira Server:

https://github.com/Seagate/cortx-motr/pull/1628

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Sergey Shilov
* Component Build  :  5073 
* Release Build    :  5311  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5311 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5311
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5311
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5311
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5311 
{panel}

**Comment by cortx-admin** [comment]
> Sergey Shilov commented in Jira Server:

Merged
https://github.com/Seagate/cortx-motr/pull/1628

**Comment by cortx-admin** [comment]
> Sergey Shilov commented in Jira Server:

Now CAS/DIX/Client tests pass.
