### ISSUE TITLE
[Codacy code cleanup] occurrence: 748 pattern: The scope of the variable 'varname' can be reduced

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1607]
### Problem

We see 748 occurrence of pattern, "The scope of the variable 'varname' can be reduced".

### Expected behavior

We should not be getting these warnings

### How to reproduce

Not Applicable

### Deployment information

Static code analysis warnings.

**Comment by rkothiya** [comment]
This issue is no longer seen, need to check if this was marked to be ignored and why.

**Comment by rkothiya** [comment]
@anaghadeshmukh marked this to be ignored as discussed in the meeting.

**Comment by cortx-admin** [comment]
> Anagha Deshmukh commented in Jira Server:

Closing the issue as identified as false positive

**Comment by cortx-admin** [comment]
> Anagha Deshmukh commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Anagha Deshmukh commented in Jira Server:

.
