### ISSUE TITLE
[Codacy code cleanup] occurrence: 369 pattern: Use`$(...)` notation instead of legacy backticked ```...```.

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1608]
### Problem

We see 369 occurrence of pattern, "Use`$(...)` notation instead of legacy backticked ```...```.".

### Expected behavior

We should not be getting these warnings 

### How to reproduce

Fire the below command to list all the warnings : 

`# shellcheck   -x  <file name>`

### Deployment information

Install the shellcheck package. For example to install it on Fedora/RHEL/centos you can fire : 

` # yum -y install ShellCheck`

### Additional information

Following files contains this warnings:

./addb2/st/addb2dump-plugin.sh
./console/st/console-st.sh
./dix/cm/st/m0t1fs_dix_repair.sh
./fdmi/st/echo/echo_plugin_start.sh
./fdmi/st/fdmi_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_cc_io_with_sns_repair.sh
./m0t1fs/linux_kernel/st/m0t1fs_client.sh
./m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh
./m0t1fs/linux_kernel/st/m0t1fs_failure_after_sns_repair_quiesce.sh
./m0t1fs/linux_kernel/st/m0t1fs_fsync_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_fwait_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_multi_clients.sh
./m0t1fs/linux_kernel/st/m0t1fs_pool_version_assignment.sh
./m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh
./m0t1fs/linux_kernel/st/m0t1fs_rconfc_fail_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_restart_motr_service.sh
./m0t1fs/linux_kernel/st/m0t1fs_rlock_revoke.sh
./m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_server.sh
./m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1k_1f.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1n_1f.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort_quiesce.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_ios_fail.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_mf.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_quiesce.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_shutdown.sh
./m0t1fs/linux_kernel/st/m0t1fs_spare_space_reserve.sh
./m0t1fs/linux_kernel/st/m0t1fs_test.sh
./motr/devices.sh
./motr/st/utils/m0crate_iem_freespace_st.sh
./motr/st/utils/m0crate_st.sh
./motr/st/utils/m0kv_start.sh
./motr/st/utils/motr_client_st.sh
./motr/st/utils/motr_cmd.sh
./motr/st/utils/motr_conf_update_st.sh
./motr/st/utils/motr_device_util.sh
./motr/st/utils/motr_dgmode_io_st.sh
./motr/st/utils/motr_fs.sh
./motr/st/utils/motr_raid0_st.sh
./motr/st/utils/motr_rm_lock_cc_io.sh
./motr/st/utils/motr_rmw_st.sh
./motr/st/utils/motr_rpc_cancel_test.sh
./motr/st/utils/motr_services.sh
./motr/st/utils/motr_sns_common.sh
./motr/st/utils/motr_st_inc.sh
./motr/st/utils/motr_sync_replication_st.sh
./motr/st/utils/motr_sys_test.sh
./motr/st/utils/motr_utils_st.sh
./motr/st/utils/sns_repair_motr_1f.sh
./motr/st/utils/sns_repair_motr_1k_1f.sh
./motr/st/utils/sns_repair_motr_1n_1f.sh
./motr/st/utils/sns_repair_motr_abort.sh
./motr/st/utils/sns_repair_motr_abort_quiesce.sh
./motr/st/utils/sns_repair_motr_ios_fail.sh
./motr/st/utils/sns_repair_motr_mf.sh
./net/lnet/st/linux_kernel/m0lnetping.sh
./rpc/ub/plot.sh
./scripts/addb-py/chronometry/restart_ios.sh
./scripts/addb-py/chronometry/s3_build_fix/rebuildall.sh
./scripts/demo/2015-10-dev2.sh
./scripts/install/opt/seagate/cortx/motr/common/cortx_util_funcs.sh
./scripts/install/opt/seagate/cortx/motr/common/m0_sns_utils_common.sh
./scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh
./scripts/install/opt/seagate/cortx/motr/libexec/m0trace_logrotate.sh
./scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
./scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
./scripts/install/opt/seagate/cortx/motr/sanity/cortx_lnet_sanity.sh
./scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
./scripts/provisioning/vmhost/gci-create-cluster.sh
./scripts/provisioning/vmhost/prepare-host.sh
./scripts/provisioning/vmhost/super-cleanup.sh
./scripts/systemtap/kem/st/st.sh
./scripts/addb-py/chronometry/task_queue/st.sh
./rpc/it/st.sh
./net/test/st/st.sh
./be/tool/st.sh
./sns/cm/st/repair_test.sh
./spiel/st/m0t1fs_spiel_dix_repair.sh
./spiel/st/m0t1fs_spiel_dix_repair_quiesce.sh
./spiel/st/m0t1fs_spiel_sns_common_inc.sh
./spiel/st/m0t1fs_spiel_sns_repair.sh
./spiel/st/m0t1fs_spiel_sns_repair_quiesce.sh
./spiel/st/m0t1fs_spiel_st.sh
./spiel/st/spiel_multiple_confd.sh
./st/m0d-device-detach-test.sh
./st/m0d-fsync-test.sh
./st/m0d-signal-test.sh
./st/m0t1fs-buffsize-layout-change-test.sh
./st/sanity.sh
./st/stob_domain_recreate_on_corruption.sh

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30753. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by alfhad** [comment]
Following PR addresses this issue:
https://github.com/Seagate/cortx-motr/pull/1843

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed and corresponding PR https://github.com/Seagate/cortx-motr/pull/1843 is merged

**Comment by alfhad** [comment]
This issue is not completely resolved as I will be creating several patches, convenient for testing and merging the same.

**Comment by alfhad** [comment]
Following PR is patch 2 for this issue:
https://github.com/Seagate/cortx-motr/pull/1850

**Comment by alfhad** [comment]
Another patch addressing this issue:
https://github.com/Seagate/cortx-motr/pull/1857

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: fahadshah2411
* Component Build  :  5327 
* Release Build    :  5971  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5971 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5971
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5971
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5971
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5971 
{panel}

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: fahadshah2411
* Component Build  :  5359 
* Release Build    :  6031  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/6031 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-6031
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6031
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6031
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6031 
{panel}
