### ISSUE TITLE
[Codacy code cleanup] occurrence: 251 pattern: foo appears unused. Verify it or export it

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1609]
### Problem

We see 251 occurrence of pattern, "foo appears unused. Verify it or export it".

### Expected behavior

We should not be getting these warnings 

### How to reproduce

Fire the below command to list all the warnings : 

`# shellcheck   -x  <file name>`

example :

In ./cortx-motr/console/st/console-st.sh line 45:
NODE_UUID=02e94b88-19ab-4166-b26b-91b51f22ad91  # required by `common.sh'
^-------^ SC2034: **NODE_UUID appears unused. Verify use (or export if used externally)**.

### Deployment information

Install the shellcheck package. For example to install it on Fedora/RHEL/centos you can fire : 

` # yum -y install ShellCheck`

### Additional information

Following files contains this warnings 

./console/st/console-st.sh
./dix/cm/st/m0t1fs_dix_repair.sh
./dix/cm/st/m0t1fs_dix_repair_quiesce.sh
./fdmi/st/fdmi_test.sh
./m0t1fs/linux_kernel/st/common_service_fids_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_cc_io_with_sns_repair.sh
./m0t1fs/linux_kernel/st/m0t1fs_client.sh
./m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh
./m0t1fs/linux_kernel/st/m0t1fs_failure_after_sns_repair_quiesce.sh
./m0t1fs/linux_kernel/st/m0t1fs_fsync_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_fwait_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_io_config_params.sh
./m0t1fs/linux_kernel/st/m0t1fs_multi_clients.sh
./m0t1fs/linux_kernel/st/m0t1fs_pool_version_assignment.sh
./m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh
./m0t1fs/linux_kernel/st/m0t1fs_rconfc_fail_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_restart_motr_service.sh
./m0t1fs/linux_kernel/st/m0t1fs_rlock_revoke.sh
./m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1k_1f.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1n_1f.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort_quiesce.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_ios_fail.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_mf.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_quiesce.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_shutdown.sh
./m0t1fs/linux_kernel/st/m0t1fs_spare_space_reserve.sh
./m0t1fs/linux_kernel/st/m0t1fs_test.sh
./motr/st/utils/m0crate_iem_freespace_st.sh
./motr/st/utils/m0crate_st.sh
./motr/st/utils/motr_client_st.sh
./motr/st/utils/motr_conf_update_st.sh
./motr/st/utils/motr_device_util.sh
./motr/st/utils/motr_dgmode_io_st.sh
./motr/st/utils/motr_fs.sh
./motr/st/utils/motr_local_conf.sh
./motr/st/utils/motr_raid0_st.sh
./motr/st/utils/motr_remote_conf.sh
./motr/st/utils/motr_rm_lock_cc_io.sh
./motr/st/utils/motr_rmw_st.sh
./motr/st/utils/motr_rpc_cancel_test.sh
./motr/st/utils/motr_sns_common.sh
./motr/st/utils/motr_st_inc.sh
./motr/st/utils/motr_sync_replication_st.sh
./motr/st/utils/motr_sys_test.sh
./motr/st/utils/motr_utils_st.sh
./motr/st/utils/sns_failure_after_repair_quiesce.sh
./motr/st/utils/sns_repair_motr_1f.sh
./motr/st/utils/sns_repair_motr_1k_1f.sh
./motr/st/utils/sns_repair_motr_1n_1f.sh
./motr/st/utils/sns_repair_motr_abort.sh
./motr/st/utils/sns_repair_motr_abort_quiesce.sh
./motr/st/utils/sns_repair_motr_ios_fail.sh
./motr/st/utils/sns_repair_motr_mf.sh
./motr/st/utils/sns_repair_motr_quiesce.sh
./motr/st/utils/sns_repair_motr_shutdown.sh
./motr/st/utils/spiel_sns_motr_repair.sh
./motr/st/utils/spiel_sns_motr_repair_quiesce.sh
./net/lnet/st/linux_kernel/m0lnetping.sh
./net/test/demo/demo.sh
./net/test/st/run-1x1.sh
./net/test/st/st-bulk.sh
./net/test/st/st-ping.sh
./net/test/test.sh
./net/test/demo/test.sh
./rpc/it/linux_kernel/rpcload.sh
./scripts/addb-py/chronometry/s3_build_fix/rebuildall.sh
./scripts/demo/2015-10-dev2.sh
./scripts/install/opt/seagate/cortx/motr/common/cortx_error_codes.sh
./scripts/install/opt/seagate/cortx/motr/common/m0_sns_utils_common.sh
./scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
./scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
./scripts/provisioning/vmhost/create-cluster.sh
./scripts/provisioning/vmhost/gci-create-cluster.sh
./scripts/provisioning/vmhost/gci-start-cluster.sh
./scripts/systemtap/kem/st/st.sh
./scripts/addb-py/chronometry/task_queue/st.sh
./rpc/it/st.sh
./net/test/st/st.sh
./be/tool/st.sh
./sns/cm/st/repair_test.sh
./spiel/st/m0t1fs_spiel_dix_common_inc.sh
./spiel/st/m0t1fs_spiel_dix_repair.sh
./spiel/st/m0t1fs_spiel_dix_repair_quiesce.sh
./spiel/st/m0t1fs_spiel_sns_common_inc.sh
./spiel/st/m0t1fs_spiel_sns_repair.sh
./spiel/st/m0t1fs_spiel_sns_repair_quiesce.sh
./spiel/st/spiel_multiple_confd.sh

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30754. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
