### ISSUE TITLE
[Codacy code cleanup] occurrence: 121 pattern: $/${} Is unnecessary on arithmetic variable

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1610]
### Problem

We see 121 occurrence of pattern, "121 pattern: $/${} Is unnecessary on arithmetic variable".

### Expected behavior

We should not be getting these warnings 

### How to reproduce

Fire the below command to list all the warnings : 

`# shellcheck   -x  <file name>`

### Deployment information

Install the shellcheck package. For example to install it on Fedora/RHEL/centos you can fire : 

` # yum -y install ShellCheck`

### Additional information

Following files contains this warnings 

./cas/st/ctgdump_tesh.sh
./fdmi/st/fdmi_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_cc_io_with_sns_repair.sh
./m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh
./m0t1fs/linux_kernel/st/m0t1fs_io_config_params.sh
./m0t1fs/linux_kernel/st/m0t1fs_rconfc_fail_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_sns_repair_mf.sh
./motr/st/utils/motr_rm_lock_cc_io.sh
./motr/st/utils/motr_utils_st.sh
./motr/st/utils/sns_repair_common_inc.sh
./scripts/install/opt/seagate/cortx/motr/common/cortx_error_codes.sh
./scripts/install/opt/seagate/cortx/motr/common/m0_sns_utils_common.sh
./scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh
./scripts/provisioning/vmhost/create-cluster.sh
./scripts/provisioning/vmhost/destroy-cluster.sh
./scripts/provisioning/vmhost/gci-create-cluster.sh

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30755. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by alfhad** [comment]
The following pull request should address the issue:
https://github.com/Seagate/cortx-motr/pull/1638/files

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Fired the following job to test this : 
[https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1136/]

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

!image-2022-04-18-12-33-25-056.png!

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The test result's screen shot is shared above. There were only 2 test which failed :

      00userspace-tests
      52motr-singlenode-sanity

Both the above tests do not seem to be related to the current patch. 

I have attached the stderr.log of both the test failures to this ticket.

**Comment by johnbent** [comment]
@rkothiya , the test result screen shot isn't making it to github. Can you paste it here please?
https://github.com/Seagate/cortx-motr/issues/1610

**Comment by rkothiya** [comment]
Hey @johnbent , sorry for the late response. For the other valid issue I will keep that in mind to put the screenshot in the github issue as well. Since it was decided in the pull request that this issue needs to be ignored. I have disabled this pattern in Codacy and closing this issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking Jira Closed and corresponding Github issue is Closed now
