### ISSUE TITLE
[Codacy code cleanup] occurrence: 52 pattern: Expr is antiquated. Consider rewriting the this using $((..)), ${} or __[[_ _]]__

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1612]
### Problem

We see 52 occurrence of pattern, "Expr is antiquated. Consider rewriting the this using $((..)), ${} or __[[_ _]]__".

### Expected behavior

We should not be getting these warnings 

### How to reproduce

Fire the below command to list all the warnings : 

`# shellcheck   -x  <file name>`

### Deployment information

Install the shellcheck package. For example to install it on Fedora/RHEL/centos you can fire : 

` # yum -y install ShellCheck`

### Additional information

Following files contains this warnings

./m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
./m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh
./m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh
./m0t1fs/linux_kernel/st/m0t1fs_spare_space_reserve.sh
./motr/devices.sh
./motr/st/utils/m0crate_iem_freespace_st.sh
./motr/st/utils/m0crate_st.sh
./motr/st/utils/motr_conf_update_st.sh
./motr/st/utils/motr_dgmode_io_st.sh
./motr/st/utils/motr_sns_common.sh
./motr/st/utils/motr_st_inc.sh
./motr/st/utils/motr_sync_replication_st.sh
./motr/st/utils/motr_utils_st.sh
./net/test/demo/demo-test-run.sh
./net/test/demo/demo.sh
./net/test/st/run-1x1.sh
./scripts/demo/2015-10-dev2.sh
./scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh
./scripts/install/opt/seagate/cortx/motr/libexec/m0trace_logrotate.sh

**Comment by alfhad** [comment]
I will take this up

**Comment by alfhad** [comment]
The following pull request should address the issue: 
https://github.com/Seagate/cortx-motr/pull/1629/

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

I have fired the below test for the same : 
[https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1143/]

**Comment by rkothiya** [comment]
The following error related to the pr was detected which will need to be fixed before merging : 

```
<< 43m0crate >>
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../../m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 109: 4 \* 5: syntax error: invalid arithmetic operator (error token is "\* 5")
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../../m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 113: 1024 \* 1024: syntax error: invalid arithmetic operator (error token is "\* 1024")
/root/motr/motr_test_github_workdir/workdir/src/m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 109: 4 \* 5: syntax error: invalid arithmetic operator (error token is "\* 5")
/root/motr/motr_test_github_workdir/workdir/src/m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 113: 1024 \* 1024: syntax error: invalid arithmetic operator (error token is "\* 1024")
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../../m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh: line 260: / 4: syntax error: operand expected (error token is "/ 4")
m0crate: FAILURE 1
0.13user 0.18system 0:05.28elapsed 5%CPU (0avgtext+0avgdata 4720maxresident)k
32inputs+88outputs (0major+45376minor)pagefaults 0swaps
```

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The following error related to the pr was detected which will need to be fixed before merging : 
{code:java}
<< 43m0crate >>
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../../m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 109: 4 \* 5: syntax error: invalid arithmetic operator (error token is "\* 5")
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../../m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 113: 1024 \* 1024: syntax error: invalid arithmetic operator (error token is "\* 1024")
/root/motr/motr_test_github_workdir/workdir/src/m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 109: 4 \* 5: syntax error: invalid arithmetic operator (error token is "\* 5")
/root/motr/motr_test_github_workdir/workdir/src/m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh: line 113: 1024 \* 1024: syntax error: invalid arithmetic operator (error token is "\* 1024")
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../../m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh: line 260: / 4: syntax error: operand expected (error token is "/ 4")
m0crate: FAILURE 1
0.13user 0.18system 0:05.28elapsed 5%CPU (0avgtext+0avgdata 4720maxresident)k
32inputs+88outputs (0major+45376minor)pagefaults 0swaps
{code}

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

As the pr was updated to address the above error, I have fired the test again to check for regression : 
[https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1149/]

**Comment by rkothiya** [comment]
The updated pr did solve the previous errors. But there is one last error which needs to be solved. 
The following error related to the pr was detected which will need to be fixed before merging : 
```
----- run_st 41motr-conf-update -----
<< 41motr-conf-update >>
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/motr_conf_update_st.sh: line 49: syntax error near unexpected token `)'
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/motr_conf_update_st.sh: line 49: `?local ios_index=$($i + 1))'
0.09user 0.15system 0:00.27elapsed 90%CPU (0avgtext+0avgdata 4712maxresident)k
224inputs+0outputs (0major+26041minor)pagefaults 0swaps
```

**Comment by alfhad** [comment]
I have updated the patch to solve this error.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed as the same is addressed via PR [https://github.com/Seagate/cortx-motr/pull/1629/] and it is merged
