### ISSUE TITLE
[Codacy code cleanup] occurrence: 34 pattern: Variable 'varname' is assigned a value that is never used

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1613]
### Problem

We see 34 occurrence of pattern, "Variable 'varname' is assigned a value that is never used".

### Expected behavior

We should not be getting these warnings

### How to reproduce

`#  codacy-analysis-cli analyze --allow-network   --tool cppcheck --directory /root/Code/cortx-motr/`

### Deployment information

Install and start docker. Then fire the below commands :

```
$ curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz 
 
$ cd codacy-analysis-cli-master && sudo make install 
```

### Additional information

`#  codacy-analysis-cli analyze --allow-network   --tool cppcheck --directory /root/Code/cortx-motr/ | grep "never used"  `   Found [Info] `Variable 'bytes_copied' is assigned a value that is never used.` in cm/cp.c:833 (cppcheck_unreadVariable)
Found [Info] `Variable 'inode' is assigned a value that is never used.` in m0t1fs/linux_kernel/dir.c:1196 (cppcheck_unreadVariable)
Found [Info] `struct member 'io_req::ir_magic' is never used.` in desim/elevator.c:41 (cppcheck_unusedStructMember)
Found [Info] `struct member 'm0_instance::ci_laddr' is never used.` in motr/m0kv/index.c:45 (cppcheck_unusedStructMember)
Found [Info] `Variable 'fop.f_opaque' is assigned a value that is never used.` in motr/ut/obj.c:1267 (cppcheck_unreadVariable)
Found [Info] `Variable 'rc' is assigned a value that is never used.` in stats/stats_srv.c:625 (cppcheck_unreadVariable)
Found [Info] `Variable 'op' is assigned a value that is never used.` in cas/client.c:534 (cppcheck_unreadVariable)
Found [Info] `Variable 'fctx.cfg' is assigned a value that is never used.` in be/fmt.c:145 (cppcheck_unreadVariable)
Found [Info] `Variable 'svc_total' is assigned a value that is never used.` in spiel/ut/spiel_ci_ut.c:389 (cppcheck_unreadVariable)
Found [Info] `struct member 'Anonymous0::num' is never used.` in net/ut/bulk_if.c:54 (cppcheck_unusedStructMember)
Found [Info] `Variable 'inactive_accs' is assigned a value that is never used.` in sns/cm/repair/ag.c:277 (cppcheck_unreadVariable)
Found [Info] `Variable 'result' is assigned a value that is never used.` in sns/ut/parity_math_mt_ub.c:222 (cppcheck_unreadVariable)
Found [Info] `struct member 'm0_dtm_dtx_party::pa_dtx' is never used.` in dtm/ut/dtx.c:327 (cppcheck_unusedStructMember)
Found [Info] `Variable 'new_gen_id' is assigned a value that is never used.` in helpers/ufid.c:62 (cppcheck_unreadVariable)
Found [Info] `Variable 'pm' is assigned a value that is never used.` in sns/poolmach.c:73 (cppcheck_unreadVariable)
Found [Info] `struct member 'rpc_link_state_transition::rlst_st_desc' is never used.` in rpc/link.c:61 (cppcheck_unusedStructMember)
Found [Info] `Variable 'offset' is assigned a value that is never used.` in xcode/xcode.c:126 (cppcheck_unreadVariable)
Found [Info] `Variable 'list_nr_more' is assigned a value that is never used.` in layout/ut/layout.c:622 (cppcheck_unreadVariable)
Found [Info] `Variable 'cw' is assigned a value that is never used.` in motr/m0crate/parser.c:361 (cppcheck_unreadVariable)
Found [Info] `Variable 'buf_size' is assigned a value that is never used.` in cm/cp.c:834 (cppcheck_unreadVariable)
Found [Info] `struct member 'm0_instance::ci_prof' is never used.` in motr/m0kv/index.c:48 (cppcheck_unusedStructMember)
Found [Info] `Variable 'id.u_lo' is assigned a value that is never used.` in motr/ut/client.c:408 (cppcheck_unreadVariable)
Found [Info] `Variable 'm0_xcode_union_close' is assigned a value that is never used.` in conf/obj.c:408 (cppcheck_unreadVariable)
Found [Info] `Variable 'rc' is assigned a value that is never used.` in lib/ut/buf.c:120 (cppcheck_unreadVariable)
Found [Info] `struct member 'm0_instance::ci_confd_addr' is never used.` in motr/m0kv/index.c:47 (cppcheck_unusedStructMember)
Found [Info] `Variable 'dumped' is assigned a value that is never used.` in cas/ctg_store.c:2061 (cppcheck_unreadVariable)
Found [Info] `Variable 'off' is assigned a value that is never used.` in motr/st/layout.c:840 (cppcheck_unreadVariable)
Found [Info] `Variable 'count' is assigned a value that is never used.` in m0t1fs/linux_kernel/file.c:2512 (cppcheck_unreadVariable)
Found [Info] `Variable 'i' is assigned a value that is never used.` in be/btree.c:1152 (cppcheck_unreadVariable)
Found [Info] `struct member 'm0_instance::ci_ha_addr' is never used.` in motr/m0kv/index.c:46 (cppcheck_unusedStructMember)
Found [Info] `Variable 'nr_comp_exts' is assigned a value that is never used.` in motr/st/layout.c:1058 (cppcheck_unreadVariable)
Found [Info] `Variable 'deadline' is assigned a value that is never used.` in be/log_discard.c:315 (cppcheck_unreadVariable)
Found [Info] `Variable 'bytes' is assigned a value that is never used.` in lib/ub.c:150 (cppcheck_unreadVariable)
Found [Info] `struct member 'layout_prefix::lp_l_id' is never used.` in layout/composite.c:44 (cppcheck_unusedStructMember)
Found [Info] `Variable 'fop.f_opaque' is assigned a value that is never used.` in motr/ut/obj.c:945 (cppcheck_unreadVariable)
Found [Info] `struct member 'layout_prefix::lp_filler' is never used.` in layout/composite.c:50 (cppcheck_unusedStructMember)
Found [Info] `Variable 'rc' is assigned a value that is never used.` in motr/client.c:570 (cppcheck_unreadVariable)
Found [Info] `Variable 'root_obj.confc' is assigned a value that is never used.` in conf/ut/rconfc.c:1370 (cppcheck_unreadVariable)
Found [Info] `struct member 'stob_perf_stats::unused' is never used.` in stob/perf.c:127 (cppcheck_unusedStructMember)
Found [Info] `Variable 'prev' is assigned a value that is never used.` in xcode/xcode.c:127 (cppcheck_unreadVariable)
Found [Info] `Variable 'buf_size' is assigned a value that is never used.` in sns/cm/repair/xform.c:106 (cppcheck_unreadVariable)
Found [Info] `Variable 'm0_fid_type_unregister' is assigned a value that is never used.` in conf/obj.c:420 (cppcheck_unreadVariable)
Found [Info] `Variable 'rc' is assigned a value that is never used.` in helpers/ufid.c:181 (cppcheck_unreadVariable)
Found [Info] `Variable 'now' is assigned a value that is never used.` in m0t1fs/linux_kernel/dir.c:1200 (cppcheck_unreadVariable)
Found [Info] `Variable 'rc' is assigned a value that is never used.` in motr/ut/client.c:333 (cppcheck_unreadVariable)

**Comment by rkothiya** [comment]
It was decided that for warnings in c files the bugs will be assigned to specific team which own that component.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

It was decided that for warnings in c files, the bugs will be assigned to specific team which own that component.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Bug were distributed in the team as per the decision in team meeting.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Warnings wont be fixed as part of this bug.
