### ISSUE TITLE
Alex exeptions

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#1618]
# 
 ## 
 ### Please describe the feature/improvement you would like to see added.

Alex is causing too many unnecessary alerts in this repo. @venkuppu-chn can you please add the following words to an Alex exception list:

executed
 failed
 DIX
 failures
 periods
 crash
 just
 easily
 special

garbage
 # 
 ## 
 ### Please explain why you think adding this feature/improvement is important.

It will reduce false positives and make it easier to fix what really needs fixing.

FYI @andriytk

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30766. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Assigning the same to [~744417] for adding above words as exception for cortx-motr repo

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~744417],

Have we made any progress on this ticket?

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

[~530903], I have added the words mentioned in ticket into Alex exception. Those words are ignored which scanning. Please refer the PR link. 

https://github.com/Seagate/cortx-motr/pull/1748

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed and corresponding PR is merged
