### ISSUE TITLE
tnet-test:client-server-bulk UT fails

### ISSUE THREAD

**Issue by nikitadanilov** [Seagate/cortx-motr#1666]
### Problem

$ ./utils/m0run m0ut -- -n4000 -tnet-test:client-server-bulk

fails after a few dozen iterations:

START Iteration: 18 out of 10000
net-test
  client-server-bulk  motr[1077012]:  ba20  FATAL  [lib/assert.c:50:m0_panic]  panic: (can_change) at node_bulk_state_change() (net/test/node_bulk.c:384)  [git: 2.0.0-670-45-g87fc0d31-dirty]... /var/motr/m0ut/m0trace.1077012

Thread 422 "lt-m0ut" received signal SIGABRT, Aborted.
(gdb) bt
#0  0x00007fffe9a6b38f in raise () from /lib64/libc.so.6
#1  0x00007fffe9a55dc5 in abort () from /lib64/libc.so.6
#2  0x00007fffebda7020 in m0_arch_panic (c=0x7fffed39a4e0 <__pctx.8244>, ap=0x7fff4e7fbab8) at lib/user_space/uassert.c:131
#3  0x00007fffebd87368 in m0_panic (ctx=0x7fffed39a4e0 <__pctx.8244>) at lib/assert.c:52
#4  0x00007fffed1856f1 in node_bulk_state_change (ctx=0x7fff6c000ef0, bs_index=3, state=TS_QUEUED) at net/test/node_bulk.c:384
#5  0x00007fffed187563 in client_transfer_start (ctx=0x7fff6c000ef0, bs_index=3) at net/test/node_bulk.c:969
#6  0x00007fffed1876fe in client_process_unused_bulk (ctx=0x7fff6c000ef0) at net/test/node_bulk.c:1013
#7  0x00007fffed18843a in node_bulk_worker (ctx=0x7fff6c000ef0) at net/test/node_bulk.c:1304
#8  0x00007fffebd94948 in m0_thread_trampoline (arg=0x7fff6c0012f0) at lib/thread.c:117
#9  0x00007fffebda8697 in uthread_trampoline (arg=0x7fff6c0012f0) at lib/user_space/uthread.c:98
#10 0x00007fffeb38715a in start_thread () from /lib64/libpthread.so.0
#11 0x00007fffe9b30dd3 in clone () from /lib64/libc.so.6

### Expected behavior

UT should not fail.

### How to reproduce

See above.

### Deployment information

Rocky Linux VM

### Additional information

See PR https://github.com/Seagate/cortx-motr/pull/1665.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30981. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
This issue will be fixed via [https://github.com/Seagate/cortx-motr/pull/1665](url)

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Expand the critical sections to cover buffer state changes.

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Done.

**Comment by cortx-admin** [comment]
> Upendra Patwardhan commented in Jira Server:

Verified by running UT continuously for 1000 times.
