### ISSUE TITLE
lnet failure on latest centos 7 kernel with Mellanox

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-motr#17]
Am trying Cortx on latest Centos 7.8.2003 kernel 3.10.0-1127.19.1.el7.x86_64. I built lustre clients using `https://github.com/Seagate/cortx-re/blob/master/scripts/release_support/build_lustre.sh` on latest kernel using mlnx ofed that has support for rhel 7.8 `https://linux.mellanox.com/public/repo/mlnx_ofed/4.9-0.1.7.0/rhel7.8/x86_64/UPSTREAM_LIBS/`

But if I try to start lnet, I get below errors.

```
# lctl net up
LNET configure error 22: Invalid argument
```

```
Sep  2 13:26:27 xxxx-xxx kernel: LNetError: 172781:0:(api-ni.c:2533:lnet_startup_lndnet()) Can't load LND o2ib, module ko2iblnd, rc=256
Sep  2 13:26:29 xxxx-xxx kernel: ko2iblnd: disagrees about version of symbol ib_fmr_pool_unmap
Sep  2 13:26:29 xxxx-xxx kernel: ko2iblnd: Unknown symbol ib_fmr_pool_unmap (err -22)
Sep  2 13:26:29 xxxx-xxx kernel: ko2iblnd: disagrees about version of symbol __ib_alloc_pd
Sep  2 13:26:29 xxxx-xxx kernel: ko2iblnd: Unknown symbol __ib_alloc_pd (err -22)
Sep  2 13:26:29 xxxx-xxx kernel: ko2iblnd: disagrees about version of symbol rdma_resolve_addr
```

```
# cat /etc/modprobe.d/lnet.conf
options lnet networks=o2ib(ienp175s0f0)  config_on_load=1  lnet_peer_discovery_disabled=1
```

Any suggestions? @chumakd  @just-now @tgeerdes-SG

**Comment by madhavemuri** [comment]
This issue is resolved.

**Comment by huanghua78** [comment]
@kaustubh-d , currently Motr is supporting CentOS 7.8. Can you try again?

**Comment by huanghua78** [comment]
This is fixed.
