### ISSUE TITLE
"make rpms" does not work

### ISSUE THREAD

**Issue by nikitadanilov** [Seagate/cortx-motr#1774]
### Problem

$ git clone https://github.com/Seagate/cortx-motr.git
$ cd cortx-motr
$ ./autogen.sh
$ ./configure
$ make -j32
$ make rpms
...

RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/cortx-motr-2.0.0-1_gitee644b1b5_4.18.0_305.10.2.el8_4.el8.x86_64/usr/bin/workload*
    Mixing main ELF and debug files in package    File listed twice: /usr/lib/.build-id/07/4a5278e1a4ecf389218fb58978158658092ba9
    File listed twice: /usr/lib/.build-id/18/d53a1efd010e3219319101ec958b02fad90c92
    File listed twice: /usr/lib/.build-id/34/775a7f3e6ace58fcf7e59b541dbc5a5ad869b5
    File listed twice: /usr/lib/.build-id/54/b67f9e8fa33dd4b48236b868bd6580568dfe04
    File listed twice: /usr/lib/.build-id/85/9ec98b08eb4d578092f720ebe8baa4257991df
    File listed twice: /usr/lib/.build-id/89/70f0c1243641ae4db9ac2191ac465c48c19651
    File listed twice: /usr/lib/.build-id/ba/7904bc9b12e7911ef79b50ab0c91671c1de352
    File listed twice: /usr/share/man/man1
    File listed twice: /usr/share/man/man1/m0d.1.gz
    File listed twice: /usr/share/man/man1/m0gccxml2xcode.1.gz
    File listed twice: /usr/share/man/man1/m0trace.1.gz
    File listed twice: /usr/share/man/man1/m0traced.1.gz
    File listed twice: /usr/share/man/man1/m0tracedump.1.gz
    File listed twice: /usr/share/man/man7
    File listed twice: /usr/share/man/man7/motr.7.gz
    Deprecated external dependency generator is used!
    Dependency tokens must begin with alpha-numeric, '_' or '/': debuginfo(build-id) = 0174e7a9709b57b1a697ccc3c6baba0db4c92219
debuginfo(build-id) = 06a06aaec20a70c86bde88d573f55cc30bc88171
debuginfo(build-id) = 074a5278e1a4ecf389218fb58978158658092ba9
debuginfo(build-id) = 09640d99ca5d18daf4374c33adee0d429cc23a90
...
    Failed to find Provides:
make[1]: *** [Makefile:20730: __rpm] Error 1
make: *** [Makefile:20771: rpms] Error 2

### Expected behavior

Should build rpms.

### How to reproduce

See above.

### Deployment information

CentOS or RockyLinux VM.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31326. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nikitadanilov** [comment]
I found the root cause: because of a wrong TERM setting, utilities like "grep" and "ls" were leaking escape sequences to their output. Makefile should reset TERM to some safe value, like "dumb".

**Comment by cortx-admin** [comment]
> Swapnil Chaudhary commented in Jira Server:

I was able to run make rpms command on my local rocky linux VM.
{noformat}
[root@ssc-vm-g3-rhev4-2993 SRPMS]# ls
cortx-motr-2.0.0-1_git1c6ef410_4.18.0_305.3.1.el8_4.el8.src.rpm  cortx-motr-2.0.0-1_git47508cad_4.18.0_305.3.1.el8_4.el8.src.rpm
cortx-motr-2.0.0-1_git317b5ca6_4.18.0_305.3.1.el8_4.el8.src.rpm  libfabric-1.11.2-1.el8.src.rpm
[root@ssc-vm-g3-rhev4-2993 SRPMS]# pwd
/root/rpmbuild/SRPMS
{noformat}
Log file: [^CORTX-31326TestLogs.txt]

On my set-up, TERM is set to xterm.
{noformat}
[root@ssc-vm-g3-rhev4-2993 /]# env | grep TERM
TERM=xterm
{noformat}

**Comment by cortx-admin** [comment]
> Swapnil Chaudhary commented in Jira Server:

Currently, I have set the value of TERM env variable to dumb. And still make rpms command is working.
Refer logs [^31326_log_with_term_setto_dumb.txt]
{noformat}
[root@ssc-vm-g3-rhev4-2993 cortx-motr]# env | grep TERM
TERM=dumb
{noformat}

[~517711], are you suggesting to SET the TERM variable to 'dumb' in makefile ? or do it manually before issuing make rpms command ?

BDW, why are we not seeing this issue on our rocky linux VM machines ?

**Comment by swapnil-seagate** [comment]
@nikitadanilov, are you suggesting to SET the TERM variable to 'dumb' in makefile ? or do it manually before issuing make rpms command ?
And, why are we not seeing this issue on our rocky linux VM machines ?
Also, I see the reporter has not ran the install-build-deps or equivalent command before running makr rpms.
QSG Guide: https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst

**Comment by cortx-admin** [comment]
> Swapnil Chaudhary commented in Jira Server:

Closing this ticket based on chat with [~517711]
{noformat}
[Yesterday 7:15 PM] Nikita Danilov
Let's close it, it was a local issue on my machine.
{noformat}

**Comment by cortx-admin** [comment]
> Swapnil Chaudhary commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Swapnil Chaudhary commented in Jira Server:

.
