### ISSUE TITLE
Build failed on Rocky Linux 8.4

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1788]
### Problem

Build motr with Rocky Linux 8.4 fail with error below:

```
  CCLD     be/tool/m0betool
  CC       be/tool/m0beck-beck.o
  CCLD     be/tool/m0beck
  CCLD     scripts/systemtap/kem/m0kemc
make[1]: *** No rule to make target 'lustre_config.h', needed by 'all-am'.  Stop.
make: *** [Makefile:4509: all] Error 2
```

### Expected behavior

Build success without error.

### How to reproduce

steps as below:

1.  git clone --recursive https://github.com/Seagate/cortx-motr.git
2.  cd cortx-motr && sudo ./scripts/install-build-deps
3.  ./autogen.sh && ./configure && make

### Deployment information

NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"

### Additional information
uname -r
4.18.0-305.3.1.el8_4.x86_64

cat /proc/version
Linux version 4.18.0-305.3.1.el8_4.x86_64 (mockbuild@ord1-prod-x86build003.svc.aws.rockylinux.org) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Thu Jun 17 07:52:48 UTC 2021

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31496. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
Hi @madhavemuri ,
How long will we be supporting lnet? Do we know if this has any workaround/fix?
If we plan to support the same then we should include the same in QSG validations

**Comment by madhavemuri** [comment]
]# rpm -qa | grep lustre
lustre-client-2.12.7-99.el8.x86_64
lustre-client-devel-2.12.7-99.el8.x86_64
kmod-lustre-client-2.12.7-99.el8.x86_64
# cat /etc/redhat-release
Rocky Linux release 8.4 (Green Obsidian)
]## uname -r
4.18.0-305.3.1.el8_4.x86_64

It's working for me with the same OS and kernel versions.

@chandradharraval : No new development work is planned for lustre, motr works with 2.12.x lustre.

@kiwionly2 : can you post the o/p log of `./scripts/install-build-deps` and `rpm -qa | grep lustre` ?

**Comment by kiwionly2** [comment]
@madhavemuri 

> rpm -qa | grep lustre

![image](https://user-images.githubusercontent.com/77140436/169773543-0193cf40-1cad-4688-bbe7-9a9f9919fd41.png)

I try to create a new directory, clone the code and rebuild again, now I get this instead :

![image](https://user-images.githubusercontent.com/77140436/169773739-e71014a3-a5d4-4beb-9d80-5f3e31708e77.png)

**Comment by chandradharraval** [comment]
@kiwionly2,
Yes we know there is an issue with Rocky linux. 
Meanwhile we fix the issue, can you use ./configure --with-user-mode-only?

**Comment by kiwionly2** [comment]
After I try with `--with-user-mode-only`, it is working. Motr able to build successfully, perhaps this could add to documentation ?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

This was temporary requirement and not the same is no longer needed
Marking this issue Closed as issue should not be seen anymore(As default is --with-user-mode-only)
