### ISSUE TITLE
Motr does not check errno when timer_create returns -1

### ISSUE THREAD

**Issue by ivan-alekhin** [Seagate/cortx-motr#1796]
### Problem

Here is what we see in m0trace when timer_create() fails:

```
35401275  101890.357.258031  49e8720  CALL    lib/user_space/timer.c:198:timer_posix_init         < rc=-1
```

Here is the code that handles the error:

```c
	rc = timer_create(clock_source_timer, &se, &ptimer);
	/* preserve timer->t_ptimer if timer_create() isn't succeeded */
	if (rc == 0)
		timer->t_ptimer = ptimer;
	return M0_RC(rc);
```

Here is an excerpt from the man page:

```
RETURN VALUE
       On success, timer_create() returns 0, and the ID of the new timer is placed in *timerid. 
On failure, -1 is returned, and errno is set to indicate the error.
```

### Expected behavior

Motr must return the actual errno rather than -1.

### How to reproduce

In my case, I'm running DTM0 all2all test that causes an avalanche of connects/disconnects. The problem was observed during debugging of connectivity issues.

So, technically speaking, I have no idea how to reproduce it. However, the fix would be quite trivial (similar to this one https://github.com/Seagate/cortx-motr/commit/ae3c398111ffae336515613aacd22e89c914683c), so that I don't think that we need a special test for that.

### Deployment information

Centos 7.9, dtm/recovery branch in Motr, a special dtm0 branch for Hare, all2all integration test.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31527. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Jugal Patil commented in Jira Server:

Already fixed
