### ISSUE TITLE
User can get corrupted data in degraded read mode

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1817]
Currently, in degraded read mode we read all data units of the parity group without `M0_IO_FLAG_NOHOLE` flag (i.e. we get zeros from servers for the missing units). Some data units of the parity group will be re-read again, if the degraded read was triggered due to a failure when reading some unit. Failed data-units are marked, and they are not tried to be read again. Parity units are read with NOHOLE flag always. When we recover the data of the parity group, we must specify which units are missing and needed to be recovered (see `iomap_dgmode_recov_prepare()` and how it is used).

Now, consider the scenario when the user tries to read the data from a parity group with 2 missing data units (4+2 EC):

1. User tries to read data unit1 of the parity group (note: index vector specified by the user in the read operation spans only this one unit).
2. The read fails (unit is missing) and switches to the degraded read mode.
3. In the degraded read mode, we read all the remaining data units without NOHOLE flag and parity units with NOHOLE flag.
4. Instead of getting the error for the 2nd missing data unit - we get zeros for it.

Now, when recovering the data of unit 1 we get corrupted data, because of zeros in the 2nd missing data unit (the recovery function treats the data of this unit as the correct one instead of recovering it).

Q&A:

Q: Why do we read data units without NOHOLE flag in degraded mode?
A: Because motr does not store the object size and there is no way to know whether the remaining data units are present in the parity group or not. If they are not present, and we use NOHOLE flag - we will get too many errors and more than K missing units in the parity group.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31617. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by andriytk** [comment]
Well, here is a simpler scenario where the proposed solution won't help:
1. User tries to read data unit 1, fails and switches to degraded mode.
2. User tries to read data unit 2 in degraded mode and gets zeros (because unit 2 failed to be written before, for example).
3. User reads parity units successfully and recovers the corrupted data (because of zeros in unit 2).

**Comment by andriytk** [comment]
Suggested solution: impose the requirement on the user that the index vector of the read operation always must span the real object data up to the group size at least.

It means that the index vector must always start where the parity group starts, and only correct case when the index vector can end before the parity group ends - it's when the object does not have data beyond that boundary.

**Comment by andriytk** [comment]
Another possible solution (a better one, as to me) would be to introduce an additional flag, say `M0_OOF_LAST`, which would indicate that the provided index vector for the read operation is the last data of the object, so that libmotr should not try to read the remaining units of the parity group in the degraded mode.

This solution is better because it's simpler for the user to comprehend: 1) it does not impose the requirement to always read in full parity groups; 2) it allows the user to explicitly specify to libmotr where the object data ends, so there are no surprises.

**Comment by madhavemuri** [comment]
@andriytk : Will this solution works for the applications which does truncation or punching of data in the object ?

**Comment by andriytk** [comment]
@madhavemuri, no. But looks like there are no such cases with S3.

**Comment by andriytk** [comment]
@madhavemuri, BTW - about punching: we can read an object with punched data only with the `M0_OOF_HOLE` flag. And using this flag, in general, does not guarantee the correctness of the read data. (Some unit can be missing just because the object was written in degraded mode, and with `M0_OOF_HOLE` flag we will get zeros for it silently without any error and without even trying to recover it.)

So punching should be discouraged from using at all. I think.

**Comment by madhavemuri** [comment]
@andriytk : May we can restrict/ask the user to punch at parity group boundaries only.

**Comment by andriytk** [comment]
@madhavemuri, i don't see how it may help...

**Comment by madhavemuri** [comment]
Agree, with degraded write will have the issues with supporting holes.

Btw with legacy s3server motr was using nohole mode for dgmod, 
commit e72d2f9af3916d2fedc405756a37565e75828083
Author: Vikram Jadhav <vikram.jadhav@seagate.com>
Date:   Mon Sep 7 10:23:07 2020 +0530

    EOS-12638: support read error reporting for holes in object (#296)

    Added M0_OOF_NOHOLE in m0_op_obj which will be passed by motr apps like s3
    during read operations.
    M0_IO_FLAG_NOHOLE is added in m0_io_flags enum to pass it through iofop.
    SIF_NOHOLE is added to the stob layer. If stob layer finds the hole, when
    the flag is set, it returns -EIO.

**Comment by andriytk** [comment]
> legacy s3server motr was using nohole mode for dgmod

Not possible. If you look at the old code (before #1728) - dgmode was reading with holes always. And motr client could not (and still cannot) control the nohole flag in dgmode.

**Comment by madhavemuri** [comment]
@andriytk : I think if we failed to write parity units, then write should fail in both the normal and dgmode.
I don't see the case where we will get holes for parity units in S3. Do you see any such case ?

**Comment by andriytk** [comment]
@madhavemuri, no, why? If two parity units failed to be written with 4+2 EC, but data units were written fine - we still can read the data back.

**Comment by andriytk** [comment]
Note: as I said previously - holes can be used only if we read data back without NOHOLE flag. But reading data without NOHOLE flag does not guarantee the correctness of the data (unless we are reading in read-verify mode). So holes should be discouraged from using at all. Unless there are some external data integrity mechanisms implemented by the user.

**Comment by andriytk** [comment]
Here I managed to reproduce the issue:

```
$ off=0; while [ $off -lt $((256*1024*1024)) ]; do aws s3api get-object --endpoint-url http://localhost:8000 --bucket testbucket --key 256m /tmp/4m.check --range bytes=$off-$((off + 4194303)) && cmp /tmp/4m{,.check} || break; off=$((off + 4194304)); done
...
motr[12782]:  4a70  ERROR  [io_req_fop.c:363:io_bottom_half]  ioo=0x5602dc5ac800 off=167772160 from=inet:tcp:192.168.180.165@21004 rc=-5 ti_rc=-5 @<43000002079a10ae:73c000005b00000>
motr[12782]:  4b50   WARN  [io_req.c:1642:ioreq_dgmode_read]  Process failed parity groups in dgmode/read ioo=0x5602dc5ac800 dgmap_nr=4
{
    "AcceptRanges": "bytes",
    "LastModified": "Wed, 08 Jun 2022 10:56:14 GMT",
    "ContentLength": 4194304,
    "ETag": "\"cc507fe792df7c09f4233d8891b8b130\"",
    "VersionId": "null",
    "ContentRange": "bytes 167772160-171966463/268435456",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
/tmp/4m /tmp/4m.check differ: char 1, line 1
```

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Andriy Tkachuk
* Component Build  :  5184 
* Release Build    :  5629  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5629 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5629
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5629
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5629
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5629 
{panel}
