### ISSUE TITLE
[Codacy code cleanup] occurrence: 10 pattern: redifined-builtin

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1847]
### Problem

We see 10 occurrence of pattern, "redefined-builtin"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # find . -iname "*.py" -exec pylint {} \; | grep "Redefining built-in" ```

### Deployment information

``` # yum install pylint ```

**Comment by rkothiya** [comment]
Pull request https://github.com/Seagate/cortx-motr/pull/1848 should address this.

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Rinku Kothiya
* Component Build  :  5180 
* Release Build    :  5605  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5605 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5605
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5605
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5605
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5605 
{panel}

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Suppressed codacy warning

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Done
