### ISSUE TITLE
[Codacy code cleanup] occurrence: 5 pattern:  no-self-use

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1852]
### Problem

We see 4 occurrence of pattern : "no-self-used"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # pylint <filename> ```

### Deployment information

``` # yum install -y pylint ```

### Additional information

**Following files contains this warnings :**
scripts/addb-py/record.py 
scripts/gdb/gdb-extensions.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32012. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

We have fixed these warnings by making the function static, as it was not using the object's member variables.

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: 
* Component Build  :  5179 
* Release Build    :  5603  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5603 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5603
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5603
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5603
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5603 
{panel}

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The patch has been merged.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Done.
