### ISSUE TITLE
./scripts/install-build-deps fails to install ansible and castxml on Rocky Linux 8.4

### ISSUE THREAD

**Issue by t7ko-seagate** [Seagate/cortx-motr#1854]
### Problem

I followed the quick start guide, [this one](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst), on a fresh new Rocky Linux 8.4 VM from SSC, but `./scripts/install-build-deps` is failing.

When I execute it as specified in QSG:

```
cd cortx-motr && sudo ./scripts/install-build-deps
```

It reports that it's not able to install ansible:

```
Upgraded:
  epel-release-8-15.el8.noarch

Complete!
Updating Subscription Management repositories.
Rocky Linux 8 - ResilientStorage                                                                                                                  68 kB/s | 2.4 kB     00:00
Rocky Linux 8 - BaseOS                                                                                                                            71 kB/s | 2.4 kB     00:00
EPEL-8                                                                                                                                            80 kB/s | 2.8 kB     00:00
Rocky Linux 8 - PowerTools                                                                                                                        79 kB/s | 2.8 kB     00:00
Rocky Linux 8 - AppStream                                                                                                                         83 kB/s | 2.8 kB     00:00
puppet6-el8                                                                                                                                       52 kB/s | 1.8 kB     00:00
Rocky Linux 8 - Extras                                                                                                                            59 kB/s | 2.1 kB     00:00
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides (ansible-core >= 2.12.2 with ansible-core < 2.13) needed by ansible-5.4.0-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I then tried to install without ansible, and am still getting failure -- this time when installing `castxml`:

```
# ./scripts/install-build-deps --no-ansible

.........

Package gcc-8.5.0-4.el8_5.x86_64 is already installed.
Package glibc-headers-2.28-151.el8.x86_64 is already installed.
Package isa-l-2.30.0-1.el7.x86_64 is already installed.
Package make-1:4.2.1-10.el8.x86_64 is already installed.
Package openssl-1:1.1.1k-5.el8_5.x86_64 is already installed.
Package openssl-devel-1:1.1.1k-5.el8_5.x86_64 is already installed.
Package python36-devel-3.6.8-38.module+el8.5.0+671+195e4563.x86_64 is already installed.
Package python3-ply-3.9-9.el8.noarch is already installed.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides libLLVM-13.so()(64bit) needed by castxml-0.4.5-2.el8.x86_64
  - nothing provides libLLVM-13.so(LLVM_13)(64bit) needed by castxml-0.4.5-2.el8.x86_64
  - nothing provides libclang-cpp.so.13()(64bit) needed by castxml-0.4.5-2.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

### Expected behavior

QSG step must complete without errors and install all dependencies:

```
cd cortx-motr && sudo ./scripts/install-build-deps
```

### How to reproduce

Create Rocky Linux 8.4 VM, and follow Hare/Motr quick start guide steps:

https://github.com/Seagate/cortx-hare/blob/main/README.md

### Deployment information

```
# cat /etc/*releas*
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
Rocky Linux release 8.4 (Green Obsidian)
Rocky Linux release 8.4 (Green Obsidian)
Derived from Red Hat Enterprise Linux 8.4
Rocky Linux release 8.4 (Green Obsidian)
cpe:/o:rocky:rocky:8.4:GA

# uname -r
4.18.0-305.3.1.el8_4.x86_64
```

### Additional information

I heard others experienced similar issues recently with freshly created VMs.

**Comment by madhavemuri** [comment]
I too have  faced this issue, temporary solution is,
Instead of  `yum install -y ansible` use,  ` yum install -y ansible-2.9.27-1.el8` .
Thanks to @gauravchaudhari02 for this input.

**Comment by bdekvadiya** [comment]
Hi @sachitanands below workaround is working successfully,

- dnf update #to update the Rocky Linux to version 8.5
- comment the below line in the file "scripts/provisioning/roles/base-os/tasks/main.yml"
#- name: disable SELinux
# selinux:
# state: disabled
# when: ansible_os_family == 'RedHat'
# tags:
# - no-selinux

No need to change the ansible version

**Comment by sachitanands** [comment]
thanks @bdekvadiya after these changes I am able to configure my dev vm. 

Could you please update this info in our main [confluence](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/808583540/Motr+RGW+MGW+on+single-node+HOWTO ) page ?

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Bhargav Dekivadiya
* Component Build  :  5227 
* Release Build    :  5746  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5746 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5746
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5746
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5746
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5746 
{panel}

**Comment by cortx-admin** [comment]
> Bhargav Dekivadiya commented in Jira Server:

New yum repo is added via yum-config-manager. If the installation of ansible is failed, it will install epel repo and ansible again after fetching from the newly added repo.

**Comment by cortx-admin** [comment]
> Bhargav Dekivadiya commented in Jira Server:

Resolved by PR : https://github.com/Seagate/cortx-motr/pull/1940

**Comment by cortx-admin** [comment]
> Bhargav Dekivadiya commented in Jira Server:

Completed
