### ISSUE TITLE
Need Dictionary of Motr Terminology

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#187]
FOB, STOB, etc all should be defined in one single Terminology file.

**Comment by VenkyOS** [comment]
@johnbent - I am working on this with the help of @huanghua78 . An initial file has been created and @huanghua78 has given me review comments, on which I am working.

Link to the file that I am working on - [Terminologies and Definitions](https://github.com/VenkyOS/cortx-motr-1/blob/Terminologies_Addition/doc/Terminologies.rst)

Relevant PR - [Terminologies](https://github.com/Seagate/cortx-motr/pull/192)
