### ISSUE TITLE
Do not assume `sizeof(int)==sizeof(uint64_t)`

### ISSUE THREAD

**Issue by jayeshbadwaik** [Seagate/cortx-motr#188]
In the code referenced [here](https://github.com/Seagate/cortx-motr/blob/8813a3d274a0608fce809d5217e0216a7e57430a/lib/types.h#L79), the enumeration assumes `sizeof(int)==sizeof(uint64_t)`. This is not correct and instead one should use `INT_MAX` to get the maximum integer value.

**Comment by u-u-h** [comment]
This also manifests itself in places where `0xffffffffffffffff` is used as a largest value in an `enum`, which by C standard can only contain `int` values.

**Comment by huanghua78** [comment]
Thank you for report this.

Maybe:
```
0xffffffffffffffffull
```
can be used?

**Comment by u-u-h** [comment]
Of course not.

If you look at the C99 standard
(e.g. http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf)

6.7.2.2 Enumeration specifiers
[...]
Constraints
The expression that defines the value of an enumeration constant shall be an integer constant expression that has a value representable as an int.
[...]
Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined, but shall be capable of representing the values of all the members of the enumeration.


The range of unsigned long long can of course differ from that of an int.

The most portable way is using INT_MAX; while that may not be equivalent if your intent was to have an all-bits-1 constant it will avoid undefined/implementation-defined behavior.

Beware that the size of the enum type can be different from int; the enumeration constants are. 

-uuh




Am 21. November 2020 05:25:19 MEZ schrieb Huang Hua <notifications@github.com>:
>Thank you for report this.
>
>Maybe:
>```
>0xffffffffffffffffull
>```
>can be used?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Seagate/cortx-motr/issues/188#issuecomment-731506627

-- 
Utz-Uwe Haus

**Comment by nikitadanilov** [comment]
motr source code is not standard C, far from it. We depend critically on gcc extensions for one thing. Current code works fine under gcc and llvm (see darwin branch), which is good enough for us.

**Comment by huanghua78** [comment]
This is explained by nikita.
