### ISSUE TITLE
Optimize degraded mode by remembering the decisions about cluster entities

### ISSUE THREAD

**Issue by madhavemuri** [Seagate/cortx-motr#1883]
### Please describe the feature/improvement you would like to see added.

Currently, Motr needs the failed notification from Hare about the cluster entity (disk, node, etc.) in order to start working in the degraded mode. This is OK and fine, but we need to add a few more cases for the degraded mode to start ON automatically.

- On timeout error. When some unit of the parity group cannot be written or read due to the rpc timeout error - we should 1) report it to Hare and 2) switch to the degraded rw mode automatically(

- On an error (disk I/O or network or anything else). Similarly to the above case, we should 1) report the error to Hare and 2) switch to the degraded mode immediately.

Switching to Degraded mode automatically is done in https://github.com/Seagate/cortx-motr/issues/1598 .

To optimize it to further, in both cases, the client should remember the decision for this cluster entity (disk, node, etc.) and continue working in degraded mode for the next requests which would involve this entity. The client should keep some timer for this decision (like 5 mins) in order to try normal mode again later with this cluster entity. (Unless this entity was reported as failed by Hare, in which case the timer should stop and the normal mode is not started until Hare reported the entity as online.)

Also motr should report the hare about the failure.

See more at https://github.com/Seagate/cortx-motr/blob/documentation/doc/dev/dewrite/index.rst

### Please explain why you think adding this feature/improvement is important.

This will improve degraded mode performance, as HA may take some time to send information about failures to all the cluster entities.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32281. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
Hi @madhavemuri ,
Can we create story for this issue(instead of bug) and track it via Degraded path future EPIC?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Based on confirmation from [~520423], converted this into story under F-26E EPIC(Can be changes if not suitable). The same can be picked up in future PI based on roadmap

**Comment by nkommuri** [comment]
Closing this github issue, as we have story for this https://jts.seagate.com/browse/CORTX-32281
