### ISSUE TITLE
cortx-motr check-everything CONFIGURE_OPTS: unbound variable

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#19]
[root@ssc-vm-0925 cortx-motr]# ./scripts/m0 check-everything
----- check_everything -----
./scripts/m0: line 158: CONFIGURE_OPTS: unbound variable

>     check-everything  =  (rebuild + dist-check + run-all) * 2
>                          *NOTE* Please run this command before landing.
>                          .
>                          The command is executed twice (note '* 2' above):
>                          the 2nd time with './configure --disable-m0-asserts'.

**Comment by huanghua78** [comment]
I don't see this issue. Can you please re-check this issue? @yanqingfu

**Comment by yanqingfu** [comment]
@huanghua78 yes, the latest release don't have this issue
