### ISSUE TITLE
Using variable 'node' before assignment

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx-motr#1912]
#### Currently on:
+ **Commit**:  c2546052b33a8164f70f1c03951e35afb033acf0
+ **File**:    [scripts/addb-py/filter.py](https://github.com/Seagate/cortx-motr/blob/c2546052b33a8164f70f1c03951e35afb033acf0/scripts/addb-py/filter.py)
+ **LineNum**: [36](https://github.com/Seagate/cortx-motr/blob/c2546052b33a8164f70f1c03951e35afb033acf0/scripts/addb-py/filter.py#L36)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32364. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by rkothiya** [comment]
Pull request https://github.com/Seagate/cortx-motr/pull/1913 should address this.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

raised a pr

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Rinku Kothiya
* Component Build  :  5194 
* Release Build    :  5665  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5665 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5665
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5665
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5665
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5665 
{panel}

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The patch has been merged
