### ISSUE TITLE
degraded write fails when cob create fails

### ISSUE THREAD

**Issue by madhavemuri** [Seagate/cortx-motr#1937]
### Problem

when writing a 200MB object using rgw and one of m0ds is
killed, there exists a case where degraded write fails if posting
COB CREATION fops fails.

(0) motr cluster settings: 5 ioservices each has 2 disks
parity group settings: 6 + 2 + 0, unit size = 4MB

(1) When writing the last 8MB of the 200MB object (48MB * 4 + 8MB),
as 8MB doesn't cover the whole parity group, for those units
it doesn't span, motr tries to send COB CREATION to ioservice,
see the code around line 1618 in io_nw_xfer.c

(2) when dispatching the fops in nw_xfer_req_dispatch(), it calls
m0_rpc_post() (around line 1870 in io_nw_xfer.c) for those
COB CREATION fops, if the target ioservice happens to crash
and rpc connection is broken, m0_rpc_post() returns -125 error
code, but this error code is not handled in
nw_xfer_req_dispatch(), it is dealt with by
ioreq_cc_bottom_half() instead.

(3) ioreq_cc_bottom_half() sets ioo->ioo_rc to -125.

(4) ioo->ioo_rc is caught at line 491 of
ioreq_iosm_handle_executed() in io_req.c and it returns error
code directly to rgw

### Expected behavior

Degraded write should succeed if number of failures in parity group are within K.

### How to reproduce

Restart m0d while IO is going on.

### Deployment information

k8s, Data EC:4+2+0

**Comment by madhavemuri** [comment]
https://github.com/Seagate/cortx-motr/pull/1884 is created to fix this issue.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32484. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Madhav Vemuri commented in Jira Server:

https://github.com/Seagate/cortx-motr/pull/1884

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Sining Wu
* Component Build  :  5200 
* Release Build    :  5682  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5682 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5682
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5682
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5682
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5682 
{panel}
