### ISSUE TITLE
subprocess call with shell=True identified, security issue.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx-motr#1954]
#### Currently on:
+ **Commit**:  12ecf228797efc000dc0c90934feef054ddb0c39
+ **File**:    [scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py](https://github.com/Seagate/cortx-motr/blob/12ecf228797efc000dc0c90934feef054ddb0c39/scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py)
+ **LineNum**: [78](https://github.com/Seagate/cortx-motr/blob/12ecf228797efc000dc0c90934feef054ddb0c39/scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py#L78)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33346. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The following pr should address this. 
[https://github.com/Seagate/cortx-motr/pull/2032]

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

There are 2 new codacy issues after fixing the 2 issues. The new warnings is, "subprocess call - check for execution of untrusted input". According to the below issue it seems that we need to manually ignore this if we think that the input is trusted :
[https://github.com/PyCQA/bandit/issues/333]

**Comment by rkothiya** [comment]
The pr has been merged.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

set shell=False in the sub process module.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Patch was reviewed and merged.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

We no longer see the critical warning. 

The newly generated low severity warning which was supposed to be manually verified and ignored has been approved for ignoring as commented in pull request and has been ignored and updated in the table.
