### ISSUE TITLE
[Codacy code cleanup] occurrence: 8 pattern: hardcoded_sql_expression

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1955]
### Problem

We see 8 occurrence of pattern : "hardcoded_sql_expression"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # bandit <filename> | grep hardcode ```

### Deployment information

``` # yum install bandit ```

### Additional information

Following files contain these patterns : 
scripts/addb-py/chronometry/hist__client_req.py
scripts/addb-py/chronometry/hist__fom_to_rpc.py
scripts/addb-py/chronometry/hist__fom_req.py
scripts/addb-py/chronometry/hist__ioo_req.py
scripts/addb-py/chronometry/hist__s3req.py
scripts/addb-py/chronometry/hist__srpc_to_crpc.py
scripts/addb-py/chronometry/hist__stio_req.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33366. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by rkothiya** [comment]
As discussed on the call we can safely ignore this particular issue.

**Comment by rkothiya** [comment]
I have marked the issues to be ignored in codacy.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Marked the issues to be ignored and updated the confluence page.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Codacy Warnings ignored.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

done
