### ISSUE TITLE
gccxml_cc1plus: error: cortx-motr/be/btree.h: No such file or directory

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1978]
### Problem

When running `make`, encounter error : 

`gccxml_cc1plus: error: /home/502380/cortx-motr/be/btree.h: No such file or directory`

I had manually inspect dir `cortx-motr/be`, and actually that is no such file `btree.h` available.

![image](https://user-images.githubusercontent.com/77140436/178718563-c3cd3fa6-fa4d-46d7-86cc-1c1d93395bdc.png)

*Seem like this file had been delete from PR #1509 

### Expected behavior

Should be able to build successfully without error.

### How to reproduce

> git clone --recursive https://github.com/Seagate/cortx-motr.git
>cd cortx-motr && sudo ./scripts/install-build-deps
>./autogen.sh && ./configure && make

### Deployment information

Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1160.6.1.el7.x86_64
Architecture: x86-64

### Additional information

This is running under ssc.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33623. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
@kiwionly2 ,
We have merged Btree code recently. Requesting to pull the fresh code, perform clean and then execute make

**Comment by cortx-admin** [comment]
> Kanchan Manohar Chaudhari commented in Jira Server:

I cloned fresh repo and compile the motr with commit {{65bcdcb}}
and I'm not seeing any errors that are reported.

We have merged btree code in commit *[{{3571bc9}}|https://github.com/Seagate/cortx-motr/commit/3571bc94978f56264f0c9a41d0fc7a637e9c747f]*, and old btree code files are removed in this commit. If you have previously cloned and compiled repo before *[{{3571bc9}}|https://github.com/Seagate/cortx-motr/commit/3571bc94978f56264f0c9a41d0fc7a637e9c747f]* commit, I would suggest to run {{./scripts/m0 rebuild}}, this shall resolve the issue that you are seeing.

**Comment by kiwionly2** [comment]
After I clean all workspace, and rebuild, everything is work fine now.

**Comment by cortx-admin** [comment]
> Kanchan Manohar Chaudhari commented in Jira Server:

No work needed, required steps are mentioned in above comment.

**Comment by cortx-admin** [comment]
> Kanchan Manohar Chaudhari commented in Jira Server:

Done, Hence marking this Jira as closed.
