### ISSUE TITLE
Error when trying to install Motr+HARE from iosea release

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-motr#2023]
### Problem

When I try to install Motr+HARE from RPMs using the [iosea release](https://github.com/Seagate/cortx-motr/releases/tag/iosea-vm-v1.0) I get this error on VMWare Workstation 

```
[root@test iosea-vm-v1.0]# sudo hctl bootstrap --mkfs CDF.yaml
2022-07-28 09:51:53: Generating cluster configuration...2022-07-28 09:52:48,714 [WARNING]
Got 15 sec timeout for function run_command (attempt 1). The attempt will be repeated again.
Probable cause : degraded machine performance or poor network.
2022-07-28 09:53:23,838 [WARNING]
Got 15 sec timeout for function run_command (attempt 2). The attempt will be repeated again.
Probable cause : degraded machine performance or poor network.
^C^CTraceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 2670, in <module>
    main()
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 283, in main
    enrich_cluster_desc(cluster_desc, opts.mock)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 399, in enrich_cluster_desc
    ipaddr_key(node['data_iface']))
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 706, in get_facts
    run_command(hostname, 'facter', '--json', *args))
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 90, in wrapper
    return f(*args, **kwds)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 682, in run_command
    return subprocess.check_output(args if is_localhost(hostname) else
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 673, in is_localhost
    for item in socket.gethostbyname_ex(hostname):
```

but when I use SSC-VMs it works fine. I am able to create a cluster without any issues.

### Expected behavior

When I run the bootstrap command it should complete without issues.

### How to reproduce

Follow instruction in README.txt from [iosea release](https://github.com/Seagate/cortx-motr/releases/tag/iosea-vm-v1.0)

### Deployment information

Deploy on VMware Workstation or any local VM client

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33775. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Solution: when I use VMWare Workstation I had to use hostname=localhost.localdomain if I used any other hostname I got the error mentioned above. Does anyone know why this issue occurs? cc: @andriytk

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed and corresponding Github issue is closed now
