### ISSUE TITLE
Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx-motr#2095]
#### Currently on:
+ **Commit**:  e75d4d8149629e147ac2e6a1f9d06b2315e01fd0
+ **File**:    [scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh](https://github.com/Seagate/cortx-motr/blob/e75d4d8149629e147ac2e6a1f9d06b2315e01fd0/scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh)
+ **LineNum**: [55](https://github.com/Seagate/cortx-motr/blob/e75d4d8149629e147ac2e6a1f9d06b2315e01fd0/scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh#L55)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34010. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: Rinku Kothiya
* Component Build  :  5317 
* Release Build    :  5943  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5943 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5943
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5943
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5943
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5943 
{panel}

**Comment by rkothiya** [comment]
The following pr address the issue : 
https://github.com/Seagate/cortx-motr/pull/2096

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The following pr address the issue :
[#2096|https://github.com/Seagate/cortx-motr/pull/2096]

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Removed the unnecessary cat command.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The pr was reviewed and merged

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Warning no longer seen on the Codacy dashboard.
