### ISSUE TITLE
Broken/inaccessible links

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#21]
Hello @VenkyOS 

There are multiple inaccessible links in https://github.com/Seagate/cortx-motr/blob/dev/doc/reading-list.md.  Can you please migrate these documents to github and fix these links?

Thanks to @olsterd for reporting this!

John

**Comment by johnbent** [comment]
@VenkyOS , the broken links have been removed but they need to be replaced with fixed links to migrated documents.  Can you please work with @huanghua78 and @nikitadanilov to find the missing docs and migrate them and fix the links please?

**Comment by VenkyOS** [comment]
Sure @johnbent . I will work with @huanghua78 and @nikitadanilov on the same.

**Comment by huanghua78** [comment]
is this issue done?

**Comment by VenkyOS** [comment]
That is what I am doing. I am converting everything to RST and then provide links.
