### ISSUE TITLE
Graphs in "HDL of DTM" File are Corrupted.

### ISSUE THREAD

**Issue by PengMacro** [Seagate/cortx-motr#211]
I noticed most of the graphs in [HLD_of_distributed_transaction_manager](https://github.com/Seagate/cortx-motr/blob/main/doc/PDF/HLD_of_distributed_transaction_manager.pdf) are corrupted. 
It would be very helpful if they get fixed. Thanks!

**Comment by johnbent** [comment]
@VenkyOS can you please help with this?

**Comment by huanghua78** [comment]
This is caused by converting this document from online doc to pdf directly.

We need to adjust the pictures a little bit before converting.

**Comment by VenkyOS** [comment]
@johnbent - I will correct the same.

Thanks

**Comment by nikitadanilov** [comment]
[HLD of distributed transaction manager.pdf](https://github.com/Seagate/cortx-motr/files/5590436/HLD.of.distributed.transaction.manager.pdf)
I happen to have an original pdf downloaded from google docs. Enjoy.

**Comment by huanghua78** [comment]
This will be fixed when we create .rst files for all these documents.
And @nikitadanilov has provided a good version of this document.

**Comment by PengMacro** [comment]
Thanks all!
