### ISSUE TITLE
ERROR  [net/lnet/ulnet_core.c:674:nlx_core_dom_init] when running example1.c

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-motr#214]
I successfully run the motr, and it gives me this output:

  ```
      MOTR is UP.
        Motr client config:

        HA_addr    : 155.98.36.46@tcp:12345:34:1
        Client_addr: 155.98.36.46@tcp:12345:33:1000
        Profile_fid: <0x7000000000000001:0>
        Process_fid: <0x7200000000000001:64>

        Now please use another terminal to run the example
        with the above command line arguments.
        Please add double quote "" around the arguments
```

So, I run the example1.c by using this following args:
`./example1 "155.98.36.46@tcp:12345:34:1" "155.98.36.46@tcp:12345:33:1000" "<0x7000000000000001:0>" "<0x7200000000000001:64>" "1148576"`

However, I got this error below
```
motr[05880]:  2f30  ERROR  [net/lnet/ulnet_core.c:674:nlx_core_dom_init]  open("/dev/m0lnet", O_RDWR|O_CLOEXEC) failed: errno=13 (EACCES). Please check permissions.
error in m0_client_init: -13
```

I am running this on "dev" branch because the current "main" branch is broken. Please let me know what that error is about and where to debug.

**Comment by huanghua78** [comment]
Please run with 'root' user, or sudo.

**Comment by huanghua78** [comment]
I think, you run "setup_a_running_motr_system.sh" with "root" user or sudo, right?

**Comment by daniarherikurniawan** [comment]
Thanks @huanghua78 ! 
I can run it after "sudo su"
I run "setup_a_running_motr_system.sh" using root because it needs root access when creating /var/motr.

Sorry for the late reply, last week I had my defense. I close this PR for now.
