### ISSUE TITLE
Failed to install kernel-devel for the current kernel

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-motr#217]
### Issue
Unable to setup S3 Server as one of the task failed (_install kernel-devel for the current kernel_).

### Description
Following the Startup Guide > [1.2 Installing Dependencies](https://github.com/Seagate/cortx-s3server/blob/dev/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#12-installing-dependencies), I have encountered 1 failure after running `./init.sh -a`.

Running `uname -r` gives me this

> **[root@ip-172-31-33-177 dev]#** uname -r
> 3.10.0-1062.12.1.el7.x86_64

### Steps to reproduce
```
sudo su -

yum install -y git
yum install -y ansible
yum install -y python3
yum install -y python-pip
yum install -y epel-release

setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

# ============= REBOOT VM =============

sudo su -

git clone --recursive https://github.com/Seagate/cortx-s3server.git -b main
cd cortx-s3server
git submodule update --init --recursive && git status

cd ./scripts/env/dev
./init.sh -a

# ============= ENTER PAT =============
```

### Error Result

> **TASK [base-os : install kernel-devel for the current kernel]**************************
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'kernel-devel-3.10.0-1062.12.1.el7.x86_64' found available, installed or updated", "rc": 126, "results": ["No package matching 'kernel-devel-3.10.0-1062.12.1.el7.x86_64' found available, installed or updated"]}
> ...ignoring
> msg:  No package matching 'kernel-devel-3.10.0-1062.12.1.el7.x86_64' found available, installed or updated
> results:  No package matching 'kernel-devel-3.10.0-1062.12.1.el7.x86_64' found available, installed or updated

> PLAY RECAP **************************
> localhost                  : ok=42   changed=29   unreachable=0    failed=1    skipped=5    rescued=0    ignored=1

Not sure what went wrong...

**Comment by daniarherikurniawan** [comment]
I solve it by manually install the kernel-devel

```
wget https://buildlogs.centos.org/c7.1908.00.x86_64/kernel/20190808101829/3.10.0-1062.el7.x86_64/kernel-devel-3.10.0-1062.el7.x86_64.rpm
sudo rpm -ivh --force kernel-devel-3.10.0-1062.el7.x86_64.rpm
```

**Comment by harrison-seow-seagate** [comment]
Thanks for the suggestion @daniarherikurniawan, I installed wget and ran the command you posted before executing `./init.sh -a` but the task still failed (showing the same exact output).

The `PLAY RECAP` output is also exactly the same for each numbers.

In your case, is there no error? Or do you mean you ignore the error and continue on?

**Comment by johnbent** [comment]
@nileshgovande , this seems to be an error with the S3 quick start guide.  Why are we asking motr folks for help?  Because S3 is calling a motr command which is failing?  @Saumya-Sunder , did you recently have success with the S3 quick start guide?

**Comment by Saumya-Sunder** [comment]
Yes John, I was able to run both Motr and S3 successfully on a VMware Workstation 16 Pro.

**Comment by harrison-seow-seagate** [comment]
Hi @Saumya-Sunder , are there any additional steps you have taken compared to the one listed above? Also, the guide doesn't show how the ldap credentials are configured, is it done by the init.sh script?

**Comment by sachitanands** [comment]
Hi @johnbent  yes, s3 ansible script (init.sh) internally calls motr ansible script (as mentioned in my previous comment) and this step was failing hence we asked help from motr team.

@harrison-seow-seagate ldap credentials are configured as part of s3 ansible script (init.sh) and its documented under "**_Before you begin_**" section of "[1.2.Installing Dependencies](https://github.com/Seagate/cortx-s3server/blob/dev/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#12-installing-dependencies)"

@Saumya-Sunder we need to move this info from "Before you begin " section and add it as normal text as "Note" which will be more visible to our team.
cc @nileshgovande

**Comment by harrison-seow-seagate** [comment]
@sachitanands , I see. Probably the init.sh script failed for those parts which is why I never had the prompts

**Comment by Saumya-Sunder** [comment]
> Hi @johnbent yes, s3 ansible script (init.sh) internally calls motr ansible script (as mentioned in my previous comment) and this step was failing hence we asked help from motr team.
> 
> @harrison-seow-seagate ldap credentials are configured as part of s3 ansible script (init.sh) and its documented under "**_Before you begin_**" section of "[1.2.Installing Dependencies](https://github.com/Seagate/cortx-s3server/blob/dev/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#12-installing-dependencies)"
> 
> @Saumya-Sunder we need to move this info from "Before you begin " section and add it as normal text as "Note" which will be more visible to our team.
> cc @nileshgovande

Sure @sachitanands, moved it in PR https://github.com/Seagate/cortx-s3server/pull/411

**Comment by Saumya-Sunder** [comment]
Do I close the ticket? @sachitanands

**Comment by harrison-seow-seagate** [comment]
@Saumya-Sunder , actually this issue has nothing to do with the documentation, I merely pointed out that the LDAP configuration was nowhere to be found (since I was not prompted due to script failure).

I just re-tried the whole setup but unfortunately it seems that the exact same error is still occurring.

**Comment by Saumya-Sunder** [comment]
@harrison-seow-seagate just a quick question - Did you install Motr before S3?

**Comment by huanghua78** [comment]
CentOS 7.7 problem.
The CentOS 7.7 is obsoleted by CentOS.org.
The packages for this version of release are now not available from centos.org or most of its mirrors.
The best way is to find a mirror which still contains the packages of the CentOS7.7,
or find a ISO file which contains all packages including the kernel-devel.

http://mirrors.oit.uci.edu/centos/7.7.1908/isos/x86_64/
http://mirrors.sohu.com/centos/7.7.1908/

Just for your references.

**Comment by harrison-seow-seagate** [comment]
Hi @Saumya-Sunder , the VM is setup based on the [LocalVMSetup](https://github.com/Seagate/cortx/blob/main/doc/LocalVMSetup.md) and everything else is just as the command posted above. So I'm not even sure if I did install Motr. Could you point me to where I can find the documentation?

@huanghua78 , thanks for the suggestion. I have just tried a few other images and realized that the error "Fail to install kernel-devel" was actually ignored. There's a fail taks for

> TASK [motr-build : build Lustre rpms]

**Comment by huanghua78** [comment]
> @huanghua78 , thanks for the suggestion. I have just tried a few other images and realized that the error "Fail to install kernel-devel" was actually ignored. There's a fail taks for
> 
> > TASK [motr-build : build Lustre rpms]
> 
> EDIT: The kernel-devel installation always failed with same message but was ignored (as posted initially)
> _Note: I'm using AWS to create the VM since I have very low internet bandwidth._

Specific Lustre version (lustre-devel) is needed. Otherwise Motr won't build.
But as I said, the CentOS7.7 is obsoleted by CentOS.org, the corresponding Lustre PRMs probably is not available.

We have a OVA image, installed with all dependencies. But as you are working on a AWS VM, you need to install all the dependencies.
We should verify the steps described in the document again.

**Comment by johnbent** [comment]
Harrison,

We are in the process of switching to centos7.8. Can you try with that and see if that works?

Thanks

John

________________________________

**Comment by Saumya-Sunder** [comment]
Tagging @VenkyOS

**Comment by harrison-seow-seagate** [comment]
Hi @johnbent , the following are some of the images I have tried on AWS (and a few others).

- [CentOS 7 (x86_64) Version  2002_01](https://aws.amazon.com/marketplace/pp/B00O7WM7QW?ref=cns_srchrow)
  - This is the one I used when I posted the issue initially
- [CentOS 7 (x86_64) Version 2003_01](https://aws.amazon.com/marketplace/pp/B08KYKK42V?ref=cns_srchrow)
- [CentOS 7 (x86_64) 2019-08](https://thecloudmarket.com/image/ami-0c862483d46858388--centos-7-pke-201908230912)
- [CentOS 7.8.2003 x86_64](https://thecloudmarket.com/image/ami-066718d3ce3024304--centos-7-8-2003-x86-64-with-cloud-init-hvm-)
  - Just tried
- [CentOS 7.7.1908 x86_64](https://thecloudmarket.com/image/ami-01dd5a8ef26e6341d--centos-7-7-1908-x86-64-with-cloud-init-hvm-)
  - Just tried

All of them failed at the following task with same Play Recap.
>TASK [motr-build : build Lustre rpms]

>PLAY RECAP **************************
localhost : ok=42 changed=29 unreachable=0 failed=1 skipped=5 rescued=0 ignored=1

**Comment by huanghua78** [comment]
This doc, "doc/Quick-Start-Guide.rst" is tested and verified by me again.
It works well.

**Comment by huanghua78** [comment]
[install-dep.txt](https://github.com/Seagate/cortx-motr/files/5620913/install-dep.txt)

I installed a CentOS 7.7.1908 from scratch, following the instructions from https://github.com/Seagate/cortx/blob/main/doc/LocalVMSetup.md

And then, followed the steps one by one in https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst
Everything works well.

But one thing to note.
As CentOS7.7.1908 is obsoleted, you may need to modify your `/etc/yum.repos.d/CentOS-Base.repo` to a valid mirror.

**Comment by harrison-seow-seagate** [comment]
Hi @huanghua78 , I followed your steps but still had the same error.
In your log file, I saw you used `vim ./scripts/install-build-deps` but not sure what did you do?

Also which mirror did you use / how did you fix the `/etc/yum.repos.d/CentOS-Base.repo`?
And which OS did you actually use since there is no CentOS 7.7.1908 from [centos.org](https://www.centos.org/centos-linux/)? I assume it's from this [link](http://mirrors.oit.uci.edu/centos/7.7.1908/isos/x86_64/) you shared but will any of them work?

I also tried using CentOS 7.8.2003 and I installed epel-release before I run install-build-devps, but still failed.

### Exact Commands (CentOS 7.7.1908 - 3.10.0-1062.el7.x86_64)
> sudo su -
> yum install -y git
> echo "SSH KEYS" >> .ssh/id_rsa
> chmod 600 .ssh/id_rsa
> git clone --recursive git@github.com:Seagate/cortx-motr.git -b main
> cd cortx-motr
> sudo ./scripts/install-build-deps

**Comment by huanghua78** [comment]
> Hi @huanghua78 , I followed your steps but still had the same error.
> In your log file, I saw you used `vim ./scripts/install-build-deps` but not sure what did you do?
> 

I did not change the "./scripts/install-build-deps".


> Also which mirror did you use / how did you fix the `/etc/yum.repos.d/CentOS-Base.repo`?

http://mirrors.oit.uci.edu/centos/7.7.1908/
http://mirrors.sohu.com/centos/7.7.1908/
https://vault.centos.org/7.7.1908

You can use either of them.

I myself use this one, because I can access it with higher speed:

```
[root@localhost ~]# diff -u /etc/yum.repos.d/CentOS-Base.repo.bak /etc/yum.repos.d/CentOS-Base.repo
--- /etc/yum.repos.d/CentOS-Base.repo.bak	2020-12-01 07:57:44.912946319 -0500
+++ /etc/yum.repos.d/CentOS-Base.repo	2020-12-01 12:23:36.518375467 -0500
@@ -12,32 +12,28 @@
 
 [base]
 name=CentOS-$releasever - Base
-mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
-#baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
+baseurl=https://mirror.sohu.com/centos/$releasever/os/$basearch/
 gpgcheck=1
 gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
 
 #released updates 
 [updates]
 name=CentOS-$releasever - Updates
-mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
-#baseurl=http://mirror.centos.org/centos/$releasever/updates/$basearch/
+baseurl=https://mirror.sohu.com/centos/$releasever/updates/$basearch/
 gpgcheck=1
 gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
 
 #additional packages that may be useful
 [extras]
 name=CentOS-$releasever - Extras
-mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
-#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/
+baseurl=https://mirror.sohu.com/centos/$releasever/extras/$basearch/
 gpgcheck=1
 gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
 
 #additional packages that extend functionality of existing packages
 [centosplus]
 name=CentOS-$releasever - Plus
-mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
-#baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/
+baseurl=https://mirror.sohu.com/centos/$releasever/centosplus/$basearch/
 gpgcheck=1
 enabled=0
 gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

```



> And which OS did you actually use since there is no CentOS 7.7.1908 from [centos.org](https://www.centos.org/centos-linux/)? I assume it's from this [link](http://mirrors.oit.uci.edu/centos/7.7.1908/isos/x86_64/) you shared but will any of them work?
> 

I am using CentOS 7.7.1908.

```
[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# 

```

kernel-devel (which contains kernel header files) must be installed on system. Otherwise building Lustre will fail, and then building Motr will fail.



> I also tried using CentOS 7.8.2003 and I installed epel-release before I run install-build-devps, but still failed.
> 
> ### Exact Commands (CentOS 7.7.1908 - 3.10.0-1062.el7.x86_64)
> > sudo su -
> > yum install -y git
> > echo "SSH KEYS" >> .ssh/id_rsa
> > chmod 600 .ssh/id_rsa
> > git clone --recursive [git@github.com](mailto:git@github.com):Seagate/cortx-motr.git -b main
> > cd cortx-motr
> > sudo ./scripts/install-build-deps

**Comment by harrison-seow-seagate** [comment]
Thanks, did not have a time to try yet but probably a very specific image is needed for the build.

**Comment by harrison-seow-seagate** [comment]
Turns out it worked and it's because I didn't install the kernel-devel previously. However, I couldn't get it to run on AWS as it would disconnect (SSH) me when during `TASK [motr-build : build Lustre rpms] `. I started a new VM and echo the output, it seems that the script just quietly failed. The VM has 2vCPU, 8GB RAM and 30GB storage.

But since it did work locally, this issue should be closed, thanks again everyone for the help.

**Script For Reference**
```
sudo su -
yum install -y git
yum install wget -y
wget https://buildlogs.centos.org/c7.1908.00.x86_64/kernel/20190808101829/3.10.0-1062.el7.x86_64/kernel-devel-3.10.0-1062.el7.x86_64.rpm
yum install kernel-devel-3.10.0-1062.el7.x86_64.rpm -y
yum install epel-release -y

git clone --recursive https://github.com/Seagate/cortx-motr.git -b main
cd cortx-motr
sudo ./scripts/install-build-deps
```

**Comment by huanghua78** [comment]
>  However, I couldn't get it to run on AWS as it would disconnect (SSH) me when during TASK [motr-build : build Lustre rpms] 

This task may take quite some time (work in background, without output. It seems just like HUNG). So, please make sure
the sshd has a long timeout. Otherwise, it will disconnect you.

**Comment by johnbent** [comment]
Hey @harrison-seow-seagate , I just want to say that getting CORTX working in AWS and documenting how you did it so others can reproduce would be an AMAZING contribution!  FYI @justinzw who I know will be interested in this since he also working on something similar.

**Comment by harrison-seow-seagate** [comment]
@huanghua78 that's exactly the issue, thanks. I managed to proceed with this image in AWS ap-southeast-1 (ami-076898e82e2b6835a) with the following script. Let me know if this is supposed to be documented somewhere.

**Script to Reproduce**
```
sudo su -

yum install -y git
yum install -y ansible
yum install -y python3
yum install -y python-pip
yum install -y epel-release
yum install wget -y
wget https://buildlogs.centos.org/c7.1908.00.x86_64/kernel/20190808101829/3.10.0-1062.el7.x86_64/kernel-devel-3.10.0-1062.el7.x86_64.rpm
yum install kernel-devel-3.10.0-1062.el7.x86_64.rpm -y

setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

reboot
# ============= REBOOT VM =============
sudo su -

git clone --recursive https://github.com/Seagate/cortx-s3server.git -b main
cd cortx-s3server
git submodule update --init --recursive && git status

cd ./scripts/env/dev
./init.sh -a

# ============= ENTER GitHub PAT =============
# ============= ENTER Passwords =============
```
