### ISSUE TITLE
motr-build Error 

### ISSUE THREAD

**Issue by PengMacro** [Seagate/cortx-motr#225]
I am following "[Quick Start Guide](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst)" but got below error when ran "sudo ./scripts/install-build-deps": 
![image](https://user-images.githubusercontent.com/37490734/99874524-4eb94280-2bae-11eb-9271-a284ed2c1ad0.png)

Here is my kernel and Linux version:
```
[root@node-4 home]# uname -r
3.10.0-1062.el7.x86_64
[root@node-4 home]# lsb_release -r
Release:        7.7.1908
```
Thanks!

**Comment by PengMacro** [comment]
Downgrading my kernel to 3.10.0-1062.el7 caused this problem. I can build correctly now if keeps using kernel version 3.10.0-1127.19.1.el7.

**Comment by PengMacro** [comment]
Now I get below error when ran "sudo ./scripts/m0 rebuild".

```
 GCCXML     pool/policy_xc.h
 GCCXML2XC  pool/policy_xc.h
 GCCXML     lib/bitstring_xc.h
 GCCXML2XC  lib/bitstring_xc.h
 GCCXML     cob/cob_xc.h
In file included from /home/cortx-motr/sns/matvec.h:29,
                 from /home/cortx-motr/sns/parity_math.h:30,
                 from /home/cortx-motr/layout/pdclust.h:71,
                 from /home/cortx-motr/conf/obj.h:28,
                 from /home/cortx-motr/conf/cache.h:26,
                 from /home/cortx-motr/conf/confc.h:26,
                 from /home/cortx-motr/rm/rm_ha.h:30,
                 from /home/cortx-motr/rm/rm.h:35,
                 from /home/cortx-motr/file/file.h:32,
                 from cob/cob.h:28:
/home/cortx-motr/sns/parity_ops.h:28:27: error: galois/galois.h: No such file or directory
In file included from /home/cortx-motr/sns/matvec.h:29,
                 from /home/cortx-motr/sns/parity_math.h:30,
                 from /home/cortx-motr/layout/pdclust.h:71,
                 from /home/cortx-motr/conf/obj.h:28,
                 from /home/cortx-motr/conf/cache.h:26,
                 from /home/cortx-motr/conf/confc.h:26,
                 from /home/cortx-motr/rm/rm_ha.h:30,
                 from /home/cortx-motr/rm/rm.h:35,
                 from /home/cortx-motr/file/file.h:32,
                 from cob/cob.h:28:
/home/cortx-motr/sns/parity_ops.h: In function 'm0_parity_elem_t m0_parity_mul(m0_parity_elem_t, m0_parity_elem_t)':
/home/cortx-motr/sns/parity_ops.h:54: error: 'galois_multtable_multiply' was not declared in this scope
/home/cortx-motr/sns/parity_ops.h: In function 'm0_parity_elem_t m0_parity_div(m0_parity_elem_t, m0_parity_elem_t)':
/home/cortx-motr/sns/parity_ops.h:60: error: 'galois_multtable_divide' was not declared in this scope
make[1]: *** [cob/cob_xc.h] Error 1
make: *** [pre-all] Error 2
```

**Comment by nihar1313** [comment]
@PengMacro , Build failure happened due to  "Build environment is not ready." 
The dependency package installation has been failed[sudo ./scripts/install-build-deps]
Since you have  Downgrade your kernel to 3.10.0-1062.el7 version, Earlier build environment is not valid now. Please clean your build environment.remove kmod-lustre-client*, lustre-client-devel*, lustre-client-* packages.
clean your git environment, 
then run ./scripts/install-build-deps
Once it get completed, then do ./scripts/m0 rebuild

**Comment by huanghua78** [comment]
>/home/cortx-motr/sns/parity_ops.h:28:27: error: galois/galois.h: No such file or directory

@PengMacro please checkout git cortx-motr recursively:
```
git clone --recursive git@github.com:Seagate/cortx-motr.git
```

Galois is needed for Cortx-motr. It is a submodule in the repo.
