### ISSUE TITLE
reading-list.md needs to be updated with sharepoint links

### ISSUE THREAD

**Issue by parikshit-dharmale** [Seagate/cortx-motr#23]
The [Motr Reading List](https://github.com/Seagate/cortx-motr/blob/dev/doc/reading-list.md) readme has **almost all the links** redirecting to google docs. 
These links needs to be updated with respective sharepoint links.

There is also reading-list.html file which also needs to be updated (not sure whether this file is required or not as we already have reading-list.md)

cc @johnbent

**Comment by huanghua78** [comment]
In "cortx-motr" "main" branch: https://github.com/Seagate/cortx-motr/blob/main/doc/reading-list.md
These links have been fixed, or will be fixed soon.
