### ISSUE TITLE
ERROR  [be/engine.c:312] when running example1.c with > 300 blocks

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-motr#249]
Got this error when running example1.c with more than 300 blocks. Originally, the example1.c only read and write 2 blocks of data, but I want to test the throughput, so I need to increase the data size. 
The exact code that I run is here (on my own repo):
https://github.com/daniarherikurniawan/cortx-motr-all/blob/master/motr/examples/example1.c

 ```
   motr[00757]:  b860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f8edc036928 engine=0x7ffef801e160 t_prepared=(268026,88716280) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00751]:  c860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f91a0033aa8 engine=0x7ffe6eb79730 t_prepared=(302142,100088668) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00757]:  b860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f8edc039338 engine=0x7ffef801e160 t_prepared=(378903,125676541) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00764]:  e860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f96c403b208 engine=0x7ffc9ce02d30 t_prepared=(276217,89536799) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00747]:  7860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f4fb80345c8 engine=0x7fffc29fdaf0 t_prepared=(299299,99140969) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00751]:  c860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f91a0036508 engine=0x7ffe6eb79730 t_prepared=(393118,130415036) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00764]:  e860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f96c403d5c8 engine=0x7ffc9ce02d30 t_prepared=(406927,131811159) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
    motr[00747]:  7860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f4fb8036fe8 engine=0x7fffc29fdaf0 t_prepared=(381746,126624240) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152

```

If I just use 2 blocks, each has 4KB, everything runs well.

**Comment by andriytk** [comment]
The error from BE suggests that the transaction is too big.

You probably are trying to put too much data units in one op on a narrow pool. As result, you have too many data units per disk in one BE transaction. Try to increase the unit size of your object. (For example, put 9 (1MB) instead of `m0_client_layout_id(instance)` at `object_create()`.)

See how [mio](https://github.com/Seagate/cortx-motr/tree/main/bindings/go) calculates the optimal unit and block sizes based on the total object size at https://github.com/Seagate/cortx-motr/blob/fc73c5c67c0128207c6ae71e94089f2728727a43/bindings/go/mio/mio.go#L262 and at https://github.com/Seagate/cortx-motr/blob/fc73c5c67c0128207c6ae71e94089f2728727a43/bindings/go/mio/mio.go#L342.

**Comment by daniarherikurniawan** [comment]
Sorry, I am not familiar with the code yet. What do you mean by `Try to increase the unit size of your object?`
Could you refer to my example1.c and point out which variable should I increase?
My goal is to read/write 1 GB of data at least. And currently, I am only able to R/W 1.6 MB, so it's still far from my target. Please help me to tune the motr config so that it can write > 1GB. Thank you in advance!

**Comment by andriytk** [comment]
Each object has a specific unit size - the size of the blocks by which its data is written among the disks. By default, it's 4K. You can change it when the object is created, by putting the correspondent layout id at `m0_obj_init()`. 9 is for 1 MB units size, 10 - for 2 MBs, 11 - for 4 MBs. You can check all the values at https://github.com/Seagate/cortx-motr/blob/main/layout/layout_pver.c#L99.

The bigger unit size is better for big objects - it will generate fewer fops in the network and fewer I/O ops at the server-side. But for smaller objects smaller unit size is better to save the storage space.

As I mentioned, try to put the value 9 for `layout_id` into `m0_obj_init()` at `object_create()` function. This will make 1 MB units size for your 1GB object.

**Comment by daniarherikurniawan** [comment]
Thanks for the explanations. It does work until 7 (256KB). Higher than that, I got this error:

```
motr[03944]:  b860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f86e002a4a8 engine=0x7ffe5bc8d460 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
motr[03938]:  c860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f3864023268 engine=0x7ffd92f77a70 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
motr[03951]:  a860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f907c029858 engine=0x7ffd1fd262a0 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
motr[03938]:  c860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f3864024ed8 engine=0x7ffd92f77a70 t_prepared=(290461,87326533) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
motr[03934]:  8860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7ff3080233e8 engine=0x7ffe98ffdce0 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
```

In this case, I have : 
```
const static int N_BLOCK = 20;
const static int BLOCK_SIZE = 8388608; // in Bytes
```
And I use 12 to initialize the unit size 
`m0_obj_init(&obj, &container->co_realm, &obj_id, 12);`

--------------------------------------------------------

If I update the unit size to 13.
`m0_obj_init(&obj, &container->co_realm, &obj_id, 13);`

I got this error:

```
motr[05614]:  ca80  ERROR  [io_req_fop.c:210:io_bottom_half]  ioo=0x2a33890 from=155.98.36.53@tcp:12345:33:901 rc=-7 ti_rc=-7 @<4300000100000000:bc6170>
motr[05614]:  cab0  ERROR  [io_req.c:538:ioreq_iosm_handle_executed]  iro_dgmode_write() failed, rc=-7
```
Is there any other variable that I could increase? It seems like my workload got bumped into some size limit.

**Comment by huanghua78** [comment]
@daniarherikurniawan 
To write data into an object, we have to do:
* choose a layout for an object: Layout ID. As @andriytk has explained, we can choose layout_id 9 (1MB), for example.
* choose a block_size in the program. This should match the layout if we want to achieve optimized performance.
* Usually, we can not pack too much data in a single request. In the example1.c, two blocks are packed into a single request.
   We may increase this number, but please remember this might exceed the maximal size limit. This needs to be tuned in 
   program.
* The most important note here:
   We don't write all data in one single request! The data should be written in an iteration.
   A single iteration only write a chunk of data (block_size * block_count).
   Next iteration should continue writing data from the last offset.


Example1.c is a beginner's guide, not a full demonstration of a complex program.
Please refer to m0cp, m0cat source code.

**Comment by huanghua78** [comment]
> Thanks for the explanations. It does work until 7 (256KB). Higher than that, I got this error:
> 
> ```
> motr[03944]:  b860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f86e002a4a8 engine=0x7ffe5bc8d460 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
> motr[03938]:  c860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f3864023268 engine=0x7ffd92f77a70 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
> motr[03951]:  a860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f907c029858 engine=0x7ffd1fd262a0 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
> motr[03938]:  c860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7f3864024ed8 engine=0x7ffd92f77a70 t_prepared=(290461,87326533) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
> motr[03934]:  8860  ERROR  [be/engine.c:312:be_engine_got_tx_open]  tx=0x7ff3080233e8 engine=0x7ffe98ffdce0 t_prepared=(385285,115850973) t_payload_prepared=131072 bec_tx_size_max=(262144,100663296) bec_tx_payload_max=2097152
> ```
> 
> In this case, I have :
> 
> ```
> const static int N_BLOCK = 20;
> const static int BLOCK_SIZE = 8388608; // in Bytes
> ```
> 
> And I use 12 to initialize the unit size
> `m0_obj_init(&obj, &container->co_realm, &obj_id, 12);`
> 
> If I update the unit size to 13.
> `m0_obj_init(&obj, &container->co_realm, &obj_id, 13);`
> 
> I got this error:
> 
> ```
> motr[05614]:  ca80  ERROR  [io_req_fop.c:210:io_bottom_half]  ioo=0x2a33890 from=155.98.36.53@tcp:12345:33:901 rc=-7 ti_rc=-7 @<4300000100000000:bc6170>
> motr[05614]:  cab0  ERROR  [io_req.c:538:ioreq_iosm_handle_executed]  iro_dgmode_write() failed, rc=-7
> ```
> 
> Is there any other variable that I could increase? It seems like my workload got bumped into some size limit.

The data size (block_size * block_size) in a single request exceeds the some limit.
If you have bigger block_size, please use smaller block_count for a *SINGLE request*.
If you have smaller block_size, you may have some bigger block_count for a *SINGLE request*.

As I explained in previous comment, you need to write data in multiple requests, and each request contains reasonable size of data. (Please pay attention to the offset for each request).

**Comment by johnbent** [comment]
Hey @daniarherikurniawan ,

Maybe you can try adding a loop?
——
1. Prepare a reasonable size of request.
2. Send this request.
3. Wait for this request to be completed.
4. Go back to prepare another request (with proper offset: offset should be increased by the size of the previous request).
——
Thanks to @huanghua78 for putting this in an email to me; I’m merely copying it here.  :)

**Comment by huanghua78** [comment]
This is explained. Developers should avoid putting too much data in a single op.
