### ISSUE TITLE
Change name of branch please

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#278]
@jadhavik1, I see you are working on a branch called 'seq_balloc_1mb_master'.  This violates our naming rules.  If you are still working on this branch please change the name to 'seq_balloc_1mb_main'.  If the branch is no longer needed, then please either rename it or delete it.

Thanks!

**Comment by nkommuri** [comment]
Closing as I don't see the branch now. Please reopen if the issue exists.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Linked Github issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
