### ISSUE TITLE
It takes several minutes to stop the last confd during hctl shutdown

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#283]
On multi-nodes cluster (3+ server nodes) with 3+ confd-s configured `hctl shutdown` command would get stuck for several minutes when stopping the last confd process:

```
[vagrant@cmu motr]$ hctl shutdown
Stopping m0d@0x7200000000000001:0x1c (ios) at ssu1.local...
Stopping m0d@0x7200000000000001:0x42 (ios) at ssu2.local...
Stopping m0d@0x7200000000000001:0x65 (ios) at ssu3.local...
Stopping m0d@0x7200000000000001:0x88 (ios) at ssu4.local...
Stopping m0d@0x7200000000000001:0xab (ios) at ssu5.local...
Stopping m0d@0x7200000000000001:0xce (ios) at ssu6.local...
Stopping m0d@0x7200000000000001:0xf1 (ios) at ssu7.local...
Stopped m0d@0x7200000000000001:0x1c (ios) at ssu1.local
Stopped m0d@0x7200000000000001:0x42 (ios) at ssu2.local
Stopped m0d@0x7200000000000001:0xce (ios) at ssu6.local
Stopped m0d@0x7200000000000001:0xab (ios) at ssu5.local
Stopped m0d@0x7200000000000001:0xf1 (ios) at ssu7.local
Stopped m0d@0x7200000000000001:0x88 (ios) at ssu4.local
Stopped m0d@0x7200000000000001:0x65 (ios) at ssu3.local
Stopping m0d@0x7200000000000001:0x7 (confd) at cmu.local...
Stopping m0d@0x7200000000000001:0x19 (confd) at ssu1.local...
Stopping m0d@0x7200000000000001:0x3f (confd) at ssu2.local...
Stopped m0d@0x7200000000000001:0x19 (confd) at ssu1.local
Stopped m0d@0x7200000000000001:0x3f (confd) at ssu2.local

!!!!!!!!!!!!!!!!!!!   IT GETS STUCK HERE   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Stopped m0d@0x7200000000000001:0x7 (confd) at cmu.local
Stopping hare-hax at client1.local...
Stopping hare-hax at cmu.local...
Stopping hare-hax at ssu1.local...
Stopping hare-hax at ssu2.local...
Stopping hare-hax at ssu3.local...
Stopping hare-hax at ssu4.local...
Stopping hare-hax at ssu5.local...
Stopping hare-hax at ssu6.local...
Stopped hare-hax at client1.local
Stopping hare-hax at ssu7.local...
Stopped hare-hax at ssu3.local
Stopped hare-hax at ssu6.local
Stopped hare-hax at ssu4.local
Stopped hare-hax at ssu5.local
Stopped hare-hax at ssu2.local
Stopped hare-hax at ssu1.local
Stopped hare-hax at ssu7.local
Stopped hare-hax at cmu.local
Stopping hare-consul-agent at client1.local...
Stopping hare-consul-agent at cmu.local...
Stopping hare-consul-agent at ssu1.local...
Stopping hare-consul-agent at ssu2.local...
Stopping hare-consul-agent at ssu3.local...
Stopping hare-consul-agent at ssu4.local...
Stopping hare-consul-agent at ssu5.local...
Stopping hare-consul-agent at ssu6.local...
Stopped hare-consul-agent at ssu4.local
Stopping hare-consul-agent at ssu7.local...
Stopped hare-consul-agent at ssu3.local
Stopped hare-consul-agent at ssu6.local
Stopped hare-consul-agent at ssu5.local
Stopped hare-consul-agent at client1.local
Stopped hare-consul-agent at ssu7.local
Stopped hare-consul-agent at cmu.local
Stopped hare-consul-agent at ssu1.local
Stopped hare-consul-agent at ssu2.local
Killing RC Leader at cmu.local... **ERROR**
```

**Comment by nkommuri** [comment]
@andriytk , are you still observing the issue?

**Comment by andriytk** [comment]
Yes, it still takes a lot of time to stop the cluster (about 5 minutes!). Stopping the last `hax` also takes a lot of time. The reason is probably the same.

To reproduce the problem, one have to do at least 3 steps: 1) start the cluster; 2) connect and disconnect some client app; 3) shutdown the cluster.

**Comment by cortx-admin** [comment]
> Venkatesh Balagani commented in Jira Server:

in LC environment, {{hctl shutdown}} no more supported
{quote}[root@cortx-data-headless-svc-ssc-vm-g4-rhev4-0027 /]# *hctl shutdown*
Failed to get D-Bus connection: Operation not permitted
Failed to get D-Bus connection: Operation not permitted
Cluster is not running
[root@cortx-data-headless-svc-ssc-vm-g4-rhev4-0027 /]#
{quote}
we do {{./destroy-cortx-cloud.sh}} it would take hardly 3-4 minutes. So, we are no more facing above issue

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Assigning this Jira back to reporter for further validation/closure

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~530903] [~747271] [~744427] 

Chandra/Mukul  how do we get this back to 'reporter'?  Board Genius is not a conscious entity.

Also how do we get the history/Corrective Action communicated to them?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Based on comments from [~744856], assigning it to reporter [~520414] for further closure

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~520414] [~519455]

What is the next step for this issue?

**Comment by cortx-admin** [comment]
> Andriy Tkachuk commented in Jira Server:

{quote}
in LC environment, hctl shutdown no more supported
{quote}

But what about other, non-LC environments? Does it mean that we are not going to support cluster shutdown in any non-LC environment from now on?

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

CORTX per Gregory will be a containerized instantiation going forward.  Kubernetes will need to be deployed on any HW that uses CORTX.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~532357] [~744292] [~752394]

What do we do with this?  It seems noone has ownership of what to do next.

**Comment by cortx-admin** [comment]
> Ujjwal Lanjewar commented in Jira Server:

This seems to be a valid issue. Either of the two things should work
 # A way to for the services (confd etc) to shutdown immediately (and restart)
 # Ability to kill the confd service and when restarted it should start in no time. 

Without these in place, scaling / upgrade use cases will get into trouble.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~532357] [~520414] [~530903] [~520479] [~744292]

Who OWNS this?  it appears noone.  Ujjwal if there are changes to be made here, what is the suggestion for next step?  This has been floundering for *{color:#FF0000}6 MONTHS{color}*

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

This should be picked up whenever we pick up LR work. 

Workaround available for now is to kill the confd service manually

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~522044] [~521878] [~530903] [~744292]

Can this workaround be handled in int QA, etc?  or are we going to run into this every CFT cycle because manual workaround breaks automation?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~211146]

I see this is reported by Community, [~522044] can comment on CFT test scenario(if any) related to this

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue closed. Please reopen if required
