### ISSUE TITLE
New FDMI docs to be converted to be shared with community 

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#3]
@VenkyOS , here are some FDMI documents which are currently private to Seagate but should be migrated to github.  Can you please convert them to RST and migrate them into the doc directory and add links to them in https://github.com/Seagate/cortx-motr/blob/dev/doc/reading-list.md?

Here is the private Seagate-only link where the files exist:
https://seagatetechnology.sharepoint.com/:f:/s/gteamdrv1/tdrive1224/EsBphdcDidhEpSlJk3fvsMYBynVzLA3d4p8lbPjnLoTsxQ?e=mTzD48

Thanks!

**Comment by huanghua78** [comment]
These documents have not yet been converted to github, @VenkyOS ?

**Comment by VenkyOS** [comment]
@huanghua78 - Not yet. It is in my Bucket of To Do activities. Only, FDMI is remaining.

**Comment by nkommuri** [comment]
@VenkyOS  , Hi Venky is this task done? Please close the ticket if done. thanks.

**Comment by huanghua78** [comment]
> @VenkyOS , Hi Venky is this task done? Please close the ticket if done. thanks.

I don't think so. Maybe we need to pick it up again.

**Comment by johnbent** [comment]
@VenkyOS is no longer at Seagate. However, @swatid-seagate can do this work. FYI @novium258

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Review in process.

[https://github.com/Seagate/cortx-motr/pull/1237]

**Comment by cortx-admin** [comment]
> John Forgan commented in Jira Server:

[~530903] Why is this assigned to the "C-6 (ADG)" Team?

cc [~936118]

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

We don't have separate agile team in Jira who works for documentation requests. For making it simple I am changing it to motr4 as we are owning community support for motr

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

[~936118]  has created separate individual PRs. Closing this.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Following are the individual PRs to update the FDMI doc in Motr repo. Once these are merged I can update the readinglist.md file.

 

[https://github.com/Seagate/cortx-motr/pull/1298]


[https://github.com/Seagate/cortx-motr/pull/1299]


[https://github.com/Seagate/cortx-motr/pull/1300]
