### ISSUE TITLE
Pool-wise consumption statistics is needed

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#302]
Currently, the consumption statistics is reported for the whole cluster by Motr, which is useless in case of a multi-pools cluster configuration (like at SAGE):

```json
$ hctl status --json
{
  "pools": [
    [
      "0x6f00000000000001:0x444",
      "tier1-nvme"
    ],
    [
      "0x6f00000000000001:0x451",
      "tier2-ssd"
    ],
    [
      "0x6f00000000000001:0x46c",
      "tier3-hdd"
    ]
  ],
  "profiles": [
    {
      "fid": "0x7000000000000001:0x4da",
      "name": "prof-0",
      "pools": [
        "tier1-nvme",
        "tier2-ssd",
        "tier3-hdd",
        null,
        null
      ]
    }
  ],
  "filesystem": {
    "stats": {
      "fs_free_seg": 51416442504,
      "fs_total_seg": 51545708832,
      "fs_free_disk": 203486464036864,
      "fs_avail_disk": 203486464036864,
      "fs_total_disk": 204053896232960,
      "fs_svc_total": 12,
      "fs_svc_replied": 12
    },
    "timestamp": 1608385030.93602,
    "date": "2020-12-19T14:37:10.936020"
  },
```

Here is the log msg from `hax` which fetches the statistics from Motr periodically using `m0_spiel_filesystem_stats_fetch()` API:

```
Dec 19 14:46:33 client-22 hare-hax[24890]: 2020-12-19 14:46:33,762 [DEBUG] {fs-stats-updater} FS stats are as follows: FsStats(fs_free_seg=51416442504, fs_total_seg=51545708832, fs_free_disk=203486464036864, fs_avail_disk=203486464036864, fs_total_disk=204053896232960, fs_svc_total=12, fs_svc_replied=12)
```

Per-pool consumption statistics is needed.

**Comment by andriytk** [comment]
cc @mssawant, @truptiatseagate, @max-seagate, @nikitadanilov, @just-now, @johnbent.

**Comment by nkommuri** [comment]
@nikitadanilov  Can you please suggest/respond? Thanks.

**Comment by chandradharraval** [comment]
@sg-shankar - Can you confirm on do we have such statistics available already or planned to be implemented as part of any upcoming feature?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~530002],

Any update on my above comments?

**Comment by chandradharraval** [comment]
Hi @andriytk,
What all information are we looking here for capture as part of pool wise statistics?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~708949],

Can you paste degraded byte count output here?

cc : [~934754], [~520423]

**Comment by cortx-admin** [comment]
> Abhishek Saha commented in Jira Server:

Degraded bytecount statistics are presented in an accumulated manner by hare grouped by healthy, degraded, critical, damaged bytes
{noformat}
ssc-vm-g3-rhev4-0847@$ sleep 60 && kubectl exec -it cortx-data-ssc-vm-g3-rhev4-0847-655869dc76-fhcw5 -c cortx-hax -- hctl status
Bytecount:
critical : 0
damaged : 0
degraded : 1132462080
healthy : 564972748{noformat}
in consul they are stored per pool version per ioservice something like this
{noformat}
[root@ssc-vm-g3-rhev4-0219 ~]# kubectl exec -it cortx-data-ssc-vm-g3-rhev4-0218-7886645864-rxjv6 -c cortx-hax -- consul kv get -recurse ios
ioservices/0x7200000000000001:0x17/pvers/0x7600000000000001:0x94/users/8881212:{"bc": 78643200, "object_cnt": 1}
ioservices/0x7200000000000001:0x17/pvers/0x7680000000000008:0x10/users/8881212:{"bc": 0, "object_cnt": 1}
ioservices/0x7200000000000001:0x2e/pvers/0x7600000000000001:0x94/users/8881212:{"bc": 78643200, "object_cnt": 1}
ioservices/0x7200000000000001:0x2e/pvers/0x7680000000000008:0x10/users/8881212:{"bc": 0, "object_cnt": 1}
ioservices/0x7200000000000001:0x3b/pvers/0x7600000000000001:0x94/users/8881212:{"bc": 78643200, "object_cnt": 1}
ioservices/0x7200000000000001:0x3b/pvers/0x7680000000000008:0x10/users/8881212:{"bc": 0, "object_cnt": 1}
ioservices/0x7200000000000001:0x52/pvers/0x7600000000000001:0x94/users/8881212:{"bc": 78643200, "object_cnt": 1}
ioservices/0x7200000000000001:0x5f/pvers/0x7600000000000001:0x94/users/8881212:{"bc": 78643200, "object_cnt": 1}
ioservices/0x7200000000000001:0xa/pvers/0x7600000000000001:0x94/users/8881212:{"bc": 78643200, "object_cnt": 1}
ioservices/0x7200000000000001:0xa/pvers/0x7680000000000008:0x10/users/8881212:{"bc": 0, "object_cnt": 1}{noformat}
[~530903], we currently don't display pool wise data in degraded bytecount.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Assigning this to Motr1 team as the same area is being worked upon by that team

**Comment by nkommuri** [comment]
Closing Gighub issue. Will be addressed through story https://jts.seagate.com/browse/CORTX-23732
