### ISSUE TITLE
Improve links in developer's guide

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#308]
The developer's guide (https://github.com/Seagate/cortx-motr/blob/main/doc/motr-developer-guide.md) has three main sections:
1. A simple Cortx Motr application (object)
2. A simple Cortx Motr application (index)
3. More examples, utilities, and applications

Right at the bottom of the intro (right before the first section A simple Cortx Motr application (object)), we should add:
These document contains the following sections:
1. A simple Cortx Motr application (object)
2. A simple Cortx Motr application (index)
3. More examples, utilities, and applications
And have these be (relevant) links to jump directly to those sections.

In the third section (More examples, utilities, and applications), there are a bunch of references to files (e.g. motr/st/utils/touch.c) which aren't links.  These should be (relative) links to jump directly to the files.

FYI @huanghua78 and @andriytk and @VenkyOS

**Comment by VenkyOS** [comment]
@johnbent - I will work on this accordingly.

**Comment by nkommuri** [comment]
@VenkyOS , Please close the ticket if the requested work is done. Thanks.

**Comment by johnbent** [comment]
@nkommuri , @VenkyOS is no longer at Seagate. These tickets can be reassigned to @swatid-seagate. FYI @novium258

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Assigning to [~936118] based on above comments from John B

**Comment by cortx-admin** [comment]
> Pratik Patil commented in Jira Server:

Added links to sections in document

**Comment by cortx-admin** [comment]
> Pratik Patil commented in Jira Server:

Improved developers guide by adding easy navigation links

**Comment by cortx-admin** [comment]
> Pratik Patil commented in Jira Server:

Fixed

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: 80801716+Garuda5611
* Component Build  :  5357 
* Release Build    :  6025  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/6025 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-6025
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6025
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6025
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6025 
{panel}
