### ISSUE TITLE
ADDB 'how to' guide

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#311]
@VenkyOS , please talk to @just-now and get any and all existing documentation about how to use ADDB.  Then attempt to use that documentation to try to use ADDB yourself.  Then please add a 'How to Use ADDB' page into this repo and please link it appropriately from existing documentation.  Thanks!

**Comment by VenkyOS** [comment]
@johnbent - Sure. I will proceed accordingly.

**Comment by nkommuri** [comment]
Hi @VenkyOS ,  Is this done? Thanks.

**Comment by johnbent** [comment]
Hello @nkommuri , all work assigned to @VenkyOS should be reassigned to @swatid-seagate. FYI @novium258

**Comment by r-wambui** [comment]
Hi @swatid-seagate could you please update on this?

**Comment by swatid-seagate** [comment]
@r-wambui Will sure try to attempt the mentioned issue.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

With whom should I connect to attempt this task?

**Comment by cortx-admin** [comment]
> Trupti Patil commented in Jira Server:

[~936118], I assume your query is about the task mentioned in the description of this ticket. You may connect with [~721080] for the same.

**Comment by nkommuri** [comment]
@swatid-seagate  did you get a chance to connect with Maxim?

**Comment by swatid-seagate** [comment]
@nkommuri awaiting @maximalezhin's response.

**Comment by cortx-admin** [comment]
> Maxim Malezhin commented in Jira Server:

Discussed with [~522123] - work is planned and will be taken in S65 (PI6) due to resources distribution.
[~535110] would you please mention ticket's priority?

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

[~721080], I think this is a lower priority than other engineering work. However, if it is easy to create documentation explaining how to use ADDB, that would be a great document to have. [~752394] is in charge of priorities.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Please have a look into Maxim's comment. Its low priority task and Maxim may update this when needed. My assistance is no more required here and plz delete from my responsibility.

**Comment by cortx-admin** [comment]
> Rahul Kumar commented in Jira Server:

To know about ADDB, You can refer to our confluence page like below links:
 # This documents will give you a overview for ADDB and it's use cases. This will help you for a deep analysis and to identify the bottle neck of the performance. ([https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/891978152/Motr+ADDB+training)]
 # Our chronometry toolkit helps to explore, profile, debug and find bottlenecks as well as reconstruct events of any internal system request. Mainly based on CORTX Motr ADDB subsystem (Analytics and Diagnostic Database), it provides rich set of graphical tools for exploring either individual requests or statistical data analysis and system behavior change over time. ([https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/343703655/WIP+Chronometry+Toolkit)]



[~535110] [~530903]

**Comment by cortx-admin** [comment]
> Rahul Kumar commented in Jira Server:

close
