### ISSUE TITLE
motr[05167]:  cbd0  ERROR  [dix/req.c:794:dix_idxop_meta_update_ast_cb]  All items are failed

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-motr#331]
So I am effectively following the examples here https://github.com/Seagate/cortx-motr/blob/main/motr/examples/example2.c
I am trying to create an index pretty much in the exact same way as the examples. After I call m0_entity_create and launch the operation I get the error described and my launched returns an error and fails.

It might have something to do with how I;ve configured my motr client. Unfortunately I don't know enough about how the indexes work in motr.

**Comment by hessio** [comment]
Here is a link to the original slack question: https://cortxcommunity.slack.com/archives/C019S0SGWNQ/p1610639957003400

The error message: motr[05167]:  cbd0  ERROR  [dix/req.c:794:dix_idxop_meta_update_ast_cb]  All items are failed

**Comment by huanghua78** [comment]
Please provide more details of the program: e.g. source code.

Is the example2 working properly?
If so, what is the difference between your program and the example2.c?

**Comment by wednesday123** [comment]
It's going to be difficult for me to dump all my source here. (not helpful for anyone either at this point).

It will be easier if I can get some context on what the error is specifically referring to.

Then I can figure out whether this is a problem on my end (most likely).

**Comment by huanghua78** [comment]
More information is needed, otherwise we can not tell what is wrong.

**Comment by wednesday123** [comment]
Let me clarify, I'm just asking for an explanation of the error code.

**Comment by huanghua78** [comment]
It means:
All metadata replica in DIX failed.
This might happen when some Motr services are down.

**Comment by wednesday123** [comment]
Great! Really appreciated thanks for the help!
