### ISSUE TITLE
Compiling error with demo-fdmi/m0-instance program

### ISSUE THREAD

**Issue by rupasree-roy** [Seagate/cortx-motr#403]
For reference: 
FDMI+containers demonstration was done for Sage-1. The details and source code are available here : 
https://jts.seagate.com/browse/EURND-91

demo-fdmi code has two parts: An FDMI plugin and a clovis app. Refactored the clovis-app to make it work with the opensource version. However, the FDMI plugin is giving few compiling errors which I am not sure how to take care of. Some of the compiling errors was simple as that had to do with the new naming conventions in opensource code - 'mero' changed to 'motr', 'clovis' name completely removed. There were few more which had a change in the function call and definition. Took care of those. However, there are few function with no reference in the opensource code. Below are the compiling errors showing those function calls: 

```
make
gcc -c -g -std=gnu99 -Wall -Werror -Wno-attributes -Wno-unused-variable -Wno-unused-but-set-variable -D_REENTRANT -D_GNU_SOURCE -DM0_INTERNAL='' -DM0_EXTERN=extern -fno-strict-aliasing -fno-omit-frame-pointer -fno-common -fPIC -include config.h -I/home/rroy/cortx/cortx-motr -I/usr/src/lustre-client-2.12.4/lnet/include -I/usr/src/lustre-client-2.12.4/lustre/include -o src/main.o src/main.c
src/main.c: In function ‘inst_init’:
src/main.c:405:5: error: implicit declaration of function ‘m0_conf_fs_get’ [-Werror=implicit-function-declaration]
     rc = m0_conf_fs_get(m0_reqh2profile(reqh), m0_reqh2confc(reqh), &fs);
     ^
src/main.c: In function ‘init_containers’:
src/main.c:490:5: error: implicit declaration of function ‘m0_clovis_container_create’ [-Werror=implicit-function-declaration]
     m0_clovis_container_create(&small_cont, &ops[0]);
     ^
src/main.c: In function ‘main’:
src/main.c:606:9: error: implicit declaration of function ‘_init’ [-Werror=implicit-function-declaration]
         rc = _init(&m0c, &cfg, true);
         ^
src/main.c:610:9: error: implicit declaration of function ‘m0_default_layout_id’ [-Werror=implicit-function-declaration]
         default_layout = m0_default_layout_id(m0c);
         ^
src/main.c:613:9: error: implicit declaration of function ‘m0_realm_init’ [-Werror=implicit-function-declaration]
         m0_realm_init(&my_realm,
         ^
src/main.c:659:17: error: implicit declaration of function ‘m0_container_op’ [-Werror=implicit-function-declaration]
                 m0_container_op(target, M0_IC_PUT,
                 ^
cc1: all warnings being treated as errors
make: *** [src/main.o] Error 1

```
According to @nikitadanilov these functions are gone due to interface refactoring and cleaning. Have attached the latest demo-fdmi code to which I have made changes according to the opensource code:

[updated_demo_fdmi.tar.gz](https://github.com/Seagate/cortx-motr/files/5922378/updated_demo_fdmi.tar.gz)

**Comment by johnbent** [comment]
Thanks @rupasree-roy for reporting this.  You provided two links.  One to the original code and one to the modified code (uploaded as a tarball).  Is the pasted compilation error coming from the original code or from the modified code in the tarball?  Also, for those of us who can't see inside Seagate, does the tarball contain everything that is at the original link?

**Comment by rupasree-roy** [comment]
The compiling errors are from the original code. There were many other compiling errors which were mainly around change in naming convention and change in function definitions. I changed the original code to take care of those compiling errors and thus the modified code. 

And yes, the tarball contains everything that is at the original link. Just that its the updated version to make it work with the opensource code. I made changes to the following files from the original link : ~/clovis-app/Makefile, ~/clovis-app/src/main.c, ~/m0-instance/Makefile, ~/m0-instance/src/main.c

**Comment by johnbent** [comment]
Thanks Rupasree for the info. Where are you maintaining this code and working on this?  I think it would make sense for you to put this code into a fork of either cortx-motr or m0-client-apps. That way, others of us can pull your fork and help look at these issues. Would that be possible for you to do please?

**Comment by andriytk** [comment]
I've found the code for container functions in an old branch of Motr. Here are the functions:

```c
void m0_container_init(struct m0_container *cont,
		       struct m0_realm     *parent,
		       const struct m0_uint128    *id,
		       struct m0_client           *instance,
		       struct m0_pool             *pool)
{
        M0_ENTRY();

        M0_PRE(cont != NULL);
        M0_PRE(instance != NULL);
        M0_PRE(parent != NULL);
        M0_PRE(pool != NULL);
        M0_PRE(id != NULL);

        m0_realm_init(&cont->cont_realm, parent, id,
		      M0_ST_CONTAINER, instance);
        m0_idx_init(&cont->cont_idx, parent, id);
        cont->cont_pool = pool;

        M0_LEAVE();
}
M0_EXPORTED(m0_container_init);

void m0_container_fini(struct m0_container *cont)
{
        M0_ENTRY();

        M0_PRE(cont != NULL);

        m0_idx_fini(&cont->cont_idx);
        m0_realm_fini(&cont->cont_realm);

        M0_LEAVE();
}
M0_EXPORTED(m0_container_fini);

int m0_container_op(struct m0_container *cont,
		    enum m0_idx_opcode   opcode,
		    struct m0_bufvec    *keys,
		    struct m0_bufvec    *vals,
		    int32_t             *rcs,
		    uint32_t             flags,
		    struct m0_op       **op)
{
        M0_PRE(cont != NULL);
        M0_ENTRY();

        return M0_RC(m0_idx_op(&cont->cont_idx, opcode, keys,
                                      vals, rcs, flags, op));
}


int m0_container_bulk(struct m0_container *cont,
		      struct m0_uint128          *bop,
		      struct m0_param            *datum,
		      struct m0_op       **ops)
{
        M0_ENTRY();

        return M0_RC(m0_idx_bulk(&cont->cont_idx, bop, datum, ops));
}


M0_INTERNAL int m0_container_create(struct m0_container *cont,
				    struct m0_op       **op)
{
        M0_ENTRY();

	M0_PRE(op != NULL);
        M0_PRE(cont != NULL);

        return M0_RC(m0_entity_create(&cont->cont_idx.in_entity, op));
}
```

Looks like they are mostly the wrappers over existing API, that's probably why they never made into the main branch. At least you can see the idea behind them.

**Comment by andriytk** [comment]
Another one:

```c
int m0_idx_bulk(struct m0_clovis_idx *idx,
                       struct m0_uint128    *bop,
                       struct m0_param      *datum,
                       struct m0_op **ops)
{
	int                         rc;
	struct m0_bufvec           *fids;
	struct m0_bufvec           *data;
	int                        *rcs;

	M0_ENTRY();

	M0_PRE(idx != NULL);
	M0_PRE(bop != NULL);
	M0_PRE(datum != NULL);
	M0_PRE(ops != NULL);

	M0_ALLOC_PTR(rcs);
	M0_ALLOC_PTR(fids);
	M0_ALLOC_PTR(data);
	if (!rcs || !fids || !data) {
		return -ENOMEM;
	}
	rc = m0_bufvec_empty_alloc(fids, 1);
	if (rc) {
		return M0_ERR(rc);
	}
	rc = m0_bufvec_empty_alloc(data, 1);
	if (rc) {
		return M0_ERR(rc);
	}

	fids->ov_buf[0] = (void*) bop;
	fids->ov_vec.v_count[0] = sizeof(void*);

	data->ov_buf[0] = (void*) datum;
	data->ov_vec.v_count[0] = sizeof(void*);

	return M0_RC(m0_idx_op(idx, M0_IC_BULK, fids,
		                      data, rcs, 0, ops));
}
```

**Comment by andriytk** [comment]
Instead of `m0_default_layout_id()` use `M0_DEFAULT_LAYOUT_ID` macro.

Don't worry about `m0_realm_init()`, just drop it and see how the realm is used in another examples. (For example, at https://github.com/Seagate/cortx-motr/blob/main/bindings/go/mio/mio.go.)

**Comment by andriytk** [comment]
As for the `m0_conf_fs_get()`, here I updated it to the latest API (`m0_confc_root_open()`) - [m0-instance.tar.gz](https://github.com/Seagate/cortx-motr/files/5932094/m0-instance.tar.gz).

Hope you could continue from here?

**Comment by rupasree-roy** [comment]
@johnbent  I was maintaining the code in one of the lab machines in FRC. And sure I can fork cortx-motr and put the code there.

**Comment by rupasree-roy** [comment]
@andriytk Thank you for sharing those info. Made changes according to what you suggested. 

As far as the wrappers like 'm0_container_op' is concerned, how are we going to take care of that?

**Comment by johnbent** [comment]
@andriytk might say differently but I'd suggest to just add the wrappers yourself in your FDMI plugin.

**Comment by andriytk** [comment]
I'd suggest to make direct calls and get rid of the wrappers.

**Comment by rupasree-roy** [comment]
Adding 
@paulq11 @Lsmithy @Z2020Z

**Comment by huanghua78** [comment]
Please note, this fdmi-demo is somewhat copied from "dix/utils/m0dixinit.c". 
Please refer to "dix/utils/m0dixinit.c " and change the fdmi-demo accordingly.

**Comment by nkommuri** [comment]
@huanghua78 please have a look at this once and suggest what needs to be done. Thanks.

**Comment by huanghua78** [comment]
This issue is outdated.
Please refer to files in `fdmi/plugins/*` for more details about how to write an FDMI application and how to compile it.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github Issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
