### ISSUE TITLE
Improvements in m0crate utility (KV test run).

### ISSUE THREAD

**Issue by somnathbghule** [Seagate/cortx-motr#450]
There are improvement areas such as,

1. Correctness in output logs (for all log levels) of m0crate KV test run.
```
	a. Following parameters are not being used by m0crate kv test but still displayed in the output logs.
		Before Fix:
			info: average size:          65536
			info: maximal size:          1048576
			info: block size:            0
		After Fix:
			No need to display this if KV test run is running.
	b. Following parameter shows wrong output.
		Before Fix:
			info: number of operations:  1000 (OP_COUT: 32 was passed. always shows the same value.). 
		After Fix:
			info: number of operations:  32
	c. If we read following output it looks like percentage of ops but its actually 
            count of number of operations remaining. 
		Before Fix:
			trace: dix: prcnt: [5, 4, 0, 0]		
		After Fix: 
			trace: dix: ops remaining: [5, 4, 0, 0]
	d.  Result should shows details about the test run,
            Before Fix:
                            result: all, 0.133912
            After Fix:
                          result: Total, 0.133912 s
	                          Avg time per ops.
	                          PUT, <time taken by put ops> s
	                          GET, <time taken by get ops> s and so on.

```			
2. Implementation of specifying the specific KEY and VALUE sizes in kv test run, sizes can be number (int) or random.
```
    key_size=sizeof(struct m0_fid)
    value_size=RECORD_SIZE-key_size;
    here RECORD_SIZE is tunable parameter available in .yaml file.
    There is no way/option available to set specific size of key and value.

```

**Comment by madhavemuri** [comment]
@imvenkip : Can you check this PR and verify it ?

**Comment by imvenkip** [comment]
> @imvenkip : Can you check this PR and verify it ?
Sure @madhavemuri . Will check it.

**Comment by imvenkip** [comment]
@somnathbghule  Could you add exactly used m0crate commands?

**Comment by somnathbghule** [comment]
`@somnathbghule``` Could you add exactly used m0crate commands?
`

I used following command to run m0crate kv test.
cmd#
m0crate -S <kv_test .yaml file>

For example:
motr/m0crate/tests/test6.yaml template can be used in m0crate kv test run.
Note: you would require to update few fields in .yaml file like   MOTR_LOCAL_ADDR, MOTR_HA_ADDR, PROF,  PROCESS_FID etc

**Comment by imvenkip** [comment]
> `` @somnathbghule``` Could you add exactly used m0crate commands? ``
> 
> I used following command to run m0crate kv test.
> cmd#
> m0crate -S <kv_test .yaml file>
> 
> For example:
> motr/m0crate/tests/test6.yaml template can be used in m0crate kv test run.
> Note: you would require to update few fields in .yaml file like MOTR_LOCAL_ADDR, MOTR_HA_ADDR, PROF,  PROCESS_FID etc

@somnathbghule  Could you share contents of kv_test .yaml file?

**Comment by nkommuri** [comment]
@imvenkip  @truptiatseagate   Any improvements happened to m0crate as part of this ticket?

**Comment by imvenkip** [comment]
@nkommuri  Already fix is available in main line.
Commit id: 7a734e79fe26f5a1f5b8b28d9859dee7d7750314
Merged PR: https://github.com/Seagate/cortx-motr/pull/461

**Comment by cortx-admin** [comment]
> Zoheb Khan commented in Jira Server:

{noformat}
[root@cortx-data-headless-svc-ssc-vm-rhev4-1739 tmp]# m0crate -S m0crate_sample.yaml
info: starting workload 0
info: workload type          index/3
info: random seed:           0
info: number of threads:     1
info: dix: End of operations.
result: total_s, 156.043289, avg_time_per_op_ns, 876352816.0, key_size_bytes, 16, value_size_bytes, -1, ops, 32
result: PUT, total_time_s, 75.440199, avg_time_per_op_ns, 357506212.0, ops, 32
result: GET, total_time_s, 0.000000, avg_time_per_op_ns, 0.0, ops, 0
result: NEXT, total_time_s, 0.000000, avg_time_per_op_ns, 0.0, ops, 0
result: DEL, total_time_s, 0.000000, avg_time_per_op_ns, 0.0, ops, 0Total: time=[156:043290138] ([4:876352816] per op) ops=32
PUT: [75:440198800] ([2:357506212] per op) ops=32
info: done workload 0
info: ---------------------------------------
{noformat}

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed as the same is not targeted for alpha release. If required the same can be reopened or tracked via story ticket in future
