### ISSUE TITLE
Motr fails in S3-Server setup

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-motr#465]
### Problem

When working on the [S3-server QSG](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md) when I run \`./jenkins-build.sh\` in section "[Test Yout Build](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#14-test-your-build-using-s3-cli)" This warning is shown: motr\[43901\]: dc10 WARN \[ha/entrypoint.c:563:ha\_entrypoint\_client\_fom\_tick\] rlk\_rc=-110. This error is repeatedly shown and the only way to stop this error from repeating endlessly is to kill the terminal tab. Ctrl+c, etc. does not stop this warning being shown. 

The terminal becomes unusable because of this. I asked S3 support and they said it was a Motr error.

**Comment by madhavemuri** [comment]
@yatin-mahajan : Can you look into this issue ?

**Comment by nkommuri** [comment]
@nileshgovande ,  Have you faced this issue during S3 QSG verification recently?

**Comment by r-wambui** [comment]
Hi @hessio is this issue still relevant, are we facing the same issue in the current QSG?

**Comment by hessio** [comment]
As far as I know this issue was resolved

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Corresponding Github issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
