### ISSUE TITLE
Breaking changes with the release of go version 1.16

### ISSUE THREAD

**Issue by suykerbuyk** [Seagate/cortx-motr#466]
https://github.com/Seagate/cortx-motr/blob/3c3921704f18544a181592aaab4cd7bffbc5b202/bindings/go/mcp/mcp.go#L29

In module mode, the go command now disallows import paths that include non-ASCII characters or path elements with a leading dot character (.). Module paths with these characters were already disallowed (see Module paths and versions), so this change affects only paths within module subdirectories.

https://golang.org/doc/go1.16

We should problably split mio out into it's own module, or restructure the go bindings repository as per go conventions with separate module and cmd project space.

**Comment by kiwionly2** [comment]
Hi @suykerbuyk 

What I did to make it run on Go 1.16 ( I get the 1.16.3 install from google site instead from yum ) is as below:
```
>cd ~/cortx-motr/bindings/go/
>go mod init motr
```
This initialize module **motr**.

Modify **mcp.go** to import as _module/folder_ ( is a folder structure anyway).

```
import (
    "os"
    "io"
    "fmt"
    "flag"
    "log"
    "motr/mio"
)
```
Then go to shell
```
>cd mcp
>go build
>go install
```
It will installed on **$GOPATH/bin** directory , in my case is **~/go/bin** , where I installed Go.

Just not sure If we want to upgrade existing code for golang 1.16+. 

Any thought ? @andriytk

Regards,
kiwi

**Comment by andriytk** [comment]
If it's backward compatible (i.e. if it works with go-1.15 also) - yes, we should fix this. Please create a PR. Thanks!

**Comment by kiwionly2** [comment]
For Go 1.16, we could turn off build with module, so code can compile with no change still.

However, after Go 1.17 will only support module, see [here](https://blog.golang.org/go116-module-changes).

Should we change the code to cope with latest Go version?

**Comment by andriytk** [comment]
Yes please! Thanks.

**Comment by kiwionly2** [comment]
PR created as #635.

**Comment by huanghua78** [comment]
https://github.com/Seagate/cortx-motr/pull/635 is merged.
Please verify and close this issue.
