### ISSUE TITLE
hsm: space is not freed on composite object removal

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#482]
It looks like the space in not freed in the pool on the composite object removal. (While the normal object removal frees the space OK.) This has to be re-checked...

Steps to reproduce:
1. Create a composite object via the hsm utility (see its help on how to do this).
2. Write some data to the object.
3. Delete the object.

Check the consumed space via `hctl status --json | jq '.filesystem'` 1) before the object was written, 2) after it was written and 3) after the deletion and make sure the space is freed after the deletion.

**Comment by nkommuri** [comment]
@andriytk , can you please provide reproduction steps. thanks.

**Comment by andriytk** [comment]
@nkommuri, please see in the updated description above. Thanks.

**Comment by r-wambui** [comment]
@nkommuri Please update if you were able to reproduce the issue.

**Comment by chandradharraval** [comment]
Hi @andriytk , @johnbent ,
Is this still valid issue and need to be fixed?

**Comment by andriytk** [comment]
Still valid, i'm afraid.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed as the same is not targeted for alpha release. If required the same can be reopened or tracked via story ticket in future
