### ISSUE TITLE
./scripts/install-build-deps errors

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#492]
[root@ssc-vm-1401 cortx-motr]# ./scripts/install-build-deps
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, subscription-manager
EOS_EPEL-7_EPEL-7                                                                                                    | 2.5 kB  00:00:00
EOS_Puppet6_puppet6-el7                                                                                              | 2.1 kB  00:00:00
epel/x86_64/metalink                                                                                                 |  15 kB  00:00:00
epel                                                                                                                 | 4.7 kB  00:00:00
(1/3): epel/x86_64/group_gz                                                                                          |  95 kB  00:00:00
(2/3): epel/x86_64/updateinfo                                                                                        | 1.0 MB  00:00:01
(3/3): epel/x86_64/primary_db                                                                                        | 6.9 MB  00:00:02
Resolving Dependencies
--> Running transaction check
---> Package ansible.noarch 0:2.9.18-1.el7 will be installed
--> Processing Dependency: python-httplib2 for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python-paramiko for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python2-cryptography for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python2-jmespath for package: ansible-2.9.18-1.el7.noarch
--> Running transaction check
---> Package ansible.noarch 0:2.9.18-1.el7 will be installed
--> Processing Dependency: python2-cryptography for package: ansible-2.9.18-1.el7.noarch
---> Package python-paramiko.noarch 0:2.1.1-0.10.el7 will be installed
--> Processing Dependency: python2-pyasn1 for package: python-paramiko-2.1.1-0.10.el7.noarch
--> Processing Dependency: python-cryptography for package: python-paramiko-2.1.1-0.10.el7.noarch
---> Package python2-httplib2.noarch 0:0.18.1-3.el7 will be installed
---> Package python2-jmespath.noarch 0:0.9.4-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: python-paramiko-2.1.1-0.10.el7.noarch (EOS_EPEL-7_EPEL-7)
           Requires: python2-pyasn1
Error: Package: python-paramiko-2.1.1-0.10.el7.noarch (EOS_EPEL-7_EPEL-7)
           Requires: python-cryptography
Error: Package: ansible-2.9.18-1.el7.noarch (epel)
           Requires: python2-cryptography
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Uploading Enabled Repositories Report
Loaded plugins: product-id, subscription-manager
[root@ssc-vm-1401 cortx-motr]# python --version
Python 2.7.5
[root@ssc-vm-1401 cortx-motr]# git --version
git version 1.8.3.1
[root@ssc-vm-1401 cortx-motr]# uname -r
3.10.0-1062.el7.x86_64

**Comment by hessio** [comment]
Hi @yanqingfu - I am currently working on reproducing this issue. I will update you once I have my system setup. It looks as though you have the correct system settings.

**Comment by hessio** [comment]
Hi @yanqingfu - I have setup Motr following the guide and unfortunately (or fortunately depending on how you look at it) wasn't able to recreate your error. Would you like to get on a call to go through the setup? My email: [patrick.hession@seagate.com](mailto:patrick.hession@seagate.com) if you would like to do this.

**Comment by yanqingfu** [comment]
Hi @hessio I followed exactly as in https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst. I think my VM got messed up somehow. I have no problems when I use a new VM.

**Comment by hessio** [comment]
Hi @yanqingfu oh this is great news. Glad you got it working!
