### ISSUE TITLE
motr system test 24motr-dix-repair get_during,: command not found

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#524]
----------- Start to exec get_during, -------------
/var/cortx/cortx-motr/dix/cm/st/dix_repair_st.sh: line 513: get_during,: command not found
------------ Completed get_during, -----------------
Failed: get_during,
/var/cortx/cortx-motr/dix/cm/st/dix_repair_st.sh: line 602: echo test cases failed: command not found
=== pids of services: 62052 62045 62039 62035 61921 61803 60997 ===
Shutting down services one by one. mdservice is the last.
----- 62052 stopping------------- 62052 stopped --------
----- 62045 stopping------------- 62045 stopped --------
----- 62039 stopping------------- 62039 stopped --------
----- 62035 stopping------------- 62035 stopped --------
----- 61921 stopping------------- 61921 stopped --------
----- 61803 stopping------------- 61803 stopped --------
----- 60997 stopping------------- 60997 stopped --------
m0tr                13967805  0
galois                 22944  1 m0tr
lnet                  590949  3 m0tr,ksocklnd
Test log available at /var/motr/root/sandbox.st-24motr-dix-repair/motr_2021-03-20_08:41:49.log.
dix-repair-st: FAILURE 127
73.58user 15.99system 3:01.71elapsed 49%CPU (0avgtext+0avgdata 502884maxresident)k
2032inputs+5495832outputs (207major+2575467minor)pagefaults 0swaps

[24motr-dix-repair_failure.txt](https://github.com/Seagate/cortx-motr/files/6175810/24motr-dix-repair_failure.txt)

**Comment by justinzw** [comment]
Thanks @yanqingfu just to check. 

You are running this command `/var/cortx/cortx-motr/dix/cm/st/dix_repair_st.sh` on a pre-built CORTX VM right?

**Comment by yanqingfu** [comment]
@justinzw, nope, I build motr from  source, just as https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst

**Comment by hessio** [comment]
Hi @yanqingfu where did you get this script? What is the purpose of this script? I am just trying to get a better understanding of this issue.

**Comment by hessio** [comment]
Hi @yanqingfu where did you get this script? What is the purpose of this script? I am just trying to get a better understanding of this issue.

**Comment by yanqingfu** [comment]
@hessio, if you run `./scripts/m0 run-st -l` you will get the following system test list. Instead of running '`./scripts/m0 run-st', I just run one by one to see what is going on for each system test.

> [root@ssc-vm-2736 cortx-motr]# ./scripts/m0 run-st -l
> ----- run_st -l -----
> 01net
> 02rpcping
> 03console
> 04sss
> 05confgen
> 06conf
> 06hagen
> 06ham
> 07m0d-fatal
> 07mount
> 07mount-fail
> 08spiel
> 08spiel-multiple-confd
> 08spiel-sns-repair
> 08spiel-sns-repair-quiesce
> 10pver-assign
> 11m0t1fs
> 11m0t1fs-rconfc-fail
> 12fsync
> 12fwait
> 13dgmode-io
> 14poolmach
> 15sns-repair-shutdown
> 15sns-repair-single
> 16sns-repair-multi
> 17sns-repair-concurrent-io
> 18sns-repair-quiesce
> 18sns-repair-quiesce-failure
> 19sns-repair-abort
> 20rpc-session-cancel
> 21fsync-single-node
> 22sns-repair-ios-fail
> 23sns-abort-quiesce
> 23spiel-dix-repair
> 23spiel-dix-repair-quiesce
> 24motr-dix-repair
> 24stob-domain-recreate-on-corruption
> 25m0kv
> 26motr-user-kernel-tests
> 34sns-repair-1n-1f
> 40motr-dgmode
> 41motr-conf-update
> 42motr-utils
> 43m0crate
> 44motr-rm-lock-cc-io
> 45motr-rmw
> 51kem
> 52motr-singlenode-sanity
> 53clusterusage-alert
> 60sns-repair-motr-1f
> 61sns-repair-motr-1n-1f
> 62sns-repair-motr-mf
> 63sns-repair-motr-1k-1f
> 64sns-repair-motr-ios-fail
> 65sns-repair-motr-abort
> 66sns-repair-motr-abort-quiesce

**Comment by hessio** [comment]
Oh I see this makes sense. Can you send me this log file: `/var/motr/root/sandbox.st-24motr-dix-repair/motr_2021-03-20_08:41:49.log` ?

**Comment by yanqingfu** [comment]
@hessio I think I found the root cause in https://github.com/Seagate/cortx-motr/blob/main/dix/cm/st/dix_repair_st.sh
`if [ ${#tests_list[@]} -eq 0 ]; then
	declare -a tests_list=(
				lookup
				insert
				get_during,
				drop_during,
				put_during,
				del_repair,
				del_rebalance
			)
fi

echo "We are going to test: ${tests_list[@]}"`

we should remove the ',' of 

get_during,
drop_during,
put_during,
del_repair,

after removing commas, new issue comes up, drop_during failed : 
[24motr-dix-repair_failure.txt](https://github.com/Seagate/cortx-motr/files/6183792/24motr-dix-repair_failure.txt)

I didn't see motr_2021-03-20_08:41:49.log in the folder /var/motr/root/sandbox.st-24motr-dix-repair, I see many trace file, but don't know which one is the one 

[root@ssc-vm-2736 sandbox.st-24motr-dix-repair]# ls
confd                m0trace.67350  m0trace.68744  m0trace.70171  m0trace.71565  m0trace.72964  m0trace.74371  m0trace.75767  m0trace.77166
fids.txt             m0trace.67427  m0trace.68821  m0trace.70248  m0trace.71642  m0trace.73041  m0trace.74448  m0trace.75858  m0trace.77377
ha                   m0trace.67504  m0trace.68898  m0trace.70325  m0trace.71719  m0trace.73132  m0trace.74525  m0trace.75935  m0trace.77454
ios1                 m0trace.67581  m0trace.69107  m0trace.70402  m0trace.71796  m0trace.73209  m0trace.74734  m0trace.76012  m0trace.77531
ios2                 m0trace.67672  m0trace.69184  m0trace.70479  m0trace.72007  m0trace.73286  m0trace.74811  m0trace.76089  m0trace.77608
ios3                 m0trace.67749  m0trace.69261  m0trace.70570  m0trace.72084  m0trace.73363  m0trace.74888  m0trace.76166  m0trace.77685
ios4                 m0trace.67826  m0trace.69338  m0trace.70647  m0trace.72161  m0trace.73440  m0trace.74965  m0trace.76375  m0trace.77767
keys.txt             m0trace.67903  m0trace.69417  m0trace.70726  m0trace.72238  m0trace.73649  m0trace.75042  m0trace.76452  mds1
m0kv_st.cod.log      m0trace.67980  m0trace.69499  m0trace.70803  m0trace.72315  m0trace.73726  m0trace.75124  m0trace.76529  vals.txt
m0kv_st.ecod.log     m0trace.68189  m0trace.69590  m0trace.70880  m0trace.72397  m0trace.73803  m0trace.75208  m0trace.76608
m0kv_st.log          m0trace.68268  m0trace.69671  m0trace.71089  m0trace.72479  m0trace.73882  m0trace.75291  m0trace.76685
m0kv_st.results.log  m0trace.68345  m0trace.69752  m0trace.71166  m0trace.72562  m0trace.73959  m0trace.75370  m0trace.76767
m0trace.67022        m0trace.68422  m0trace.69833  m0trace.71243  m0trace.72646  m0trace.74041  m0trace.75459  m0trace.76858
m0trace.67105        m0trace.68499  m0trace.69914  m0trace.71320  m0trace.72733  m0trace.74123  m0trace.75536  m0trace.76935
m0trace.67186        m0trace.68590  m0trace.70000  m0trace.71397  m0trace.72810  m0trace.74215  m0trace.75613  m0trace.77012
m0trace.67273        m0trace.68667  m0trace.70084  m0trace.71488  m0trace.72887  m0trace.74294  m0trace.75690  m0trace.77089

**Comment by hessio** [comment]
I am sure it says in that file you attached to check that log file I asked for. So I am not too sure. We will keep looking at the code for now.

**Comment by yanqingfu** [comment]
@hessio, yeah, it said to check that log file. I also use` find -name` to search that file but shows nothing, which means we don't save it and might be a bug.

**Comment by yanqingfu** [comment]
root cause was found /var/cortx/cortx-motr/dix/cm/st/dix_repair_st.sh: line 513: get_during,: command not found.
close this and open other issues:  https://github.com/Seagate/cortx-motr/issues/530; https://github.com/Seagate/cortx-motr/issues/531

**Comment by huanghua78** [comment]
Please note, only the first two sub test cases are enabled. Please refer to:

```
636   - id       : 62dix-repair-st-lookup-insert
637     script   : dix_repair_st.sh -v lookup insert
638     dir      : src/dix/cm/st/
639     executor : Xperior::Executor::MotrTest
640     sandbox  : /var/mero/sandbox.62dix-repair-st
641     polltime : 30
642     timeout  : 1800
```

Other sub test cases may fail at this moment. This is known issue.

**Comment by yanqingfu** [comment]
@huanghua78 didn't see your quote in here: https://github.com/Seagate/cortx-motr/blob/dev/.xperior/testds/motr-single_tests.yaml
