### ISSUE TITLE
motr system test 24stob-domain-recreate-on-corruption confd/addb-stobs: No such file or directory

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#525]
[root@ssc-vm-2736 cortx-motr]# ./scripts/m0 run-st 24stob-domain-recreate-on-corruption
----- run_st 24stob-domain-recreate-on-corruption -----
<< 24stob-domain-recreate-on-corruption >>
Prepare
mkfs
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -D /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/db -T AD -S /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/addb-stobs -e lnet:192.168.63.62@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/conf.txt -w 3 -f <0x7200000000000001:0>
mkfs (truncate addb-stobs id file)
/var/cortx/cortx-motr/st/stob_domain_recreate_on_corruption.sh: line 133: cd: confd/addb-stobs: No such file or directory
stob-domain-recreate-on-corruption: FAILURE 1
1.75user 0.65system 0:02.67elapsed 90%CPU (0avgtext+0avgdata 373360maxresident)k
560inputs+300504outputs (6major+68220minor)pagefaults 0swaps

**Comment by justinzw** [comment]
Thanks @yanqingfu for reporting this. Just to clarify - are you running this on a pre-built VM and is it 1.0.2?

**Comment by yanqingfu** [comment]
@justinzw, nope, I build motr from  source, just as https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst

**Comment by johnbent** [comment]
@justinzw , can you please try to reproduce this and let @huanghua78  and @mukundkanekar know if you are able to successfully reproduce this and cannot yourself debug it?

**Comment by yanqingfu** [comment]
new release seems ok

[root@ssc-vm-2736 cortx-motr]#  ./scripts/m0 run-st 24stob-domain-recreate-on-corruption
----- run_st 24stob-domain-recreate-on-corruption -----
<< 24stob-domain-recreate-on-corruption >>
Prepare
mkfs
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -D /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/db -T AD -S /var/mot           r/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-24stob-domain-recreate-on-           corruption/confd/addb-stobs -e lnet:192.168.63.62@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-24stob-domain-recrea           te-on-corruption/confd/conf.txt -w 3 -f <0x7200000000000001:0>
mkfs (truncate stobs id file)
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -D /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/db -T AD -S /var/mot           r/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-24stob-domain-recreate-on-           corruption/confd/addb-stobs -e lnet:192.168.63.62@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-24stob-domain-recrea           te-on-corruption/confd/conf.txt -w 3 -f <0x7200000000000001:0>
motr[130827]:  d290  ERROR  [stob/linux.c:183:stob_linux_domain_key_get_set]  <! rc=-22 path=/var/motr/root/sandbox.st-24stob-domain           -recreate-on-corruption/confd/stobs
mkfs force
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -D /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/db -T AD -S /var/           motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-24stob-domain-recreate-           on-corruption/confd/addb-stobs -e lnet:192.168.63.62@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-24stob-domain-rec           reate-on-corruption/confd/conf.txt -w 3 -f <0x7200000000000001:0>
mkfs force (truncate stobs id file)
/var/cortx/cortx-motr/utils/mkfs/m0mkfs -F -D /var/motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/db -T AD -S /var/           motr/root/sandbox.st-24stob-domain-recreate-on-corruption/confd/stobs -A linuxstob:/var/motr/root/sandbox.st-24stob-domain-recreate-           on-corruption/confd/addb-stobs -e lnet:192.168.63.62@tcp:12345:34:1001 -m 163840 -q 2 -c /var/motr/root/sandbox.st-24stob-domain-rec           reate-on-corruption/confd/conf.txt -w 3 -f <0x7200000000000001:0>
motr[131054]:  9060  ERROR  [stob/linux.c:183:stob_linux_domain_key_get_set]  <! rc=-22 path=/var/motr/root/sandbox.st-24stob-domain           -recreate-on-corruption/confd/stobs
Stop
stob-domain-recreate-on-corruption: test status: SUCCESS
6.60user 1.74system 0:07.84elapsed 106%CPU (0avgtext+0avgdata 376996maxresident)k
80inputs+939808outputs (14major+208356minor)pagefaults 0swaps
