### ISSUE TITLE
motr system test 24motr-dix-repair test log file not found in the indicated folder

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#530]
![image](https://user-images.githubusercontent.com/68423216/112076128-c7f49080-8bb4-11eb-99b6-514897bf2410.png)

**Comment by huanghua78** [comment]
Because error messages have already shown on console. They are not re-directed to the log file.

Some of the error messages are directly shown to stdout/stderr. Some are also saved to log file.
In this case, no error messages are re-directed to log file.

We can remove this line:
```
diff --git a/dix/cm/st/dix_repair_st.sh b/dix/cm/st/dix_repair_st.sh
index 9e13540b..c1b8fdf5 100755
--- a/dix/cm/st/dix_repair_st.sh
+++ b/dix/cm/st/dix_repair_st.sh
@@ -603,8 +603,6 @@ main() {
        stop
        if [ $rc -eq 0 ]; then
                sandbox_fini
-       else
-               echo "Test log available at $MOTR_TEST_LOGFILE."
        fi
        report_and_exit dix-repair-st $rc
 }

```
Or enhance the test script to re-direct some of the error messages also to this log file.

**Comment by huanghua78** [comment]
For example, the following patch can re-direct messages to log files, too.
```
diff --git a/dix/cm/st/dix_repair_st.sh b/dix/cm/st/dix_repair_st.sh
index 9e13540b..8a3c4cc2 100755
--- a/dix/cm/st/dix_repair_st.sh
+++ b/dix/cm/st/dix_repair_st.sh
@@ -597,7 +597,7 @@ main() {
        start
        rc=$?
        [ $rc != 0 ] && return $rc
-       execute_tests
+       execute_tests | tee -a $MOTR_TEST_LOGFILE
        rc=$?
        [ $rc != 0 ] && "echo test cases failed"

```

**Comment by r-wambui** [comment]
@huanghua78 Could you please update on the status of this? Were the patches you suggested earlier implemented? If so should we close this issue?

**Comment by huanghua78** [comment]
@r-wambui it has not been fixed.

**Comment by cortx-admin** [comment]
> Zoheb Khan commented in Jira Server:

I ran the dix_repair_st.sh and it failed as shown below, The log file could not be found at the given location. *This needs to be fixed.*
{noformat}
[root@i1u06-m07 st]# ./dix_repair_st.sh --no-setup all
Device "eth1" does not exist.
Device "eth1" does not exist.
We are going to test: all
Device "eth1" does not exist.
SPIEL_OPTS= -l /cortx-motr/dix/cm/st/../../..//motr/.libs/libmotr.so --client @tcp:12345:34:1001 --ha @tcp:12345:34:1
SPIEL_FIDS_LIST= fids = {'profile' : Fid(0x7000000000000001, 0), 'pool' : Fid(0x6f00000000000014, 1), 'ios' : Fid(0x7300000000000001, 3), 'process' : Fid(0x7200000000000001, 7), }
/var/motr/sandbox.dix-repair-st
*** m0dixinit is omitted. Mkfs creates meta indices now.
Device "eth1" does not exist.
motr[67529]:  72f0  ERROR  [net/libfab/libfab.c:461:libfab_ep_addr_decode_sock]  <! rc=-22
motr[67529]:  7380  ERROR  [net/libfab/libfab.c:2570:libfab_txep_init]  <! rc=-61
motr[67529]:  7490  ERROR  [net/libfab/libfab.c:1547:libfab_passive_ep_create]
 libfab_tm_res_init = -61motr[67529]:  7490  ERROR  [net/libfab/libfab.c:1549:libfab_passive_ep_create]  <! rc=-61
motr[67529]:  7490  ERROR  [net/libfab/libfab.c:3150:libfab_ma_start]  <! rc=-61
motr[67529]:  7700  ERROR  [rpc/rpc_machine.c:513:rpc_tm_setup]  <! rc=-61 TM start
motr[67529]:  7700  ERROR  [rpc/rpc_machine.c:173:m0_rpc_machine_init]  <! rc=-61
Initialization error -61
Got error -61
Done, rc:  61
Motr CmdLine utility returned 61!
Failed to init test 1
./dix_repair_st.sh: line 602: echo test cases failed: command not found
/var/motr/sandbox.dix-repair-st
Test log available at /var/motr/sandbox.dix-repair-st/motr_2021-12-17_04:21:07.log.
dix-repair-st: FAILURE 1
--------------------------------------------------------------------------------------------------
[root@i1u06-m07 st]# cd /var/motr/sandbox.dix-repair-st
[root@i1u06-m07 sandbox.dix-repair-st]# ll
total 16448
-rwx------ 1 root root 16842752 Dec 17 04:21 m0trace.67529
[root@i1u06-m07 sandbox.dix-repair-st]# find /var/motr/ -name motr_2021-12-17_04:21:07.log
[root@i1u06-m07 sandbox.dix-repair-st]#
[root@i1u06-m07 sandbox.dix-repair-st]#
[root@i1u06-m07 sandbox.dix-repair-st]# ll
total 16448
[root@i1u06-m07 sandbox.dix-repair-st]# cat /var/motr/sandbox.dix-repair-st/motr_2021-12-17_04:21:07.log
cat: /var/motr/sandbox.dix-repair-st/motr_2021-12-17_04:21:07.log: No such file or directory
[root@i1u06-m07 sandbox.dix-repair-st]#

{noformat}

**Comment by cortx-admin** [comment]
> Sanjog Vikram Naik commented in Jira Server:

Started PR [CORTX-23743: Add logging for DIX repair tests by sanjognaik · Pull Request #1530|https://github.com/Seagate/cortx-motr/pull/1530]

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. motr - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: sanjog.naik
* Component Build  :  5039 
* Release Build    :  5176  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/rockylinux-8.4/5176 

h3. Image Location  :  
*  cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5176
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5176
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5176
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-5176 
{panel}

**Comment by cortx-admin** [comment]
> Sanjog Vikram Naik commented in Jira Server:

PR [CORTX-23743: Add logging for DIX repair tests by sanjognaik · Pull Request #1530|https://github.com/Seagate/cortx-motr/pull/1530] is approved and merged.

**Comment by cortx-admin** [comment]
> Sanjog Vikram Naik commented in Jira Server:

It is verified that, in case of ST failure, messages are getting logged in log file.
