### ISSUE TITLE
motr system test 24motr-dix-repair drop_during failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#531]
![image](https://user-images.githubusercontent.com/68423216/112076307-2ae62780-8bb5-11eb-84c1-567b38aa738e.png)

https://github.com/Seagate/cortx-motr/issues/524

https://github.com/Seagate/cortx-motr/issues/530

**Comment by huanghua78** [comment]
Now, this test case is disabled. It is not ready.
