### ISSUE TITLE
Clang static analyzer report

### ISSUE THREAD

**Issue by pasis** [Seagate/cortx-motr#545]
Hello, I've run Motr through clang analyzer and attached the report in case you're interested in looking over the list. Majority of the "bugs" are false positive, however, some highlights may be interesting.

Feel free to close this ticket.

[scan-build-2021-03-27-182904-19485-1.zip](https://github.com/Seagate/cortx-motr/files/6215855/scan-build-2021-03-27-182904-19485-1.zip)

**Comment by johnbent** [comment]
@huanghua78 and @nikitadanilov , should we assign someone to look into this clang report?  @pasis , thanks!

**Comment by johnbent** [comment]
@huanghua78 and @mukundkanekar can you either assign this to someone or close this if it isn't useful?  Thanks @pasis .

**Comment by mehjoshi** [comment]
Thank you @pasis and sorry for the delay in getting back on this.
I looked at the scan reports. I do not know how to look at it very well so I went through the index and picked a few of each of the Bug Types. Below, I list them and a few of my findings:

1) 'Uninitialized argument value':
	I ignored most of the errors in this category as they are in some or the other UTs.
    However, I looked at the following error from the report in utils/layout/m0layout.c:layout_demo()
		d = classify(pl, map[frame][obj].sa_unit);

Here, it looks like the function classify() is returning an array which is being indexed later. So, clearly the analyzer software
cannot determine the right number of values returned.

2) 'Logic error' result of operation is garbage or undefined:
	1) cas/client.c	nreq_asmbl_prep	826
	   This is indeed a bug! A bug ticket has been logged for this to be tracked internally.
	
	2) hsm/m0hsm.c	shell_loop	668
	   This is a false positive. The value of argc is expected to be populated by the function being called just above.
		argv = sh_split_line(line, &argc);
	 
		if (argc > 1) {
	3) conf/db.c	confx_obj_dup	243
		This is a false positive.
		
	4) motr/io_pargrp.c	pargrp_iomap_populate	690
		This is a false positive.
	
	5) conf/helpers.c	m0_conf_confc_ha_update_async	655
		This one looks like a potential bug. Not sure very sure if variable rc can be left unassigned here.
		Need to ask someone familiar to take a closer look.
	
	6) I looked at few others in this category which are not UT or ST and did not find anything serious. Still, it will be good to
	   go over the ST cases at least. I don't know if/when we can cover all of them. Let me see ..

3) Dead store	Dead assignment
    These can be ignored for now.

**Comment by mehjoshi** [comment]
@pasis , We haven't heard back from you on this, so I am going to go ahead and close it. Thanks!
