### ISSUE TITLE
Poor SNS-repair performance due to flaw in the permutation algorithm

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#572]
From Nachiket:

> I think this logic needs to be updated:

https://github.com/Seagate/cortx-motr/blob/05b719b85d806fa97e83adec4f3fea1245ab17e3/fd/fd.c#L919

> This is the original code where permutation caches are maintained based on length. This turned out to be a bad choice as it violates pdclust principle and leads to very poor repair performance. My fix for this shall be on gerrit where each node of failure domains tree maintains its own cache and caches are no longer maintained based on length.

See also https://jts.seagate.com/browse/MERO-2668

**Comment by johnbent** [comment]
This entire file (fd/df.c) looks like very complex code (where functions return the address of pointers and stuff like that for example) with almost zero documentation.  Except for one very nice comment from Nachiket.  @andriytk and @nikitadanilov and @huanghua78 .  I can't find Nachiket's github ID.

**Comment by andriytk** [comment]
@johnbent here is the design doc of failure domains - https://seagatetechnology.sharepoint.com/:w:/s/gteamdrv1/tdrive1224/EYXh5mOopIlPlD9hGyQ2ZBoBN3Q5KJnWW7R2Km7WQZpMVg. Please check with our tech writers if it can be converted to pdf and published here on github.

**Comment by johnbent** [comment]
Thanks @andriytk .  This looks awesome.  @Saumya-Sunder , please convert to markdown and link it somewhere in motr.  Andriy, did you also see my confluence page about failure domains: [https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/27164675/CORTX+Hierarchical+Failure+Domains.](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/27164675/CORTX+Hierarchical+Failure+Domains.)  It's also not accessible to our community yet.  But we are working to publish those pages soon!

**Comment by Saumya-Sunder** [comment]
Just a quick question @andriytk, I see several greyed out instances of the text [equation]. Do I mention as is or was it meant to be a placeholder for the actual equation?

**Comment by andriytk** [comment]
@Saumya-Sunder give it some time, it will render into the actual equations. Microsoft...

**Comment by Saumya-Sunder** [comment]
Sure @andriytk , just let me know once you are done.

**Comment by andriytk** [comment]
@Saumya-Sunder I don't work on the doc. I meant to give it some time until the page is loaded in your browser and the equations are rendered so you can see them.

**Comment by Saumya-Sunder** [comment]
Oh yeah, saw them rendered now. Thanks @andriytk .

**Comment by nkommuri** [comment]
@andriytk  please let us know the current status of  PR? Can we apply this patch as it is or needs to be revisited? thanks.

**Comment by andriytk** [comment]
As far as I remember, the UT still has to be fixed/updated for this patch. Unfortunately, I don't have very much time to spare on it, so it will be good if someone from Motr team could pick it up.

**Comment by r-wambui** [comment]
@andriytk @nikitadanilov I'm in the process on clearing the backlog on the issues,  any update on this, has this been assigned to anyone on the Mort team?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~520414],

Can you share link of the PR which is mentioned in earlier comments([https://github.com/Seagate/cortx-motr/pull/576] ??)? I understand we still need to fix some UT over and above this PR.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~520414],

Can you comment on my above query?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Adding it under F-56D which will be picked up in future PI based on roadmap plan

**Comment by nkommuri** [comment]
Closing Github issue. Will be addressed through story. https://jts.seagate.com/browse/CORTX-23744
