### ISSUE TITLE
Bucket Listing Can Silently Fail

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#609]
Thanks to @RodDaSilvaWCO for finding a reporting a bug where buckets can incorrectly appear empty.  The team is hard at work creating a more permanent fix (which only affects the released Virtual Machine by the way and not Lyve Rack).  In the meantime, here is a workaround:

1) Edit file /opt/seagate/cortx/s3/conf/s3config.yaml by changing the option S3\_MOTR\_MAX\_IDX\_FETCH\_COUNT value to 10 from 30

    S3\_MOTR\_MAX\_IDX\_FETCH\_COUNT: 10

2) After editing s3config.yaml file, restart s3server instance

    systemctl restart s3server@0x7200000000000001:0x16

   s3server will load the changed option from s3config.yaml

**Comment by mukul-seagate11** [comment]
@yeshpal-jain-seagate, please address the issue reported

**Comment by nkommuri** [comment]
@johnbent   since we have workaround and a separate JIRA issue ( https://jts.seagate.com/browse/EOS-19702) is created to handle actual fix, shall we close this Github issue? Thanks.

**Comment by johnbent** [comment]
Thanks @nkommuri . Should we close it now or should we wait until that JIRA issue is closed?

**Comment by nkommuri** [comment]
@johnbent , ok lets keep this open until the actual issue is fixed.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Resolved based on above comments and assigning back to reporter for further closure

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

we documented a workaround so we can close this
