### ISSUE TITLE
Unit test fail cause by file not found.

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#620]
Hi all, 

I am manually build cortx-motr on Seagate Self Service cloud. ( CentOS 7.8 )

So far the build is ok, some how when I run unit test 
```
$ sudo ./scripts/m0 run-ut
```

It had fail with following error 

```
----- run_ut -----
/usr/bin/ld: cannot open output file /home/502380/cortx-motr/ut/.libs/11198-lt-m
0ut: Permission denied
```

![image](https://user-images.githubusercontent.com/77140436/116859071-fa70bf00-ac31-11eb-8313-b75b326e3f5a.png)

I had check the listed directory and that is no such file **11198-lt-m** 

Any idea ?

**Comment by yanqingfu** [comment]
https://github.com/Seagate/cortx-motr/issues/549

**Comment by kiwionly2** [comment]
close because of duplicate issue #549
