### ISSUE TITLE
 lctl list_nids not show ip address when setup

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#636]
Hi all, 

I am setup motr using seagate self service cloud. 

While try to setup lnet, it seem like nothing show (it should show an IP address ) even I had follow documentation for troubleshoot.

![image](https://user-images.githubusercontent.com/77140436/117143600-97268e80-ade3-11eb-9c76-90b03a52df93.png)

any idea ?

**Comment by hessio** [comment]
Hi @kiwionly2 can you run `ip a` and show the output of this, you need to use an iface name from this list.

**Comment by hessio** [comment]
Hi @kiwionly2 - I logged into the system and fixed this issue for you. Here is the output of the `history` so you can see the commands I executed.  
  
 `132 lctl list_nids`  
 `133  cat /etc/modprobe.d/lnet.conf`  
 `134  vi /etc/modprobe.d/lnet.conf`  
 `135  sudo systemctl restart lnet`  
 `136  sudo lctl list_nids`  
 `137  modprobe lnet`  
 `138  sudo lctl list_nids`  
 `139  vi /etc/modprobe.d/lnet.conf`  
 `140  modprobe lnet`  
 `141   lctl list_nids`  
 `142  ip a`  
 `143  cat /etc/modprobe.d/lnet.conf`  
 `144  systemctl restart lnet`  
 `145   lctl list_nids`  
 `146  sudo lctl list_nids`  
 `147  sudo rmmod lnet`  
 `148* sudo rmmod k lnet`  
 `149  sudo rmmod ksocklnd lnet_selftest lnet`  
 `150  systemctl stop lnet`  
 `151  systemctl status lnet`  
 `152  systemctl start lnet`  
 `153  sudo rmmod lnet`  
 `154  sudo rmmod ksocklnd lnet`  
 `155   lctl list_nids`  
 `156  history`  
 I knew to try these commands from this discussion: [https://github.com/Seagate/cortx-motr/discussions/598](https://github.com/Seagate/cortx-motr/discussions/598)  
Please let me know if you have anymore issues/questions.

**Comment by kiwionly2** [comment]
Thanks @hessio, yes, it work now.
