### ISSUE TITLE
Reset state when unit test fail

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#639]
Hi, I am running various unit test for motr in Seagate self service cloud.

When the test fail and I want to rerun, it show error below :

![image](https://user-images.githubusercontent.com/77140436/117270720-166f9d00-ae8c-11eb-81f7-32df6cb0510c.png)

Is any way to reset the state for retest ?

**Comment by hessio** [comment]
Hi @kiwionly2 what do you mean by reset state? State of the VM?

**Comment by yanqingfu** [comment]
https://github.com/Seagate/cortx/blob/main/doc/Build-Installation-FAQ.md refer Qs3

**Comment by kiwionly2** [comment]
@hessio  Just to reset everything related to test so the test could rerun again.

I had follow the Qs3 but seem like no luck, I reboot the system and now it running fine.
