### ISSUE TITLE
System test fail on 07mount

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#641]
Hi, 

I am running system test after build success. However, it fail when running test case 07mount.  I try to reboot couple of time and run it but seem like no luck.

Is that any prerequisite for the test ? I am running in Seagate self service cloud.

![image](https://user-images.githubusercontent.com/77140436/117394392-a9f6ab80-af28-11eb-9aa4-c948b1546524.png)

*I need reboot to run test again due to the cleanup of module seem like not working properly.

![image](https://user-images.githubusercontent.com/77140436/117394810-6ea8ac80-af29-11eb-8797-210b6d868137.png)

**Comment by kimika88** [comment]
I have the same error

**Comment by justinzw** [comment]
ok, I will work on reproducing. Thank you for reporting this @kimika88 and stay tuned for an update.

**Comment by r-wambui** [comment]
@justinzw could you please update if this still exists? @kiwionly2 the #1173 that you raised in while working on the current issue was resolved and closed. Are you in a position to retest this and confirm if this issue is resolved?

**Comment by kiwionly2** [comment]
@r-wambui 

I pull the latest code, build and rerun again, issue #1173 no longer exist.

However I encounter other error caused by rerun system test after my terminal lose connection when running system test.

![image](https://user-images.githubusercontent.com/77140436/143383535-f7c57eed-20e2-4bdc-94a8-fe3457e69974.png)

Running `lsmod` show that this module is still in use by others process.

![image](https://user-images.githubusercontent.com/77140436/143383803-ee6c7067-9503-4a7c-b2f4-4884d6bdea52.png)


Even I had stop / start the SSC VM, but still no luck.

But is ok to close this issue if others was able to pass the test, because this probably is caused by my environment issue.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Closing as per the comment from reporter

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
