### ISSUE TITLE
./scripts/m0 run-st 03console error 

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#658]
[root@ssc-vm-2736 cortx-motr]#  ./scripts/m0 run-st 03console
----- run_st 03console -----
<< 03console >>
Running m0mkfs... OK
Service started
Console test fop, xcode input: connecting from 0@lo:12345:34:* to 0@lo:12345:34:1
connected
Console Address = 0@lo:12345:34:*
Server Address = 0@lo:12345:34:1
Sending FOP: 09 Console Test

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 22
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcd
Server replied with FOP: 08 Console Reply

        m0_cons_fop_reply
                cons_return(u32) = 0
                cons_notify_type(u32) = 9
OK
Console test fop, YAML input: connecting from 0@lo:12345:34:* to 0@lo:12345:34:1
connected
Console Address = 0@lo:12345:34:*
Server Address = 0@lo:12345:34:1

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 495
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Sending FOP: 09 Console Test

        m0_cons_fop_test
                cons_test_type(u8) = A
                cons_test_id(u64) = 495
                m0_cons_fop_fid
                        cons_seq(u64) = 144
                        cons_oid(u64) = 233
                m0_cons_fop_buf
                        cons_size(u32) = 5
                        cons_buf(u8) = abcde
Server replied with FOP: 08 Console Reply

        m0_cons_fop_reply
                cons_return(u32) = 0
                cons_notify_type(u32) = 9
OK
**/var/cortx/cortx-motr/console/st/console-st.sh: line 133:  5809 Terminated              $SERVER -v &>$SANDBOX_DIR/server.log**
console: test status: SUCCESS
2.81user 1.04system 0:04.19elapsed 91%CPU (0avgtext+0avgdata 377004maxresident)k
96inputs+399376outputs (10major+150819minor)pagefaults 0swaps

**Comment by hessio** [comment]
Hi @yanqingfu what is the error you are seeing here? Sorry I do not understand.

**Comment by yanqingfu** [comment]
@hessio  the test itself is not failing, but here is the error message

![image](https://user-images.githubusercontent.com/68423216/123421428-6696f000-d5ef-11eb-96be-922f4dee20ea.png)
