### ISSUE TITLE
m0composite shows confusing errors from dix_idxop_meta_update_ast_cb

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#661]
When `m0composite` runs the 1st time after the cluster is bootstrapped - there are no errors. But on the 2nd and subsequent runs it shows the errors:

```
$ m0composite "$CLIENT_LADDR" "$CLIENT_HA_ADDR" "$CLIENT_PROFILE" "$CLIENT_PROC_FID"
motr[26256]:  7bd0  ERROR  [dix/req.c:794:dix_idxop_meta_update_ast_cb]  All items are failed
motr[26256]:  5bd0  ERROR  [dix/req.c:794:dix_idxop_meta_update_ast_cb]  All items are failed
$ echo $?
0
```

Although, the command returns success status, the errors shown above are confusing.

Note: `m0composite` command must be run one time only after cluster bootstrap by design. But the next runs should return some user-friendly error msg explaining that the utility was already run and all is fine. Or there should be no errors at all. The above errors are confusing and meaningless to the user.

**Comment by nezzzu** [comment]
@huanghua78 Is it possible to assign this issue to someone?

**Comment by r-wambui** [comment]
@nkommuri @truptiatseagate Could you please update on the status of this? Has this been assigned to anyone?

**Comment by cortx-admin** [comment]
> Zoheb Khan commented in Jira Server:

I was able to reproduce this issue with the latest code. Below is the console output::

m0composite only ran successfully once after the cluster bootstrap and failed with the reported error on another attempt.

!image-2022-02-01-16-53-33-472.png!

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

As per bug scrub meeting, Marking this issue Closed with resolution as designed
