### ISSUE TITLE
m0_client_init() hangs during Maestro IO library tests.

### ISSUE THREAD

**Issue by siningwuseagate** [Seagate/cortx-motr#697]
Test platform: SAGE cluster at Juelich Supercomputer Centre
Test application: tests of Maestro IO library (`tests/mio_run_tests`): https://github.com/Seagate/cortx-mio
     
During the tests, a hang is observed with the following stack.                        
 ```
#0  0x00007fec15d7bb3b in do_futex_wait.constprop.1 () from /usr/lib64/libpthread.so.0
#1  0x00007fec15d7bbcf in __new_sem_wait_slow.constprop.0 () from /usr/lib64/libpthread.so.0
#2  0x00007fec15d7bc6b in sem_wait@@GLIBC_2.2.5 () from /usr/lib64/libpthread.so.0
#3  0x00007fec178cac54 in m0_semaphore_down (semaphore=0x7ffc8227a0e8) at lib/user_space/semaphore.c:62
#4  0x00007fec178bd5c5 in m0_chan_wait (link=link@entry=0x7ffc8227a0c0) at lib/chan.c:341
#5  0x00007fec17847a74 in m0_conf_objs_ha_update (nvec=nvec@entry=0x7ffc8227a200) at conf/helpers.c:576
#6  0x00007fec17847da8 in m0_conf_confc_ha_update_async (confc=<optimized out>, 
    nvec=nvec@entry=0x7ffc8227a200, chan=chan@entry=0x0) at conf/helpers.c:642
#7  0x00007fec17847e42 in m0_conf_confc_ha_update (confc=<optimized out>) at conf/helpers.c:663
#8  0x00007fec178e54fa in confc_init (m0c=0x149e260) at motr/client_init.c:946
#9  initlift_confc (mach=0x14a76e0) at motr/client_init.c:1015
#10 0x00007fec179588e2 in state_set (mach=0x14a76e0, state=5, rc=<optimized out>) at sm/sm.c:457
#11 0x00007fec178e63cc in initlift_move_next_floor (m0c=m0c@entry=0x149e260) at motr/client_init.c:371
#12 0x00007fec178e6b00 in m0_client_init (m0c_p=m0c_p@entry=0x7fec18121d48 <mio_motr_instance>, 
    conf=conf@entry=0x7fec18121bc0 <mio_motr_inst_conf>, init_m0=init_m0@entry=true)
    at motr/client_init.c:1576
#13 0x00007fec181159fe in mio_motr_init (mio_inst=<optimized out>) at src/driver_motr.c:162
#14 0x00007fec18113b1f in mio_init (yaml_conf=<optimized out>) at src/mio.c:917
#15 0x0000000000402539 in main (argc=<optimized out>, argv=0x7ffc8227a6f8) at examples/mio_copy.c:52
```                                              

lnet packet drops were observed during the test.  

After analysing the application and `hax`'s trace files, possible cause of the hang is:
(1) `m0_conf_objs_ha_update()` calls `m0_ha_state_get()` to send out HA request via `m0_ha_msg_nvec_send()` and `m0_ha_link_send()`.
(2) `m0_conf_objs_ha_update()` waits on `m0_chan_wait()` (no timeout). 
        And we notice that the`m0_motr_ha_ops::hao_msg_is_not_delivered`  is set to `motr_ha_msg_is_not_delivered_cb` which 
        is an empty function and does nothing. 
(3) if the HA msg is dropped for some reason, motr client knows nothing about it and still waits forever on the `chan`. This causes the hang.

**Comment by andriytk** [comment]
> if the HA msg is dropped for some reason, motr client knows nothing about it and still waits forever

I think HA messaging is based on rpc which do have re-transmissions. @max-seagate any idea?

**Comment by nkommuri** [comment]
Closing as there is no response. Please re-open if the issue still exists.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
