### ISSUE TITLE
cortx-motr 51kem missing x86_64 kernel/module

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#7]
why test status is still **SUCCESS**?

> [root@ssc-vm-0925 cortx-motr]# ./scripts/m0 run-st 51kem
> ----- run_st 51kem -----
> << 51kem >>
> make -C /lib/modules/3.10.0-1062.el7.x86_64/build M=/home/670951/cortx-motr/scripts/systemtap/kem modules
> make[1]: Entering directory `/usr/src/kernels/3.10.0-1062.el7.x86_64'
>   CC [M]  /home/670951/cortx-motr/scripts/systemtap/kem/kemd.o
>   Building modules, stage 2.
>   MODPOST 1 modules
>   CC      /home/670951/cortx-motr/scripts/systemtap/kem/kemd.mod.o
>   LD [M]  /home/670951/cortx-motr/scripts/systemtap/kem/kemd.ko
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-1062.el7.x86_64'
> Inserting kemd.ko
> Running Systemtap
> semantic error: while resolving probe point: identifier 'kernel' at /usr/share/systemtap/tapset/linux/memory.stp:68:8
>         source:                      kernel.function("__handle_mm_fault@mm/memory.c").call
>                                      ^
> 
> semantic error: missing x86_64 kernel/module debuginfo [man warning::debuginfo] under '/lib/modules/3.10.0-1062.el7.x86_64/build'
> 
> semantic error: while resolving probe point: identifier 'kernel' at :67:22
>         source: probe vm.pagefault = kernel.function("handle_mm_fault@mm/memory.c").call !,
>                                      ^
> 
> semantic error: missing x86_64 kernel/module debuginfo [man warning::debuginfo] under '/lib/modules/3.10.0-1062.el7.x86_64/build'
> 
> semantic error: while resolving probe point: identifier 'vm' at /home/670951/cortx-motr/scripts/systemtap/kem/kemd.stp:137:7
>         source: probe vm.pagefault {
>                       ^
> 
> semantic error: no match
> 
> Missing separate debuginfos, use: debuginfo-install kernel-3.10.0-1062.el7.x86_64
> Pass 2: analysis failed.  [man error::pass2]
> Number of similar error messages suppressed: 3.
> Rerun with -v to see them.
> Running KEM clients
> Collecting kernel events...
> Shutdown Systemtap
> /home/670951/cortx-motr/scripts/systemtap/kem/kem_run.sh: line 43: kill: (32613) - No such process
> Removing kemd.ko
> make -C /lib/modules/3.10.0-1062.el7.x86_64/build M=/home/670951/cortx-motr/scripts/systemtap/kem clean
> make[1]: Entering directory `/usr/src/kernels/3.10.0-1062.el7.x86_64'
>   CLEAN   /home/670951/cortx-motr/scripts/systemtap/kem/.tmp_versions
>   CLEAN   /home/670951/cortx-motr/scripts/systemtap/kem/Module.symvers
> make[1]: Leaving directory `/usr/src/kernels/3.10.0-1062.el7.x86_64'
> kem_run: test status: SUCCESS
> 121.88user 108.38system 1:17.40elapsed 297%CPU (0avgtext+0avgdata 314756maxresident)k
> 42800inputs+839600outputs (53major+1952793minor)pagefaults 0swaps
> [root@ssc-vm-0925 cortx-motr]# uname -r
> 3.10.0-1062.el7.x86_64
> [root@ssc-vm-0925 cortx-motr]# cd /lib/modules
> [root@ssc-vm-0925 modules]# ls
> 3.10.0-1062.9.1.el7.x86_64  3.10.0-1062.el7.x86_64
> [root@ssc-vm-0925 modules]# cd 3.10.0-1062.el7.x86_64
> [root@ssc-vm-0925 3.10.0-1062.el7.x86_64]# ls
> build   modules.alias      modules.builtin      modules.dep.bin  modules.modesetting  modules.softdep      source   weak-updates
> extra   modules.alias.bin  modules.builtin.bin  modules.devname  modules.networking   modules.symbols      updates
> kernel  modules.block      modules.dep          modules.drm      modules.order        modules.symbols.bin  vdso
> [root@ssc-vm-0925 3.10.0-1062.el7.x86_64]# cd build
> [root@ssc-vm-0925 build]# ls
> arch   crypto   firmware  include  ipc      kernel  Makefile        mm              net      scripts   sound       tools  virt
> block  drivers  fs        init     Kconfig  lib     Makefile.qlock  Module.symvers  samples  security  System.map  usr    vmlinux.id
> [root@ssc-vm-0925 build]# cd kernel
> [root@ssc-vm-0925 kernel]# ls
> bpf  debug   gcov  Kconfig.freezer  Kconfig.locks    livepatch  power  time
> cpu  events  irq   Kconfig.hz       Kconfig.preempt  Makefile   sched  trace

**Comment by huanghua78** [comment]
This test is obsolete.
