### ISSUE TITLE
panic() in 52singlenode-sanity

### ISSUE THREAD

**Issue by huanghua78** [Seagate/cortx-motr#738]
While doing testing for https://github.com/Seagate/cortx-motr/pull/671,
there is such a panic found: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/489/testReport/junit/01motr-single-node/52singlenode-sanity/

This is not caused by #671. It has been in "main".

Similar issue:
https://jts.seagate.com/browse/EOS-19130

**Comment by nkommuri** [comment]
Closing as the test passes without panic.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Test passed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Fixed

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Issue fixed
