### ISSUE TITLE
Broken / inaccessible links

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#74]
https://github.com/Seagate/cortx-motr/blob/main/doc/motr-design-doc-list.rst has a ton of really nice looking documents but the majority are 404 and the few that aren't 404 are pointing to internal Seagate docs.

@VenkyOS , can you please work to fix this?  For each missing doc, can you work with @huanghua78 and @nikitadanilov to find them please?  For each internal doc, can you migrate/convert them and fix the link please?

**Comment by VenkyOS** [comment]
@johnbent - I will work with @huanghua78 and @nikitadanilov

**Comment by VenkyOS** [comment]
This is WIP as part of the document conversion from SharePoint to RST.

**Comment by nkommuri** [comment]
Hi @VenkyOS , please close the ticker if requested work is done. Thanks.

**Comment by johnbent** [comment]
@nkommuri , @VenkyOS is no longer at Seagate. These tickets can be reassigned to @swatid-seagate. FYI @novium258

**Comment by r-wambui** [comment]
Hi @swatid-seagate @novium258 any updates on this? Swati have you managed to fix the links? If so could we please close this issue.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

This seems a huge task for verifying each link in the document.

Will connect with @huanghua78 for this sooner.

**Comment by nkommuri** [comment]
@madhavemuri shall we get rid off "Google Drive Link" Column from https://github.com/Seagate/cortx-motr/blob/main/doc/motr-design-doc-list.rst ? fyi, Google Drive Links are not working.

**Comment by johnbent** [comment]
Yes, good idea @nkommuri . @swatid-seagate can you do the needful please?

**Comment by chandradharraval** [comment]
HI @swanand-gadre ,
Any update on above comments from @johnbent ?

**Comment by johnbent** [comment]
Hey @chandradharraval , did you mean to tag @swatid-seagate not @swanand-gadre ?

**Comment by chandradharraval** [comment]
Hi @johnbent,
Yes thanks for catching, I have now corrected the same

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~935494] [~535110] 
it seems this ifixed?  What is next step?

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Started working on it. It needs to recreate the document.

**Comment by r-wambui** [comment]
Hi @swatid-seagate Any updates on this?

**Comment by chandradharraval** [comment]
Hi @swatid-seagate,
Is this covered under any of your recent PRs or we still have some more work to do here?

**Comment by swatid-seagate** [comment]
Hi @chandradharraval , its not covered under any PR. This document is in progress. Currently I am working on some other priority tasks.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

This job remains unsolved due to inadequate time.

**Comment by chandradharraval** [comment]
Hi @novium258,
Has Swati given any handover to anyone in team for work already completed for this issue?

**Comment by anaghadeshmukh** [comment]
> @madhavemuri shall we get rid off "Google Drive Link" Column from https://github.com/Seagate/cortx-motr/blob/main/doc/motr-design-doc-list.rst ? fyi, Google Drive Links are not working.

Should we also be removing Sharepoint links as that is internal to Seagate?

**Comment by nkommuri** [comment]
I think so.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~536285] [~535110]

Yes we should be removing anything that pointing to Google drive since it doesn't exist and any internal repositories that the Community cannot access :)
[~520423] [~934462] 
I have to believe whatever is in these docs surely is now on github?  Or some new version of them that is more relevant?  I am not sure how time consuming of a task it is to clean this up, but if it simple it seems like we should do it ?  :)

**Comment by cortx-admin** [comment]
> Pratik Patil commented in Jira Server:

Updated broken/ missing links in the motr-design-doc-list and converted it into md format

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~946307] [~936118]

So what do we do with this next?  I read this as the links have been addressed?

**Comment by cortx-admin** [comment]
> Mukund Bala Kanekar commented in Jira Server:

PR Link
[https://github.com/Seagate/cortx-motr/pull/2137]

[~946307] looks like 2 links are still broken, please refer my  comment in PR.

**Comment by cortx-admin** [comment]
> Mukund Bala Kanekar commented in Jira Server:

Approved PR as the 2 broken links are pointing to current doc, and will be fixed once PR is merged.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
