### ISSUE TITLE
Fail to build bindings/go for go 1.11 above

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#762]
When I try to build with go version 1.15.5 was fail and found out that **import** for [/cortx-motr/bindings/go/mkv/mkv.go](https://github.com/Seagate/cortx-motr/blob/main/bindings/go/mkv/mkv.go) should be 

`motr/mio`

instead of 

`../mio`

which `motr` refer from file [/cortx-motr/bindings/go/go.mod](https://github.com/Seagate/cortx-motr/blob/main/bindings/go/go.mod)

This is because of go 1.11 and above is [module aware](https://golang.org/ref/mod) by default.

@andriytk

**Comment by andriytk** [comment]
Thanks for noticing it. See https://github.com/Seagate/cortx-motr/pull/764.
