### ISSUE TITLE
motr unit tests reports memory leaks

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-motr#77]
[ut.txt](https://github.com/Seagate/cortx/files/4990383/ut.txt)

Hello-

the motr unit tests report memory leaks. Are these explained or expected? 

Thank you.

**Details:**
  coroutine [Anatoliy]                            0.00 sec    0 B
  [ time: 9.08 sec, mem: 72 MiB, leaked: 62 MiB ]

  sm-add [Nikita]                                 0.00 sec  332 KiB
  [ time: 0.01 sec, mem: 38 MiB, leaked: 64 KiB ]

  balloc                                          5.46 sec    1 GiB
  [ time: 5.46 sec, mem: 1 GiB, leaked: 1 MiB ]

  emap                                            0.81 sec    1 GiB
  [ time: 165.85 sec, mem: 17 GiB, leaked: 7 MiB ]

  bulkclient_test                                16.00 sec   12 KiB
  [ time: 16.00 sec, mem: 12 KiB, leaked: 56 B ]

  server-restart-nomkfs [Egor]                    0.77 sec  513 MiB
  [ time: 36.50 sec, mem: 5 GiB, leaked: 8 MiB ]

  m0_clovis_op_kick                               0.00 sec   68 KiB
  [ time: 2.05 sec, mem: 1 MiB, leaked: 12 KiB ]

  clovis_obj_namei_cb_fini                        0.00 sec   68 KiB
  [ time: 0.09 sec, mem: 1 MiB, leaked: 24 KiB ]

  m0_clovis_obj_op                                0.00 sec    3 KiB
  [ time: 0.00 sec, mem: 92 KiB, leaked: 2 KiB ]

  pargrp_iomap_dgmode_recover                     0.00 sec    4 KiB
  [ time: 0.00 sec, mem: 153 KiB, leaked: 1 KiB ]

  ioreq_dgmode_write                              0.00 sec    7 KiB
  [ time: 0.00 sec, mem: 166 KiB, leaked: 1 KiB ]

  ioreq_fop_dgmode_read                           0.00 sec    0 B
  [ time: 0.00 sec, mem: 97 KiB, leaked: 1 KiB ]

  clovis_sync_request_fop_send                    0.00 sec    2 KiB
  [ time: 0.00 sec, mem: 39 KiB, leaked: 36 KiB ]

  m0_clovis_idx_service_config                    0.00 sec    0 B
  [ time: 0.00 sec, mem: 77 KiB, leaked: 992 B ]

  lsf [Anatoliy]                                  0.01 sec  880 KiB
  [ time: 51.97 sec, mem: 786 MiB, leaked: 299 KiB ]

  composite_layer_idx_scan                        0.00 sec    0 B
  [ time: 0.00 sec, mem: 319 KiB, leaked: 5 KiB ]

  cobfoms_utfini                                  0.40 sec    2 MiB
  [ time: 1.46 sec, mem: 360 MiB, leaked: 12 KiB ]

  dir-add-del                                     0.00 sec  528 B
  [ time: 0.00 sec, mem: 66 KiB, leaked: 64 B ]

  pver-find                                       0.00 sec   45 KiB
  [ time: 0.00 sec, mem: 45 KiB, leaked: 24 B ]

  glob-errors                                     0.00 sec    0 B
  [ time: 0.00 sec, mem: 60 KiB, leaked: 96 B ]

  validation                                      0.02 sec  601 KiB
  [ time: 0.02 sec, mem: 601 KiB, leaked: 704 B ]

  walk                                            0.00 sec   60 KiB
  [ time: 0.00 sec, mem: 60 KiB, leaked: 64 B ]

  user-concur-reb [Sergey]                        0.89 sec  226 MiB
  [ time: 14.28 sec, mem: 3 GiB, leaked: 4 MiB ]

  dtx-fix                                         0.01 sec    4 KiB
  [ time: 0.03 sec, mem: 21 KiB, leaked: 4 KiB ]

  test_fd_mapping                                 0.50 sec    1 MiB
  [ time: 0.52 sec, mem: 2 MiB, leaked: 344 B ]

  fdmi-pd-fake-rec-reg                            0.02 sec   48 KiB
  [ time: 0.08 sec, mem: 240 KiB, leaked: 3 KiB ]

  fdmi-sd-send-notif                              0.02 sec   52 KiB
  [ time: 0.04 sec, mem: 106 KiB, leaked: 3 KiB ]

  filter-str-ops                                  0.00 sec    1 KiB
  [ time: 0.00 sec, mem: 7 KiB, leaked: 72 B ]

  delayed-unreachable                             0.00 sec    2 KiB
  [ time: 0.10 sec, mem: 7 MiB, leaked: 7 MiB ]

  ha-usecase                                      0.02 sec  739 KiB
  [ time: 1.72 sec, mem: 233 MiB, leaked: 441 KiB ]

  layout-pdclust-instance-failure                 0.00 sec    2 KiB
  [ time: 0.00 sec, mem: 12 KiB, leaked: 1 KiB ]

  client-server-bulk                             11.23 sec  248 KiB
  [ time: 29.66 sec, mem: 1 MiB, leaked: 64 KiB ]

  mdservice-fini                                  0.58 sec    1 MiB
  [ time: 1.08 sec, mem: 193 MiB, leaked: 194 KiB ]

  reqh                                            0.89 sec  297 MiB
  [ time: 0.89 sec, mem: 297 MiB, leaked: 126 KiB ]

  creditor-reset                                  0.76 sec  232 MiB
  [ time: 17.96 sec, mem: 4 GiB, leaked: 4 MiB ]

  two-read-locks                                  0.77 sec  232 MiB
  [ time: 6.95 sec, mem: 2 GiB, leaked: 5 MiB ]

  pool-dix-rebalance                              0.72 sec   92 MiB
  [ time: 14.04 sec, mem: 1 GiB, leaked: 38 KiB ]

**Comment by r-wambui** [comment]
Hi @truptiatseagate has option 1(Add documentation into the test program itself) been fixed or still in progress? For option 2 (Finding out whit unit tests are causing the memory leaks) could you please let's know if someone is assigned to the task?

**Comment by nkommuri** [comment]
> JIra ticket link: https://jts.seagate.com/browse/EOS-23725
> 
> @johnbent @truptiatseagate @anaghadeshmukh @nkommuri Is the solution to this issue for the long term be at the backlog and should we document for the short term solution?

yes @r-wambui

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

As part of option 1, planning to print following statement at the beginning of run-ut. 

 

diff --git a/scripts/m0 b/scripts/m0

index ace98a6..42cdd10 100755

--- a/scripts/m0

+++ b/scripts/m0

@@ -325,6 +325,11 @@ UT output:    $RUNDIR

EOF

}

 

+if [[ "$1" == "run-ut" ]]; then

+   echo "Please note that we have observed memory leaks in some UTs which we are going to address in future releases"

+fi

+

+

CMD=

OPTS=

while [ $# -gt 0 ]; do

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~530903] [~934754] [~934462]

have addressed most of this in our last several months memory leak 'hunt'?

**Comment by anaghadeshmukh** [comment]
+ Chandra

Regards,
Anagha
________________________________

**Comment by novium258** [comment]
@anaghadeshmukh Did we get an answer on this one?

**Comment by chandradharraval** [comment]
Hi @novium258, 
This memory leak is for one of the unit test and not in the code flow. Due to that we have not prioritize it. We will be fixing the same in our current PI

**Comment by nkommuri** [comment]
Closing. No plans to fix memory leaks in UTs right now. We will take this up in future. Leaks in main stream code will be prioritized and fixed.

**Comment by cortx-admin** [comment]
> Bhargav Dekivadiya commented in Jira Server:

NA

**Comment by cortx-admin** [comment]
> Bhargav Dekivadiya commented in Jira Server:

Github issue : [https://github.com/Seagate/cortx-motr/issues/77] is closed

**Comment by cortx-admin** [comment]
> Bhargav Dekivadiya commented in Jira Server:

Corresponding Github issue : [https://github.com/Seagate/cortx-motr/issues/77] is closed
