### ISSUE TITLE
Unit test fail : insmod: ERROR: could not insert module /root/cortx-motr/m0tr.ko: Invalid parameters

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#791]
Hi, 

I had encouter this error when run the test, and try the solution at #598 , but seem like no luck, any idea ?

```
[root@ssc-vm-3962 cortx-motr]# scripts/m0 run-ut
----- run_ut -----
insmod: ERROR: could not insert module /root/cortx-motr/m0tr.ko: Invalid parameters
Error loading /root/cortx-motr/m0tr.ko node_uuid=abcdef01-2345-6789-0123-456789ABCDEF Aborting.
Error unloading /root/cortx-motr/m0tr.ko.
[root@ssc-vm-3962 cortx-motr]# lctl list_nids
IOC_LIBCFS_GET_NI error 100: Network is down
[root@ssc-vm-3962 cortx-motr]#
```

**Comment by yanqingfu** [comment]
maybe try Qs2 and Qs3 https://github.com/Seagate/cortx/blob/main/doc/Build-Installation-FAQ.md

**Comment by hessio** [comment]
Hi @kiwionly2 were you able to resolve this issue? If not please let me know and I will try to help debug.

**Comment by hessio** [comment]
I have tried to log in and am unable, you can reply here when there is a resolution on your ticket

**Comment by kiwionly2** [comment]
@hessio Look like the helpdesk is get me another instance instead of find out the root cause, so I got no way to show you the error anymore, I will open another issue if I encounter this again. thanks !
