### ISSUE TITLE
should we uninstall pip setuptools?

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-motr#795]
This is an issue with [motr Quick Start Guide](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst) but it's highly related to [S3 Quick Start Guide](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md)

In Motr QSG, there is a [trouble shooting](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst#troubleshooting): 

> If the pip installation fails while installing build dependencies, run the following commands:
> 
> python -m pip uninstall pip setuptools
> sudo scripts/install-build-deps

When I was running `install-build-deps`, I got an issue "DistributionNotFound: ipaddress". Then I followed the trouble shooting and ran `python -m pip uninstall pip setuptools`. 
It worked great, I managed to build motr and passed the unit tests.

However, later when I followed the S3 Quick Start Guide, and when I was [running "`./init -a`"](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#12-installing-dependencies), I got the following error:

```
TASK [install pip module python-ldap for cipher account] ***************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pkg_resources
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (setuptools) on skylake's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

RUNNING HANDLER [restart rsyslog] **************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************
127.0.0.1                  : ok=59   changed=51   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
```

From the error message, looks like it's expecting us to have `setuptools` installed. However, I have just uninstalled it following Motr trouble shooting.

I think @nileshgovande mentioned that we should qualify Motr QSG before running S3 QSG. So I guess we may need to decide whether we should uninstall setuptools.

Regarding the "DistributionNotFound: ipaddress" problem I had when running "install-build-deps", I was able to resolve it without uninstalling setuptools. See https://github.com/Seagate/cortx-s3server/pull/1007

So maybe we shouldn't suggest uninstalling setuptools in Motr QSG, or maybe we should describe how to resolve the "Failed to import setuptools" in S3 QSG.

Thanks,
Meng

**Comment by hessio** [comment]
Hi @mengwanguc did you resolve this issue? Was this a resolution for this bug? Seagate/cortx-s3server#1007

**Comment by mengwanguc** [comment]
Hi @hessio , so the original issue is about `ipaddress` package, and it can be resolved by Seagate/cortx-s3server#1007.

However, the Motr guide troubleshooting provides a different solution `python -m pip uninstall pip setuptools`, which can cause problems later when installing s3.
So the provided solution solves a problem for motr installation, but create another problem for s3 installation.

So here I'm suggesting maybe we should replace the provided solution with the new solution Seagate/cortx-s3server#1007.

However, Seagate/cortx-s3server#1007 only resolves the `ipaddress` problem.

I'm not sure if `uninstall pip setuptools` was also intended to resolve other problems. 
If yes, then we shouldn't simply remove this solution.

That's why I opened this issue and want to discuss

**Comment by hessio** [comment]
Thanks @mengwanguc yes this makes sense. I am not sure what uninstalling setuptools will resolve, @andriytk or @huanghua78  do you know what the reason for uninstalling setuptools is? If we uninstall setuptools are we doing this for another reason or just to resolve this ip address issue mentioned above?

**Comment by huanghua78** [comment]
> Thanks @mengwanguc yes this makes sense. I am not sure what uninstalling setuptools will resolve, @andriytk or @huanghua78  do you know what the reason for uninstalling setuptools is? If we uninstall setuptools are we doing this for another reason or just to resolve this ip address issue mentioned above?

I don't know the reason of "uninstalling setuptools".

**Comment by mehjoshi** [comment]
@mengwanguc , 
I don't understand the issue. The motr Quick Start Guide says to uninstall pip if the pip installation fails.
However, you seem to have encountered a different issue:
> When I was running install-build-deps, I got an issue "DistributionNotFound: ipaddress". Then I followed the trouble shooting and ran python -m pip uninstall pip setuptools.
So, why do you suggest updating Motr QSG?

**Comment by mengwanguc** [comment]
Hi @mehjoshi , thanks for pointing it out.

I think at that time, when I was reading this troubleshooting "If the pip installation fails while installing build dependencies", my understanding was "if an installation failure related to pip happens", not "if the installation of the pip itself happens".
(though the latter should be the correct understanding as you've pointed out.)

And at that time, I got this error message:

```
Traceback (most recent call last):
  File "/bin/ansible-playbook", line 92, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 22, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 38, in <module>
    from ansible.plugins.loader import inventory_loader
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 23, in <module>
    from ansible.parsing.utils.yaml import from_yaml
  File "/usr/lib/python2.7/site-packages/ansible/parsing/utils/yaml.py", line 17, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 30, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 45, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: ipaddress
```

It seemed to me that some failure related to python package happens.
So then I followed the troubleshooting (maybe wrongly) and uninstalled pip, and it works! The error message doesn't show any more and I successfully installed Motr.

However, since I uninstalled pip setuptools, later in S3 installation, an error related to `setuptools` happens.

My current suggestions are:

1. Ask users to run `pip install ipaddress` to resolve the `DistributionNotFound: ipaddress` problem.
I thought the original documentation has covered this by asking users to uninstall pip setuptools. However, now looks like it's not the intended solution for `ipaddress` problem.

2. Discuss if we should ask users to uninstall pip setuptools.
I think you are right that I didn't have the problem of "pip installation fails". 
But I did follow the solution and uninstalled pip setuptools.
And this solution later caused a problem in S3 installation.
Thus I'm feeling it's may not be a good solution. So I'm wondering if we should keep it.

**Comment by mehjoshi** [comment]
Hi @mengwanguc.
At this point I can't clearly tell why we need to uninstall pip and setuptools. I see comments in some build config files which suggest that we are dependent on Ansible requiring python-setuptools from 2.7 for building Motr doc packages. Whether this still applies or whether this is something left behind as a residue during our development is something that will need investigation. I will open an internal ticket to track it and attach a reference to this issue/discussion. Thanks!

**Comment by imvenkip** [comment]
PR: https://github.com/Seagate/cortx-motr/pull/928

**Comment by mehjoshi** [comment]
This issue is fixed by:
EOS-23124: Improve Troubleshooting section in Quick-Start-Guide
The install-build-scripts is updated to install python-ipaddress and the troubleshooting documentation is now updated as well to better describe the failure message.
