### ISSUE TITLE
cortx-motr ut net-lnet panic

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#8]
`./scripts/m0 run-ut` failed

> fop-lock-ut
>   fop-lock-1reqh                                  0.00 sec   51 KiB
>   fop-lock-2reqh                                  0.00 sec   51 KiB
>   [ time: 0.54 sec, mem: 154 MiB, leaked: 0 B ]
> fom-stats-ut
>   stats                                           0.00 sec    1 KiB
>   [ time: 0.25 sec, mem: 77 MiB, leaked: 0 B ]
> net-bulk-if
>   net_bulk_if                                     0.02 sec   50 KiB
>   [ time: 0.02 sec, mem: 50 KiB, leaked: 0 B ]
> net-bulk-mem
>   net_bulk_mem_buf_copy_test                      0.00 sec    1 KiB
>   net_bulk_mem_tm_test                            0.00 sec  352 B
>   net_bulk_mem_ep                                 0.00 sec  744 B
>   net_bulk_mem_failure_tests                      0.00 sec    4 KiB
>   net_bulk_mem_ping_tests                         7.00 sec  200 KiB
>   [ time: 7.00 sec, mem: 207 KiB, leaked: 0 B ]
> net-lnet
>   net_lnet_fail                                   0.00 sec  288 B
>   net_lnet_tm_initfini                            0.00 sec  232 B
>   net_lnet_tm_startstop                          24.43 sec    6 KiB
>   net_lnet_msg                                   12.21 sec    5 KiB
>   net_lnet_buf_desc                              12.20 sec    4 KiB
>   net_lnet_bulk                                  22.20 sec    5 KiB
>   net_lnet_sync                                   6.10 sec    4 KiB
>   net_lnet_timeout  motr[06394]:  4290  FATAL  [lib/assert.c:48:m0_panic]  panic: Unit-test assertion failed: m0_atomic64_get(&test_timeout_ttb_called) >= 2 * timeout_secs at test_timeout_body() (net/lnet/ut/lnet_ut.c:2033)  [git: cortx1.0-rc1-165-g1efc5498e] /var/motr/m0ut/m0trace.6394
> Motr panic: Unit-test assertion failed: m0_atomic64_get(&test_timeout_ttb_called) >= 2 * timeout_secs at test_timeout_body() net/lnet/ut/lnet_ut.c:2033 (errno: 0) (last failed: none) [git: cortx1.0-rc1-165-g1efc5498e] pid: 6394  /var/motr/m0ut/m0trace.6394
> /var/cortx/cortx-motr/motr/.libs/libmotr.so.1(m0_arch_backtrace+0x20)[0x7ff418209c20]
> /var/cortx/cortx-motr/motr/.libs/libmotr.so.1(m0_arch_panic+0xe6)[0x7ff418209dd6]
> /var/cortx/cortx-motr/motr/.libs/libmotr.so.1(+0x374004)[0x7ff4181f9004]
> /var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x26b442)[0x7ff4198df442]
> /var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x214406)[0x7ff419888406]
> /var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x212e77)[0x7ff419886e77]
> /var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(+0x2131f0)[0x7ff4198871f0]
> /var/cortx/cortx-motr/ut/.libs/libmotr-ut.so.0(m0_ut_run+0x25e)[0x7ff4198ded7e]
> /var/cortx/cortx-motr/ut/.libs/lt-m0ut(main+0x1156)[0x4044d6]
> /lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff416983555]
> /var/cortx/cortx-motr/ut/.libs/lt-m0ut[0x40462a]
> /var/cortx/cortx-motr/utils/m0run: line 397:  6394 Aborted                 (core dumped) $(srcdir_path_of $binary) "$@"

but run net-lnet alone was not failed.

> [root@ssc-vm-0958 cortx-motr]# ./scripts/m0 run-ut -t net-lnet
> ----- run_ut -t net-lnet -----
> net-lnet
>   net_lnet_fail                                   0.00 sec  288 B
>   net_lnet_tm_initfini                            0.00 sec  232 B
>   net_lnet_tm_startstop                           4.01 sec    6 KiB
>   net_lnet_msg                                    2.00 sec    5 KiB
>   net_lnet_buf_desc                               2.00 sec    4 KiB
>   net_lnet_bulk                                  12.00 sec    5 KiB
>   net_lnet_sync                                   1.00 sec    4 KiB
>   net_lnet_timeout                                5.50 sec    4 KiB
>   [ time: 26.54 sec, mem: 31 KiB, leaked: 0 B ]
> 
> Time: 26.54 sec, Mem: 31 KiB, Leaked: 0 B, Asserts: 1248
> Unit tests status: SUCCESS
> utime 0.158871 stime 0.075492 maxrss 44732 nvcsw 2716 nivcsw 27
> minflt 10524 majflt 2 inblock 0 oublock 33584
> rchar 95461 wchar 1540 syscr 234 syscw 56
> read_bytes 0 write_bytes 17195008 cancelled_write_bytes 0

**Comment by huanghua78** [comment]
This issue has not been reproduced for a long time.
It is now closed.
