### ISSUE TITLE
A 4-nodes Cluster deployed, but I/O test catch errors

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-motr#816]
### A little bit of background
I am following Motr [Readme](https://github.com/Seagate/cortx-motr/wiki/Build-Motr-from-Source-in-a-Cluster) that build motr from source and deploy it across the cluster. I am using Chameleon cluster (4 nodes). I can run single-node Motr successfully on each node. **The I/O test for the single-node also went well.** 

I am also able to do passwordless ssh to/from all the nodes in the cluster, including as `root`.

### Problems
It arises when I run 
```sh
/opt/seagate/cortx/hare/libexec/m0crate-io-conf >/tmp/m0crate-io.yaml
dd if=/dev/urandom of=/tmp/128M bs=1M count=128
sudo m0crate -S /tmp/m0crate-io.yaml
```

The error:
```sh
motr[207192]:  ba80  ERROR  [io_req_fop.c:210:io_bottom_half]  ioo=0x7f67400025a0 from=10.52.2.216@tcp:12345:2:2 rc=-28 ti_rc=-28 @<430000081b375e4a:6c6f1ad6391fb78b>
motr[207192]:  aa80  ERROR  [io_req_fop.c:210:io_bottom_half]  ioo=0x7f67300024c0 from=10.52.2.216@tcp:12345:2:2 rc=-28 ti_rc=-28 @<4300000653a61886:74237eb429544faf>
motr[207192]:  9a80  ERROR  [io_req_fop.c:210:io_bottom_half]  ioo=0x7f6738002cc0 from=10.52.2.216@tcp:12345:2:2 rc=-28 ti_rc=-28 @<430000004556e830:29834d192f044875>
......
```

### Trace file contains:
- the error in details
- multinode-CDF.yaml
- m0crate-io.yaml
- and some stuff that might be useful to look at

[trace.txt](https://github.com/Seagate/cortx-motr/files/6751061/trace.txt)
 
### Setup
I can't keep the cluster for a long period of time. So, if you have any suggestions when my reservation has ended, I might try it on a smaller (2 nodes) cluster. I also can give you access to the cluster. 

Thanks.

**Comment by madhavemuri** [comment]
@daniarherikurniawan : I suspect some ENOSPACE error here.
Can you run `m0reportbug` utility on each node, which collects support bundle on each node and share it here.
Also post output of  `df -h`, `lsblk` and `hctl status --json` here.

**Comment by daniarherikurniawan** [comment]
Hi @madhavemuri! Thx for the feedback. I solve the problem after checking the `lsblk`! Turns out, one of the server doesn't have "loop" devices. If we run `sudo losetup /dev/loop$i /var/motr/disk$i.img` twice, it will cancel the setup. In my case, I run it twice, thus I have no loop devices in place.

I will suggest a few changes to the Readme to help improve the debugging process.
Close this for now. Thx!
