### ISSUE TITLE
list all keys in a client index key-value store

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-motr#830]
Hello,

I'm wondering is it possible to list all the keys in a client index key-value store?

By reading [idx.h](https://github.com/Seagate/cortx-motr/blob/main/motr/idx.h), looks like it's not supported yet, as it only implements 4 types of index operations (PUT, GET, DEL, NEXT).
But I want to double check in case I missed anything.

---
The background is that I want to implement a [go-datastore](https://github.com/ipfs/go-datastore/blob/master/datastore.go#L94) based on motr, and the datastore requires a [`Query(q query.query)`](https://github.com/ipfs/go-datastore/blob/master/query/query.go) function.

I assume currently index Key-Value store doesn't support queries. 

So a native way to implement this query function is to list all the keys, and then check the keys one by one to see if each key satisfies the query.

That's why I want to check if it's possible to list all the keys, which sounds easier to implement than query functionalities.

**Comment by hessio** [comment]
Hi @mengwanguc I think you are right it is not available.

cc @andriytk

**Comment by andriytk** [comment]
NEXT operation is there exactly for this purpose.

**Comment by mengwanguc** [comment]
> NEXT operation is there exactly for this purpose.

Ah I see. Do you mean NEXT is like a circular list iterator so that we can do:

k = NEXT(firstKey)
while (k != firstKey) {
    k = NEXT(k)
}

I thought it's a one-direction list so NEXT will reach end somehow. But if it's a circular iterator then it makes a lot of sense.

**Comment by mengwanguc** [comment]
Hi @andriytk , I think my another question is how can user get the start key, if the user had no knowledge of the key-value store? (i.e. the user doesn't know any key at all)

**Comment by andriytk** [comment]
Read more about it here - https://github.com/Seagate/cortx-motr/blob/e822f3af0eab46fc76cb52c6274b94cb5eaa3022/motr/client.h#L1445-L1458

**Comment by mengwanguc** [comment]
> cortx-motr/motr/client.h

Thanks! This answers all my questions!

**Comment by johnbent** [comment]
@mengwanguc , can you please try to figure out why you didn't find this info yourself?  I don't think it is your failure!  I think the documentation needs to be improved.  So, can you please retrace your steps searching yourself for this information and find the place where it should be but isn't?  And then add it?  And then please add @andriytk as a reviewer to the PR?

**Comment by mengwanguc** [comment]
Hi @johnbent , sure!

I think that was because when I was reading [idx.h](https://github.com/Seagate/cortx-motr/blob/main/motr/idx.h) for index key-store information, it only says "given a set of key balabala.."..  So I had the impression that users must give the starting key when calling `NEXT`. However, that's not true, as NEXT can still work even if user doesn't give the starting key.

I will add to the documentation about what will happen if user doesn't provide a starting key.

**Comment by johnbent** [comment]
Cool.  Please feel free to add it as a comment in idx.h directly if you think that is useful.


________________________________
