### ISSUE TITLE
permission denied error when doing unit test

### ISSUE THREAD

**Issue by kimika88** [Seagate/cortx-motr#837]
-bash-4.2$ sudo ./scripts/m0 run-ut
error fetching identities for protocol 2: agent refused operation
[sudo] password for (userid):
----- run_ut -----
/usr/bin/ld: cannot open output file /home/(userid)/code/cortx-motr/ut/.libs/17523-lt-m0ut: Permission denied
collect2: error: ld returned 1 exit statusn-bash-4.2$

**Comment by johnbent** [comment]
Hello @kimika88 , thanks for trying out CORTX!  Sorry to hear you ran into an issue.  Can you please let us know which set of instructions you were following when you hit this error?

**Comment by kimika88** [comment]
Hi @johnbent I am following the quick start guide: https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst

**Comment by johnbent** [comment]
Thanks.  And what is your test environment?

**Comment by kimika88** [comment]
I am on a vm with CentOS 7.9.2009 x86_64

**Comment by imvenkip** [comment]
@kimika88  Please follow below steps.

1. mkdir /home/<userid>/share
2. chmod 777 /home/<userid>/share
3. sudo bash
4. cd /home/<userid>/share
5. git clone --recursive https://github.com/seagate/cortx-motr.git
6. cd cortx-motr/
7. ./scripts/install-build-deps
8. ./scripts/install-motr-service --uninstall
9. ./scripts/m0 rebuild
10. ./scripts/install-motr-service --link
11. ./scripts/m0 run-ut

**Comment by johnbent** [comment]
Thanks @imvenkip !  Is this different than the instructions in https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst?

**Comment by imvenkip** [comment]
@johnbent Yes. @kimika88 is trying with regular user. I am suggesting to try with root user.

**Comment by kimika88** [comment]
Thanks @imvenkip , this instruction is helpful.

**Comment by kimika88** [comment]
Just to note that I need to constantly chaning permissions to the newly created files unless in the root directory.
