### ISSUE TITLE
Missing perl-YAML-LibYAML when run scripts/m0 make

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#859]
Hi, 

When I run `scripts/m0 make`, I had encounter this.

![image](https://user-images.githubusercontent.com/77140436/125887300-fd68665d-3cf7-4ae1-9d5f-5249e50c1f1f.png)

After I installed `perl-YAML-LibYAML`, it work as expected.

Not sure should we add a check and auto install not available ?

**Comment by mehjoshi** [comment]
Did you run motr/scripts/install-build-deps? Normally, it should install the needed pre-requisites.

**Comment by nkommuri** [comment]
Closing as everything works fine now.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Linked Github issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
