### ISSUE TITLE
Build stop when encounter Lustre network error

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#860]
Hi, 

I encounter error when build motr which related to Lustre.

![image](https://user-images.githubusercontent.com/77140436/125887822-8d4d23ac-01b4-4ebf-b984-34878a394de3.png)

any idea ?

**Comment by kiwionly2** [comment]
Hi @hessio, 

Not sure if you free to help me take a look.

My self service  cloud instance is ssc-vm-6193.

**Comment by hessio** [comment]
Hi @kiwionly2 yes I will try to take a look either today or tomorrow, sorry for the delay

**Comment by hessio** [comment]
Oh I see in the image you are not logged in as /root user.
If you run: `sudo su -` you should switch to root user and be able to complete this installation

**Comment by kiwionly2** [comment]
Thanks @hessio , I rebuild m0tr with root user and is working now.

We need root user is it because I am running in the Seagate self service cloud ?

**Comment by huanghua78** [comment]
Building Motr itself does not require "root" user.
But you need to install some packages with root user before building.
Please run  ./scripts/install-build-deps with root user.

**Comment by kiwionly2** [comment]
@huanghua78 

I was able to build with root user ( in Seagate Self Service Cloud ) with no error.

However when I was build not using root, it hit with this error.

Previously I could build m0tr not using root user and it work without this error.

**Comment by huanghua78** [comment]
This is not a good practice. Especially on a NFS mounted home dir.
When you first time built Motr with root user, it created some files, including configure files and some symlink files.
Later, when you again built Motr with normal user, the building system may still be using some of these files. But these files are not accessible to a normal user.
Especially, on a NFS mounted home dir, the files generated by root user, are mapped to some other UID.
This depends on NFS server configuration.
This will cause some problems in some cases.

**Comment by kiwionly2** [comment]
I encounter configure error for lnet ( detail at the top of description ) when I am running build with own user account ( normal user).
After I rebuild with root user as per @hessio suggest, the build is working now.

Now I build again with my own user account which fail previously, everything is working now, and I no longer able to reproduce this error.

Not sure If running unit test after build could detect any of these problem as you mentioned.

**Comment by mehjoshi** [comment]
@kiwionly2, I see that you are not facing this issue anymore. So, I will go ahead and close this issue. Feel free to re-open incase you disagree.
