### ISSUE TITLE
Lustre network failed to start

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-motr#9]
I was trying to follow this Quick Start Guide, [Building the Source Code](https://github.com/Seagate/cortx-motr/blob/dev/doc/Quick-Start-Guide.rst#building-the-source-code). I got this error at the second step: `IOC_LIBCFS_GET_NI error 100: Network is down` when running `sudo lctl list_nids`. The wiki said "... to check if the lustre network is functioning accurately...",  would be great if it also provides some hints on how to debug when lustre doesn't work properly.  

I am running on the `CentOS Linux release 7.7.1908 (Core)` with kernel: `Linux 3.10.0-1062.12.1.el7.x86_64`. 

The lustre installation seems to be successfully executed:
```
Transaction test succeeded
Running transaction
  Installing : lustre-client-devel-2.12.4-99.el7.x86_64                     1/1
  Verifying  : lustre-client-devel-2.12.4-99.el7.x86_64                     1/1

Installed:
  lustre-client-devel.x86_64 0:2.12.4-99.el7
```

**Comment by andriytk** [comment]
@daniarherikurniawan in the troubleshooting section of the guide doc you mention there is following:

> If lctl list_nids does not render an output, perform the following steps:...

Have you tried the steps mentioned there? Especially, pay attention to /etc/modprobe.d/lnet.conf file and the interface configuration there. Please, let us know if it helps. Thanks.

**Comment by daniarherikurniawan** [comment]
Yes, it works. Thank you for updating the guide doc.
